brucemiller/LaTeXML

lib/LaTeXML/Common/Config.pm

Same treatment for ```--log``` as we do for ```--destination``` in terms of auto-making their directory.
(Aside: It is a bit awkward to do dev work while libxml is raising validity errors everywhere, but I am pretty certain this works as intended)

Fixes #575

---

lib/LaTeXML/Post/MakeBibliography.pm

Fixes #583 
In the end it was easy to make a pull request that solves the problem. Here is a screenshot of the result:

Abbreviate alpha cite labels to the third letter

---

lib/LaTeXML/Package/lxRDFa.sty.ltxml
lib/LaTeXML/Util/Pack.pm
lib/LaTeXML/texmf/lxRDFa.sty

Adds a [labels] option to lxRDFa.sty, which auto-generates RDFa for LaTeX labels.
Example use:
```
latexmlc --preload=article.cls --preload=[labels]lxRDFa.sty 
--whatsin=fragment --whatsout=fragment --format=html
'literal:\section{Foo}\label{bar}test' 
```
Output:
```html
<article class="ltx_document" prefix="dcterms: http://purl.org/dc/terms/">
<section id="S1" class="ltx_section" property="dcterms:alternative" content="bar">
<h2 class="ltx_title ltx_title_section"><span class="ltx_tag ltx_tag_section">1 </span>Foo</h2>
<div id="S1.p1" class="ltx_para">
<p class="ltx_p">test</p>
</div>
</section>
</article>
```

[labels] option for RDFa auto-preservation of TeX labels

---

lib/LaTeXML/Common/Model.pm
lib/LaTeXML/Common/Model/RelaxNG.pm

In sTeX, we are currently seeing inconsistent XML produced on different runs of LaTeXML, as shown here:
https://github.com/KWARC/sTeX/issues/68#issuecomment-93775585
Interestingly, we were getting inconsistent output only when LaTeXML was starting up from scratch. During daemonized runs the output was consistently the same. This lead me to believe there are possible non-deterministic interpretations of the sTeX schema.
We are using an already pre-compiled model, as in:
```
(Loading compiled schema /home/dreamweaver/localmh/ext/sTeX/schema/omdoc+ltxml.model... 0.03 sec)...... 0.14 sec)
```
Which reduced the possible causes.
As it turns out, we need to be extra careful with sorting hash keys in ```LaTeXML::Common::Model``` and ```LaTeXML::Common::Model::RelaxNG```, as the different orders …

Consistent Model Interpretation

---

lib/LaTeXML/Post/CrossRef.pm

This is a minor change with an important impact for my server-side use of LaTeXML. Key points of understanding:
* BibTeX keys are case insensitive. LaTeXML uses a lower-cased canonical form to accommodate that, which is great.
* While lookup should work in a case-insensitive manner, the actual key value shouldn't be changed, in terms of reporting the key back to the log or output.
* In my use, I need the missing citations to be recorded on output with the exact key written in the source, in order to have some sanity and not worry about special normalizations LaTeXML has a preference towards.
This PR preserves the functional behaviour, while leaving the key intact for output. Feedback welcome!

Downcase citation keys only for lookup

---

lib/LaTeXML/Package/grffile.sty.ltxml

It extends the pathname capabilities of graphicx, which (I am almost certain) is already supported by native LaTeXML.
We use this LaTeX style at Authorea, so I am sending over a stub binding to the LaTeXML master.

grffile.sty.ltxml

---

lib/LaTeXML/Core.pm
lib/LaTeXML/Core/Mouth.pm
lib/LaTeXML/Package/listings.sty.ltxml

It took me a while to realize why the listing language styles were being reloaded on every daemonized conversion job, and then I saw this wonderfully helpful commented out code.
I would like to make a very warm request for including it, as the speedup it grands in daemon mode is in the order of 5+ seconds, while classic mode wouldn't experience much of a hit.
I also included a very helpful 10 character snippet of the mouth content when reporting that a Literal String is being processed, so that the logs are a lot more informative. For example this helped me figure out I had to be looking at \lstset:
```
(Processing content Literal String \subsectio...
(Processing content Literal String \lstset{ %...
(Digesting TeX Anonymous String...
(Processing content Literal String \end{docum... …
```

Daemon-friendly listings and literal strings

---

lib/LaTeXML/Package/LaTeX.pool.ltxml
lib/LaTeXML/Package/natbib.sty.ltxml
t/daemon/formats/citation.xml
t/daemon/formats/citationraw.xml
t/theorem/amstheorem.xml

The goal of this pull request is to preserve more of the information we originally had in the TeX source to the XML output of LaTeXML.
In particular, I have added a hook for preserving the macro name of (natbib and core) citation commands (such as ```\citep``` or ```\citet```) as an optional argument to the internal ```\@@cite``` macro. I am happy to refactor if you find flaws in the approach.
My personal goal here is to apply different CSS styling to the different macros, when dealing with an HTML version of the input.

Preserve cite macro information as class attribute

---

lib/LaTeXML/Post/CrossRef.pm

For cases such as natbib, the fill-in "show" pattern becomes quite complex (e.g. ```AuthorPhrase1, AuthorPhrase2``` or similar). 
In the case for missing citations, I think we agreed in one of the previous pull requests, that we just want to propagate the citation key back into the XML, as a form of user-facing error report. This behaviour is currently broken under natbib, where you could get ```<cite>``` contents such as ```[]``` or ``` , ```.
So, with this pull request I am doing a simple circumvention of the ```show``` parser in the case of missing citations, which ensures we get the citation key into the final XML output.

Simple crossref fill-in for missing citations

---

lib/LaTeXML/Post/MathML.pm

This is a stop gap measure to preserve all RDFa attributes in top-level math elements, akin to the way LaTeXML has been preserving image-related attributes.
Maybe it helps move the discussion forward, maybe it gets merged. I have tested and it does exactly what I would expect it to - the MathML <math> element can be seen carrying RDFa attributes e.g. in LaTeXML's HTML output.

Preserve RDFa in MathML

---

lib/LaTeXML/Package/hyperref.sty.ltxml
lib/LaTeXML/Package/nameref.sty.ltxml
lib/LaTeXML/Post.pm
t/post/hyperref-post.xml
t/post/hyperref.xml
t/structure/hyperref.tex
t/structure/hyperref.xml

* Added support for nameref.sty.ltxml
* Fixed an argument counting bug for \autoref, cleaned up double definition
* Trimmed "tag"s from shown titles in CrossRef
* Added classes for ref macro names 
* this bit is openly Authorea-motivated, as we are doing the labels and referencing outside of LaTeXML and would like to know the macro information, so that we created the right label
* Added tests

nameref.sty.ltxml

---

lib/LaTeXML/Common/Config.pm

Until now, LaTeXML would only look for profile ```.opt``` files in its own resource directory, ignoring user-supplied paths.
However, this hinders using custom profiles, and is also problematic for testing plugin modules. As ```make test``` executes the tests using the built ```blib``` directory, prior to installing LaTeXML, it becomes a necessity to be able to specify the built directories as search paths for LaTeXML, as in this example:
https://github.com/KWARC/LaTeXML-Plugin-MathWebSearch/commit/2b8838b3e5dc6a6105572c27d0dc52075b646c7b#diff-d0d26286eac2af991850ff3ab61960c8R16
My other request is that after merging here we also increment the minor version number of LaTeXML and push a new release to CPAN, so that I can have a successfully building plugin release of …

Search for profiles in LaTeXML's --paths

---

lib/LaTeXML/Package/acronym.sty.ltxml
lib/LaTeXML/resources/XSLT/LaTeXML-structure-xhtml.xsl

Fixes #623
I am not sure this is the "optimal" fix, but the minimal example now behaves as expected:
```tex
\usepackage{acronym}
\newacro{HST}{Hubble Space Telescope}
\newacro{RGB}{Red Giant Branch}
Testing \ac{HST} and \ac{RGB}, \ac{RGB} and \ac{RGB}.
\end{document}
```

Acronyms now behave as expected in preambles

---

lib/LaTeXML/Package/LaTeX.pool.ltxml

Huge thanks to @brucemiller who tutored me through this enhancement.
LaTeXML has a brilliant design for dealing with boxes and the intricacies of TeX, as long as one manages to properly get the design in focus.
Now that I did, here is a super simple pull request that preserves ```\nonumber``` in the TeX revision source, so that follow-up applications can benefit from it.

\nonumber is now preserved in the TeX revision

---

t/alignment/eqnarray.xml

Reverts brucemiller/LaTeXML#637
Sorry, this just really isn't the right way to go for this. The TeX string ought, in my view, to be "clean" math markup. nonumbers, labels, etc are document-level stuff, that are embedded in the math.

Revert "oops, forgot to update test files"

---

lib/LaTeXML/Package/LaTeX.pool.ltxml

Reverts brucemiller/LaTeXML#636
Again, this really isn't the right approach to the underlying problem...

Revert "\nonumber is now preserved in the TeX revision"

---

bin/latexmlc

I just spent an unreasonable amount of time debugging broken ZIP archives produced by ```latexmlc```. It turns out I was bravely encoding all output data as UTF-8, **including** the binary archive data. Ooops!

Dont encode archive whatsouts, they are binary

---

bin/latexmlc

This PR fixes a minor (but relevant) file pollution when running:
```
latexmlc --log=some.log --whatsout=archive
```
As it were, the log file was written inside the archive (as intended) **and** on the file system itself (unintended). latexmlc should simply avoid creating log files when an archive is requested (but still print out log info to STDERR otherwise).
The unintended log files were polluting my CorTeX runs - which I am basing on latexmlc now.

Log file only gets written in archive for --whatsout=archive

---

lib/LaTeXML.pm

I was bitten by the colors while parsing STDERR from latexmls, which binds STDERR **after** the Error module is loaded.
Using a package-level var for ```COLORIZED_LOGGING``` is nice for performance, so I kept that as-is, but also added the checks to ```bind_log``` and ```flush_log``` which are responsible for changing STDERR.

Redetermine colorize logging any time we rebind STDERR

---

bin/latexmlc

This is a cosmetic PR, following up on my last encoding patch, aiming to avoid an annoying warning when ```--whatsout``` is not specified to latexmlc.
Here is the issue requesting it:
https://github.com/KWARC/sTeX/issues/136

Unset whatsout was raising a warning, silence it

---

lib/LaTeXML/Util/Image.pm

This was a bit tricky to get right, but I think I got the best possible solution here.
I started with a pure-Perl solution adding:
```perl
push(@args, 'memory-limit', '512MiB',
'map-limit', '1GiB',
'disk-limit', '2GiB',
'time-limit', 300);
```
before the first 'Set' operation. However, with testing I found out that these options **override** the environmental variables, which means that users would be unable to modify these LaTeXML settings.
The solution in the PR allows users to specify ImageMagick environmental variables **from outside** to LaTeXML, and thus adjust the settings as needed. I only set a default (arXMLiv-motivated) upper bound for memory, map, disk and time, if they were not already set prior to the latexml process starting. I tested this extensively and it works exactly …

Defensive upper-bounds for ImageMagick conversion jobs

---

lib/LaTeXML/Package/nameref.sty.ltxml

I wanted to see if we can get #611 closed with a simple binding extension. Some of the details around the page-enhanced referencing simply don't apply to HTML, and while they can be reimagined, I don't have the incentive to get the perfectly right now.
The docs for the package are [here](http://mirror.ctan.org/macros/latex/contrib/hyperref/nameref.pdf)

Basic support for the family of nameref macros

---

lib/LaTeXML.pm
lib/LaTeXML/Common/Config.pm

The core+post workflow now has unified error-reporting, with more robust reports for post-proc and archive whatsouts.
As it turns out, if there was a Fatal error (via a Perl die) in post-processing, when creating an archive as output, the entire log was not being written out, as the archive was never created in the first place.
The reason for that was that the ```eval``` guard was wrapping the entire post-processing call, wrapping also the archive creation logic.
In this PR I have improved on that end, and finally unified the error-reporting codes (albeit in a hacky way) by:
* Making the ```eval``` guard only wrap ```$latexmlpost->ProcessChain```, hence always writing an archive with a log file (in the CorTeX setup).
* Ensuring that the final ```status_code``` is the max of the combined …

Unified error-reporting in core+post processing

---

lib/LaTeXML/Common/Config.pm

This is a convenience method that allows me to check if certain options have been "defined" (without actually getting their content) from peripheral services, such as the latexmls socket server.

Adds defined method for Config objects

---

lib/LaTeXML.pm
lib/LaTeXML/Util/Pack.pm

1.52% of arXMLiv's conversion currently exhibits "no message" fatals, a lot of which seem to be caused by a failure to detect the main TeX file in the source archives.
This PR checks if there is no .tex file present in the archive, and if so checks all files without extensions as possible candidates for a main source file.
I have tried it on a couple of arXiv papers and it converted both to no problems, which seemed promising!

Fallback to files without extensions, when no .tex file is present

---

lib/LaTeXML/Common/Error.pm

Small change, but dramatic improvement on reading the logs in the command line.

use bright blue for info, the regular blue looks horrible on Unity

---

lib/LaTeXML/Util/Pack.pm

The size of the diff is misleading here, it's mostly a re-indent of a block. The PR does a single change - removes the early exit if there is a single .tex file in a ZIP archive.
Instead, it still performs the heuristic check, which can determine the .tex file is invalid and throw a "Fatal:invalid:Archive" rather than a rather bizarre alternative error. It also has the nice side-effect of filtering out withdrawn papers from the corpus.
If we merge here, I would need to rerun both Fatals and no-problems (as many withdrawn papers may have ended as "no problem" snippets), and will add a special "invalid" category for the reports, based on the "Fatal:invalid" messages.

Check single-file archives, as some may have %auto-ignore from arXiv

---

lib/LaTeXML.pm
lib/LaTeXML/Core/Mouth/file.pm

My last PR was not explicit enough with writing the invalid fatal to the log file (it's in LaTeXML.pm, so it is hard-printed, rather than using the Error API)
So here is one more commit that adds the info to the log, and makes it parseable by systems such as CorTeX.

Write invalid fatal info to log

---

lib/LaTeXML/Package/TeX.pool.ltxml

In https://github.com/KWARC/LaTeXML-Plugin-sTeX/issues/20 we discovered that parameter of type `CommaList` becomes empty when we provide it with a list. The primary cause is that the original `CommaList` when taking a list of arguments always pushes an empty `@tokens` to the `@items` and we construct an Array based on the item list.
Because the if else snippet does not capture the situation when the `$token` is a regular token and thus the tokens we want were never added to the `@tokens`
```perl
if ($token->equals(T_END)) {
push(@items, Tokens(@tokens));
last; }
elsif ($token->equals($comma)) {
push(@items, Tokens(@tokens)); @tokens = (); }
elsif ($token->equals(T_BEGIN)) {
push(@tokens, $token, $gullet->readBalanced->unlist, T_END); }
```

Fix the empty items when CommaList parameterType actually takes a list

---

lib/LaTeXML/Package/TeX.pool.ltxml

The real-world example I am looking at had a ```\input{preamble.tex}``` at the top of its main file, which worked just fine when typeset with ```pdflatex```.
To emulate that, I suggest that LaTeXML keeps an eye for braced ```{filename}``` wrappers in the bare ```TeXFileName``` paramater type, and load the LaTeX.pool definitions when spotted.
I probably have a blind spot for unexpected side-effects, especially since I am not familiar with all cases in which ```TeXFileName``` is used. So I am open to refactor if you can predict side-effects.
Thanks for reviewing!

Auto-load LaTeX when braced form is seen in TeXFileName parameters

---

lib/LaTeXML/Core.pm
lib/LaTeXML/Core/Document.pm

Basic fix for #741 , which disables math ligatures entirely, when the noparse option is specified.
A more advanced fix would attack the problem at its root and e.g. only apply ligatures to the last N children of the current parent, using efficient libxml methods such as a combination of ```->lastChild``` and ```->previousSibling```.

Disable math ligatures for --noparse option

---

lib/LaTeXML.pm
lib/LaTeXML/Common/Error.pm
lib/LaTeXML/Core/Document.pm

A number of stability improvements for daemonized processing here:
1. The daemon initialization code was never wrapped in a timeout, I have added one
2. Marked some Fatal errors as explicitly "unsafe", so that daemon processes are forced to reinitialize from scratch (motivation below)
3. The reporting of "insertion context" for absorbtion errors prints enormous XML dumps on screen, which are almost always unnecessary/overwhelming, even to a developer. I have found the context of 5 levels deep to be both brief and sufficiently informative for the examples I have. Maybe this should also depend on verbosity?
4. Minor: improved ALRM message text a little
**Motivation:**
Some Fatals have proven to corrupt the State. In particular certain deep recursions (inf. loops?) in the absorbtion stage …

Introducing UNSAFE_FATAL, trimming insertion context traces

---

.travis.yml
lib/LaTeXML/Util/Pathname.pm

[ @dginev edited with description]
Thanks to @physikerwelt  for opening the pull request and initiating the Travis discussion via email. I assume the travis file is borrowed from KWARC/LaTeXML.
Let me write a brief justification for @brucemiller since I suspect he hasn't been sucked in the Travis madness.
The idea is that while CPAN Testers would provide us a test harness for the releases, Travis can already provide us with quick regression testing on every push to git. It is usual to combine the build with a badge, you can see the "build |passing" button in the README of [KWARC/LaTeXML](https://github.com/KWARC/LaTeXML) for an example.
After merging the ```.travis.yml``` file, you also need to enable builds from the travis site, after which each push to git will be build and recorded, so …

Add travis support

---

bin/latexmlc

This is a minor fix, since nothing was (functionally) broken. Code was still unintentionally wrong though.
But that was by sheer luck - the latexmls calls were using out-of-scope local variables, that happened to be in the global script scope, rather than the variables passed in as arguments. Oops.

Mixup with the request variables in calling latexmls

---

lib/LaTeXML/Common/Config.pm

As described.
I only had time to update the synopsis tonight, there are still missing methods in the details section that I should copy over from latexml/latexmlpost. Also, some bits may be outdated, as you keep updating the documentation of the classic executables, but it doesn't propagate to Config.pm.
Maybe we merge here and bump the rest of the issue to 0.8.3? Writing docs is hard! Especially for the just over 100 option entries in the synopsis! Proofreading sure took a while.
Oh, and I even caught a minor bug in Config.pm, I had missed out on the ```--noparallelmath``` option!

Updating POD synopsis with all supproted options by Common::Config

---

lib/LaTeXML/Package/listings.sty.ltxml

I have seen a regression in one of my listings today that looks just about like:
```tex
\begin{lstlisting}
{\color{BrickRed}♥}
\end{lstlisting}
```
The unicode heart was breaking with a Perl:die due to a wide string. The fix in this PR makes that work as expected instead.

Handle UTF-8 in listings data

---

bin/latexmlc
lib/LaTeXML/Common/Config.pm

I had rearranged the docs, and had forgotten that I am using an advanced sections selector of pod2usage, which made ```latexmlc --help``` return an empty value, rather than the synopsis string.
This pull request fixes this.

Fixes #792 (regression with latexmlc documentation)

---

lib/LaTeXML/Util/Pack.pm

This is an embarrassing oversight on my part - i had swapped the places of the grep/map pair, grepping on perl objects, instead of the file name held by them.
That lead to archives with no TeX file from the arXiv corpus to be falsely searched through, and in fact often ```.cls``` and ```.sty``` files were being converted in the absence of a real source, due to this error.
An example directory tree I just tested with looks like:
```
-rw-r--r-- 1 dreamweaver dreamweaver  41139 Jun 29  2004 llncs.cls
-rw-r--r-- 1 dreamweaver dreamweaver  12121 Jun 29  2004 mathpartir.sty
-rw-r--r-- 1 dreamweaver dreamweaver   4209 Jun 29  2004 welldef.bbl
-rw-r--r-- 1 dreamweaver dreamweaver  87850 Jun 29  2004 welldef.tex.cry
```
As the authors used an encrypted ```.cry``` file, this archive contains no …

Fix bug with wrongly checking all files inside archive input

---

lib/LaTeXML/Core/Token.pm

This fixes the typo at the bottom of http://dlmf.nist.gov/LaTeXML/manual/coremodules/LaTeXML_Core_Token.html
in the description of getCSName

fixes typo in LaTeXML::Core::Token documentation

---

lib/LaTeXML/Common/Model.pm
lib/LaTeXML/Package.pm

A little cosmetic improvement I spotted while studying the code.
The trailing whitespaces removed are a side-effect of my code editor (sublime text), which right trims lines automatically. Also cosmetically appealing.

Consistently use the XML::XML_NS namespace uri

---

lib/LaTeXML/Package/LaTeX.pool.ltxml

Add `onlyPreamble` guards for class-selection LaTeX macros. The absence of these errors became apparent during an Authorea debugging session, so I'm contributing them back upstream.
The goal is that given input such as:
```
\documentclass[11pt,letter]{article}
\documentclass[letterpaper,10pt]{article}
...
\end{document}
```
We would like LaTeXML to report a preamble violation error as in:
```
Error:unexpected:\documentclass The current command '\documentclass' can only appear in the preamble
```
This is all setup already for usepackage, so just leveraging that infrastructure in this PR.
Bonus: My sublime editing environment removes trailing whitespace (that is actually a tiny speedup for RawTeX I believe)

add onlyPreamble checks for \documentclass and \documentstyle

---

lib/LaTeXML/MathParser.pm

Luckily a no-op typo, but still a very weird-looking one `=> =>`. Stumbled on it while doing secretive work around this file.

Fix typo in PREFIX_ALIAS

---

doc/site/index.tex

This commit adds instructions to the web page on how to install latexml
on archlinux and in particular how to setup dependencies.

Add archlinux setup instructions

---

bin/latexml
bin/latexmlc
bin/latexmlfind
bin/latexmlmath
bin/latexmlpost
doc/makemanual
doc/makesite
doc/manual/genpods
doc/manual/genschema
release/checkinst
tools/cluster
tools/genencoded
tools/genfontmap
tools/kwalitee
tools/latexmllint
tools/maketests
tools/pre-commit
tools/symbolscan
tools/texscan
tools/xtest

On certain machines, when run directly, all scripts would default to use
the perl interpreter located in /usr/bin. This can cause problems on
machines where perl is located in a different path, or where multiple
perl instances are present on a system (such as on Mac when using
homebrew).
This PR updates the shebang, the line which starting with #!
indicating the interpreter to use when running a file, from
/usr/bin/perl to /usr/bin/env perl. This makes sure not to hard-code the
perl path to /usr/bin, but to instead search $PATH for the appropriate
file.

Change shebang to /usr/bin/env/perl

---

.gitignore

When running `make clean`, the `Makefile` is moved to `Makefile.old`. To prevent accidental committing of the file, this PR adds it to gitignore.

Add Makefile.old to gitignore

---

.travis.yml

This PR updates the Travis tests to run both with and without TexLive installed.

Add TexLive to Travis Tests

---

tools/makemanifest

Previously, the tools/makemanifest script was written in bash. This had the problem, that the ``sort`` command was behaving different on certain Linux installations, leading to inconsistent results.
This PR rewrites the tool in pure perl, thus ensuring consistency between different systems. Furthermore, it adds three new switches to it, --quiet, --save and --diff. These can be used to suppress output, automatically overwrite the old MANIFEST file, and show a diff instead of the full new MANIFEST respectively.

Rewrite tools/makemanifest in Perl

---

lib/LaTeXML/resources/XSLT/LaTeXML-jats.xsl

This PR removes an extra non-breakable space character when using
the JATS output format.

Fix extra space in JATS output (fixes #864)

---

lib/LaTeXML/Package/lxRDFa.sty.ltxml

This PR is a follow-up to #596 and I would appreciate a quick review & merge, if possible.
It turns out that my generic recording of `\label` as metadata did not extend to packages redefining it, such as longtable.
The problem there is that longtable redefines (via `Let`) the `\label` macro on each environment start, which makes it impossible to maintain the RDFa hook I introduced globally in the preamble. However, I _can_ hook into the lower level `\@longtable@label` macro, and it all works great again!
Example test being:
```tex
\usepackage{longtable}
\usepackage[labels]{lxRDFa}
\begin{longtable}[]{@{}lccc@{}}
1 & 2 & 3 & 4 \\
\caption{\label{table:long} caption}
\end{longtable}
I should be able to refer to Table \ref{table:long}.
\end{document} …
```

Also record labels as metadata for longtables, when requested in lxRDFa

---

Makefile.PL

When generating `LaTeXML::MathGrammar`, recent versions of `Parse::RecDescent` were generating a warning about the missing `runtime_class` option. This warning indiciated that the grammar may stop working with future versions of the RecDescent package.
This PR adds the missing option to the call inside of Makefile.PL, ensuring that the default runtime `Parse::RecDescent` will continue to be used.

Fix missing runtime_class warning

---

Makefile.PL

Older versions of Parse::RecDescent did not support the third argument
to parser pre-compilation introduced in
b5aa3d04474538ea0d601d99e3e45d7a4df89aaa. This caused installation
problems for LaTeXML on older systems.
This PR fixes the problem by introducing a fallback that does not
use the third argument. This only gets triggered when the MathGrammar is
not created.

Bugfix for older Parse::RecDescent versions

---

lib/LaTeXML/Core/Box.pm
lib/LaTeXML/Core/Comment.pm
lib/LaTeXML/Core/List.pm
lib/LaTeXML/Core/Whatsit.pm

Previously, objects representing a `LaTeXML::Core::Box` were an array, whereas objects representing `LaTeXML::Core::Whatsit` (which inherit from Box) were a hash.  This led to duplication of several methods in the Whatsit class.
This PR refactors `LaTeXML::Core::Box` (and `LaTeXML::Core::List`, `LaTeXML::Core::Comment`, `LaTeXML::Core::Whatsit` that inherit from it) to be a blessed hash reference instead. This makes code within between the four classes consistent with each other, and also makes code more readable due to named access of properties.

Refactor LaTeXML::Core::Box blessed objects

---

lib/LaTeXML/Core/Gullet.pm

This was a bit of a shocker in Authorea editing. There were obvious pieces of wrong LaTeX content that never returned an error from latexml, such as:
```
\textbf{some text here
```
Importantly, this is being converted in fragment mode, and has no `\end{document}` in _the same mouth_ to throw a grouping error. This revealed a particular case of unreported errors in LaTeXML:
**When a Gullet->readBalanced call does not have a closing brace, the read silently succeeds to slurp all content until the end of the Mouth**
This can cause some serious issues if the error is committed early in a large chunk of latex, naturally. So I suggest throwing an informative error, and then proceeding as usual. It is good enough for users to correct their mistake in online editing. Example interface from …

Add error when readBalanced fails to balance at end of Mouth

---

lib/LaTeXML.pm
lib/LaTeXML/Core.pm
lib/LaTeXML/Package.pm
lib/LaTeXML/Package/LaTeX.pool.ltxml

I was investigating a Fatal conversion job from the cortex report over arXiv for a change, which happened to be a very impressive 85 manuscript:
https://arxiv.org/abs/1011.5551
They use a custom documentclass, and rather advanced latex, so we're far from "no problem" land, but can find interesting low-level fixes:
1. I wanted to quickly check if running with `--includestyles` helps, and noticed that a) latexmlc does not enable the behavior when given the option, and b) the option doesn't propagate to `LoadClass` in general. 
- The first was due to a camelCase name mismatch, the second was just never added I think.
2. Since enabling includestyles didn't really help (the loading got stuck in an infinite loop!), I next tried gradually improving coverage to avoid the Fatal error in the …

--includestyles fix for latexmlc and 1011.5551 fixes

---

lib/LaTeXML/Package/TeX.pool.ltxml

Fixes #878 
It upgrades the fatal message from the example:
```
Fatal:misdefined:LaTeXML::Package::Pool::__ANON__ Can't locate method 'valueOf' via 'missing'
at /home/deyan/perl5/lib/perl5/LaTeXML/Package/TeX.pool.ltxml line 1221, <$IN> line 3.
In Core::Definition::Primitive[\advance ... from TeX.pool.ltxml line 1221
<= Core::Stomach[@0x55f4b4414ec8] <= Core::Definition::Primitive[Begin] <= Core::Stomach[@0x55f4b4414ec8]
3 errors; 1 fatal error; 1 undefined macro[\AtBeginPart]
```
To a less critical error report:
```
Conversion complete: 3 errors; 1 undefined macro[\AtBeginPart].
```
Which is still sufficiently informative about the root cause. Feel free to review & merge @brucemiller

Safe no-op for \advance when missing definition

---

.gitignore
README.pod
doc/manual/manual.tex
doc/site/index.tex

update Mailing list

---

lib/LaTeXML/Common/Config.pm
lib/LaTeXML/Post/Graphics.pm

So, one more interesting use case for me today, with an interesting issue.
I needed to run through some latex through latexml that was "detached" from its auxiliary files (crucially: images), but I wanted to eventually reconnect the HTML result to the original images. I am happy to do some post-processing after latexml, in essence all I needed was to have the includegraphics file argument preserved in the final `src` attribute of the HTML `img` tag.
That's really easy to do! And in fact should be better practice than the current master behavior, which is to leave an empty `src=""` attribute, which is technically invalid / discouraged HTML.
I also caught a tiny bug with one conditional (for activate latexmlc post-processing) and disabled a somewhat useless guard that stops you from using …

Preserve image graphic in fragment when not found

---

doc/manual/manual.tex

An explicit "-" is needed to read from stdin.

Fix first usage example

---

lib/LaTeXML/Core.pm
lib/LaTeXML/Util/Pack.pm

This PR is a bit more critical as it fixes a long-standing (and shocking) bug with daemonized runs.
Namely, the preload `insertPI` logic was wrongly modifying the preloads directly in the latexml object, so reruns would see all preloads as extension-free and mistreat classes as packages.
if we `--preload=article.cls`, the first run would run correct, but overwrite the value to `article` (no extension) and the second daemonized run would wrongly try to load article as a package. Pretty shocking! It is painfully obvious with `--mathsvg` as the resulting `\usepackage{article}` makes the SVG conversion fail entirely, which lead me to debugging & fixing.
Additionally, I made sure to remove the cache file, which is something I borrowed from latexmlmath.

Robust preloads for daemon reruns, unlink cache for mathsvg

---

lib/LaTeXML/Util/Pack.pm

Me again. Turns out my PR yesterday was operation on `--whatsout=math` but only for the `xml` format target. I added some extra robustness so that the html family out whatsouts is also recognized.
I don't need this in a rush, since I can happily use the `xml` format myself, but may be useful in general.

Ensure mathsvg produces svg in whatsout=math when html format

---

lib/LaTeXML/Core.pm
tools/maketests

Oddly, there were two `gen_xml` methods. The one being used was shelling out to `latexml`. I am running a development environment where I haven't run `make install` and everything is in the working directory, so this doesn't work.
The other `gen_xml` method uses the library, which works with my local development environment. A nice side-effect is this is the same approach used by `make test`, which seems more resilient somehow.
Also, `convertAndWriteFile()` was broken, so I've fixed that.

Use library to generate XML in maketests instead of system()

---

bin/latexml
bin/latexmlmath
lib/LaTeXML/Post/Writer.pm

Fixes #918
No rocket science here. Maybe before merging I should go through all executables in `bin/` and ensure all default prints are using the utf8 encoding? cc @brucemiller

Use utf8 when writing to stdout in latexml

---

bin/latexml
bin/latexmlc
lib/LaTeXML.pm

Follow-up to #938 .
In fact I think this PR demonstrates why I think leaving things in the current state will cause more trouble (at least for me) down the line when I forget this discussion thread. Having identically named `toString` methods that return different types of data (unencoded Perl chars vs encoded Unicode bytes) is just awkward.
Then again I realize there are more toString methods out there, and they all use characters internally. So might as well punt with this... I just caught myself again mistakenly double-encoding in LaTeXML.pm (see line 327 in diff), it's just too opaque to easily notice which method is getting called.

More encoding cleanup

---

lib/LaTeXML.pm

While investigating #948 I spotted a broken bold 0 encoding when printing to stdout from latexmlc.
Turns out there were two cases that needed new patches
* One was the fatal error case for core processing, which was missing the encode call
* The other was the XML format case in post-processing, which was leveraging the duck-typing of all document objects (i.e. all of them having `toString`) to return differently encoded values -- since exactly one of our `toString` calls isn't returning bytes. So I added an explicit check there.
Keeps feeling awkward... I still don't care enough to raise a larger stink about refactoring :> If I hit this once again I might.

Two more wrongly encoded cases in LaTeXML.pm

---

lib/LaTeXML/Package/LaTeX.pool.ltxml

Fixes #931 . 
Simple case of over-eager heuristics, any macro that started with `\math` was treated as a signal that math mode was already activated during `--whatsin=math` processing. Clearly not the case.

Soften heuristic, was breaking mathbf macro

---

bin/latexmlc
lib/LaTeXML.pm
lib/LaTeXML/Post/Manifest/Epub.pm
t/931_epub.t

Fixes #827 and #806 
This is a platform-specific fix, and in fact I need to double-check this keeps the epub generation as-is on Linux. 
It turns out that without an explicit `:raw` binmode, printing out binary data on Windows 10 leads to corrupted archives, for reasons I do not fully understand at the moment. 
While debugging, I first verified the archive integrity, all EPUB-needed files were added to the Archive::Zip object and then serialized via IO::String. However, the same payload lead to different `.epub` file contents when e.g. the compression level was changed, leading to the OPS subdirectory completely disappearing when the archive is viewed in 7zip. 
In the end, it turned out the produced archives were partially readable by 7zip (my Win10 archive reader of choice), but were …

Ensure raw binmode when writing archive files in latexmlc

---

lib/LaTeXML/Package/TeX.pool.ltxml
lib/LaTeXML/Package/pgfmath.code.tex.ltxml

Just took a quick look at the Perl-level fatal errors of `1802.08337` in arXiv, and teased them away so that the Fatal comes from having 100+ errors. The document itself has some serious problems with tikz interpretation, so I won't attempt to resolve it to a non-error state now.

Teasing away Perl-level dies for 100+ error document

---

lib/LaTeXML/Package/TeX.pool.ltxml

The specific use in arXiv 1802.01430 was causing a Fatal error:
```
\graphicspath{ {./Figs/} } 
```
as the argument was being misinterpreted. Please check if this fix is the most accurate upgrade, it certainly makes the document work with a decent HTML output.

make DirectoryList tolerant of spaces

---

lib/LaTeXML.pm

This causes cortex-specific troubles, as the return archive is empty, and hence no log information can be gathered. 
This PR ensures if the core processing returns a completely empty document, without any elements set, it will still produce an HTML document and add the log file to the archive, when the target is `.zip`.
The specific arXiv document that hit this was 1802.05735

when core returns an empty document, ensure post still succeeds

---

t/931_epub.t

Addresses the comment about the epub test being a bit too noisy. IPC::Open3 is a core module, so shouldn't need makefile changes, and is the most foolproof way to capture the streams when calling an external command.

using IPC::Open3 to silence the status write of latexmlc during testing

---

lib/LaTeXML.pm
lib/LaTeXML/Common/Error.pm
lib/LaTeXML/Post/MakeBibliography.pm

Fixes #916 
A bit tricky, since managing the STDERR redirects is getting wild, but it works nicely. Unsure about the final log to print, attaching screenshots with this version. I did not want to indent the messages, so that automated regexes (e.g. from cortex) can still parse the log as usual.
Here are the logs converting the the issue example, with `master`:
And the logs after this PR is installed:

Integrate logs from separate bibliography converts in post-processing

---

lib/LaTeXML/Package/LaTeX.pool.ltxml
lib/LaTeXML/Package/TeX.pool.ltxml
lib/LaTeXML/Package/calc.sty.ltxml
lib/LaTeXML/Package/multirow.sty.ltxml
lib/LaTeXML/Package/pstricks.sty.ltxml

I took a pass through one example document, but also went through all line numbers in the 92 Fatal messages reported at:
```
fatal >  misdefined >  LaTeXML::Package::Pool::__ANON__
```
https://corpora.mathweb.org/corpus/%2Fdata%2Farxiv_1802%2F/tex_to_html/fatal/misdefined
and patched them. Just some minor code hardening.

Fix misc fatal:misdefined:ANON problems

---

lib/LaTeXML/Package/TeX.pool.ltxml

While it's hard to fully fix #794 , we can at least keep it from regressing into a Fatal.

avoid Fatal for tikz matrices

---

lib/LaTeXML/Package/LaTeX.pool.ltxml

Fixes #982 
There was a rather nasty infinite loop when loading `ucs.sty` with the `--includestyles` option, which kept allocating new memory.
Turns out using the native definition of `\@protected@testopt` from latex.ltx allows for the package to load completely smoothly and error-free. So I'm submitting this PR to address the original report on the mailing list.
That said, looking at the documentation of ucs:
https://mirrors.sorengard.com/ctan/macros/latex/contrib/ucs/ucs.pdf
I am tempted to add a trivial binding for latexml, that sets the input encoding to utf8. Will wait for feedback from @brucemiller

\@protected@testopt definition from latex.ltx, allows loading ucs.sty

---

MANIFEST
lib/LaTeXML/Package/turing.sty.ltxml
lib/LaTeXML/Package/wiki.sty.ltxml

I am refreshing the [Mojolicious showcase](https://github.com/dginev/LaTeXML-Plugin-ltxmojo) as it has gotten quite dusty - and more importantly, as I am migrating to a new physical machine and will do a fresh setup.
Turns out it was working on a now long-stale branch of LaTeXML, so I am switching it to work with the usual master. Among other things, I noticed two of the bindings I used in the showcase that are actual CTAN packages were not in master yet, but they are both entirely raw interpretation.
So here they are in this PR. Let me know if you'd like them tweaked differently :+1:

wiki.sty and turing.sty bindings

---

release/Dockerfile

This commit adds a Dockerfile to LaTeXML to be able to use latexml easily within a Docker container.

Add Dockerfile for use with Docker

---

MANIFEST
doc/manual/genpods
lib/LaTeXML/Common/Error.pm
lib/LaTeXML/Common/Locator.pm
lib/LaTeXML/Core/Box.pm
lib/LaTeXML/Core/Definition/CharDef.pm
lib/LaTeXML/Core/Definition/Conditional.pm
lib/LaTeXML/Core/Definition/Constructor.pm
lib/LaTeXML/Core/Definition/Expandable.pm
lib/LaTeXML/Core/Definition/Primitive.pm
lib/LaTeXML/Core/Definition/Register.pm
lib/LaTeXML/Core/Document.pm
lib/LaTeXML/Core/Gullet.pm
lib/LaTeXML/Core/KeyVals.pm
lib/LaTeXML/Core/List.pm
lib/LaTeXML/Core/Mouth.pm
lib/LaTeXML/Core/Mouth/Binding.pm
lib/LaTeXML/Core/State.pm
lib/LaTeXML/Core/Stomach.pm
lib/LaTeXML/Core/Whatsit.pm
lib/LaTeXML/MathParser.pm
lib/LaTeXML/Package.pm
lib/LaTeXML/Package/LaTeX.pool.ltxml
lib/LaTeXML/Package/TeX.pool.ltxml
lib/LaTeXML/Pre/BibTeX.pm

This pull request refactors the behaviour of locators. In particular, it turns locators into a new class `LaTeXML::Common::Locator`, that is then only `ToString`ed when displayed to the user. 
The locator class also improves upon the old locators and is internally a quintuple consisting of
* the source filename, or `undef` in case of an anonymous string source, or `''` in case of a literal string source
* the starting line and column numbers of the locator
* the ending line and column numbers of the locator (or `undef` if not applicable)
This means that an instance of a locator class can refer either to a point, or an entire range in the source file. When requesting a Locator from the Mouth, the code tries to estimate the location and length of the last token, thereby returning a range. …

Cleanup and Refactor Locators

---

lib/LaTeXML/Package/enumitem.sty.ltxml

This commit improves the enumitem binding, in that it defines `\newlist` and `\renewlist` to create and update stub environments for the appropriate list types.

Improve enumitem binding

---

lib/LaTeXML/Util/Test.pm

Ideally this helps with CPANTesters, should be just redundant information for a regular Perl installation.
One key question is whether a call to `perl` will use the correct version of Perl on CPANTesters. If this fails, there seem to be alternatives that can be tried without a system call, such as:
```
{
local @ARGV = qw<param1 param2 param3>;
do "$latexmlc";
}
```
but that would need a slightly larger rewrite of the Test.pm setup

pass @INC to latexmlc invocation in tests

---

lib/LaTeXML/Util/Test.pm

Config is a core module, and I got this solution from:
["How should I invoke perl from my test scripts?"](http://wiki.cpantesters.org/wiki/CPANAuthorNotes)
Could help with using the correct Cwd.so, which I see is the next CPANTesters issue. It may also be the case that we shouldn't pass *all* `@INC` paths onto the call, which would be my next step if this PR doesn't suffice.

Also use same perl between Test.pm and system()

---

t/931_epub.t

This one slipped by, the epub test uses a custom invocation since it does not fit the usual daemon setup -- it examines archive files instead of XML.
Essentially the same change in the last PR - using a more careful Perl invocation, to be compatible with CPANTesters. Hopefully the last change needed to pass.

Paranoid perl invocation for epub test

---

.gitignore
.travis.yml
t/81_babel.t
tools/travis/README.md
tools/travis/scripts/build-all.sh
tools/travis/scripts/build-test-image.sh
tools/travis/src/entrypoint.sh
tools/travis/src/installdeps.sh
tools/travis/src/texlive-2015.sh
tools/travis/src/texlive-2016.sh
tools/travis/src/texlive-2018.sh
tools/travis/src/texlive-latest.sh

This commit completly overhauls the way Travis tests are done. Previously, these were used by manually installing appropriate versions of perl and tex into the testing environment and then running a script.
This commit introduces a scheme for building appropriate docker test runtime images. 
This allows for a lot more flexibility and reliable when running tests.
It also makes the tests run faster, as it is no longer neccessary to download, install and configure several dependencies.
These images are then pulled and used by Travis at testing time.

Texlive more tests

---

lib/LaTeXML/Post/CrossRef.pm

Currently we see empty parens in the recent arxiv conversion run, for documents using revtex4-1, and i assume other natbib-based citation styles.  Example:
https://corpora.mathweb.org/preview/arxmliv/tex_to_html/cond-mat0001224?style=simple
Note `KR1 ()` , etc.
The core of the issue is the arxiv setup - there is no `.bib` file to consult for metadata, just the final `.bbl` - in some cases directly embedded into the main document source. So we end up with having only the bib key -- which latexml already falls back to. I localized the code path to this fallback in natbib.sty.ltxml:
```
Invocation(T_CS('\@@cite'),
Tokens(Explode('cite')),
Invocation(T_CS('\@@bibref'),
Tokens(Explode("Authors Phrase1YearPhrase2")),
$keys,
Invocation(T_CS('\@@citephrase'), $open), …
```

Guard against empty parens in citations with missing metadata (natbib-style)

---

lib/LaTeXML/Util/Pack.pm

Michael pointed me to a weird looking arXiv paper:
https://corpora.mathweb.org/preview/arxiv_1802/tex_to_html/1802.00029
And indeed it is currently pointing to the documentation of a cls file at `ieeeconf/root.tex` instead of the actual paper source `main.tex`.
It turned out the heuristic for guessing the main TeX source was a bit simplistic in cases where it found two equally likely latex sources (as these are, both have \documentclass declarations and are self-contained documents). So I added a tie-breaking rule in this PR, which prioritizes the file closer to the root of the zip archive.
Attaching a test ZIP for demonstration, as simple as:
```
latexmlc paper.zip --dest=paper.html
```
[paper.zip](https://github.com/brucemiller/LaTeXML/files/2589513/paper.zip)

Prioritize sources closer to root of archive in ZIP input

---

lib/LaTeXML/Package.pm

Simple upgrade to solve the scenario described in https://github.com/arxiv-vanity/engrafo/issues/270
In essence, when loading a `.cls` file as raw TeX, also define a baseline CSS, similarly to the OmniBus.cls.ltxml approach.

Baseline styling for raw .cls loads

---

lib/LaTeXML/Core/Mouth.pm

* standardized variable names to Tom's from/to pairs, which are more readable
* removed the rather bizarre column arithmetic in the locator heuristic
* replaced with a simple "zero or here" rule
More work can be done, but this provides slightly more meaningful locator ranges for the stex tests.

More careful location range heuristic

---

MANIFEST
lib/LaTeXML/Package/quantumarticle.cls.ltxml
lib/LaTeXML/resources/XSLT/LaTeXML-structure-xhtml.xsl

https://quantum-journal.org/instructions/authors/
https://github.com/quantum-journal/quantum-journal
I think this is everything needed from the .cls file. I have tested with the template and a real paper from the journal and both render without errors.
I wanted to include the template as a test, but I don't think I can because it is licensed under LPPL. Is that right? I don't think I can even write my own test because the .cls file is not in texlive, so I'd have to commit it to the repo to get the PDF to render.
ref https://github.com/arxiv-vanity/engrafo/issues/316

Add support for quantumarticle.cls

---

bin/latexmlmath

Fixes #1111 
I simply copied the inputencoding handling from the `latexml` executable, and reformatted with `latexmllint`.

Add --inputencoding to latexmlmath

---

MANIFEST
MANIFEST.SKIP
t/97_manifest.t
tools/pre-commit

Example effect, when adding a new binding and forgetting to update the MANIFEST:
```
Some files are missing from MANIFEST, please add them: 
lib/LaTeXML/Package/new.sty.ltxml;
COMMIT ABORTED
```
Hopefully can make the @brucemiller 's reviewer life a little more pleasant!

Add pre-commit check for MANIFEST membership

---

MANIFEST.SKIP

A few quick rules that get the most recent daemon tests to pass without complaints -- the failures only become visible if you run `make test` on a multi-threaded setup.
I run 32 tests in parallel so a lot of the temporary files are visible when the manifest check is run.

more rules for SKIP

---

lib/LaTeXML/Core/State.pm
lib/LaTeXML/Package/TeX.pool.ltxml

This PR gets latexml to "survive" Chapter 1 of the TeXbook, somewhat on a whim.
It makes good headway down the content as well, but there seems to be some deep issues with plain TeX alignments as one jumps into absorbing chapter 2. I may wait until the alignment refresh lands in the latexml master before I look into that.
For chapter 1, two simple fixes:
- add the `\dospecials` macro, as described in the TeXbook, to TeX.pool. We already reference in some of the bindings (verbatim.sty.ltxml) and had a version of it defined in LaTeX.pool
- add an active catcode for the form-feed character, which appears often in the TeXbook sources, as well as its TeX.pool definition via `^^L` (as per the plain.tex format, p. 343).
- Perltidy demanded to lint the files I touched, so there are also some …

\dospecials and form-feed

---

lib/LaTeXML/Common/Config.pm
lib/LaTeXML/Core.pm
lib/LaTeXML/Core/Mouth.pm

Foundation for #1116 
A big part of the fragility and double-encoding in the various unicode tests one can try with the executables comes from there being *no* default input encoding in play. That implies that latexml treats any input as a perl byte string and an author of a TeX document unfamiliar with Perl finds the behavior hard to predict.
From a usability standpoint, it seems more direct that when we say "latexml is unicode native" we also imply a default input encoding of UTF-8. This PR changes that, and all tests continue to pass without need for extra intervention (luckily the ascii origins are invariant to unicode decoding).
I also have ensured that string mouths also use the inputencoding logic, as so far we only employed it for file mouths.
This PR can be followed up with my …

Default inputencoding (utf-8)

---

.appveyor.yml
Makefile.PL
README.pod
lib/LaTeXML/Package.pm
lib/LaTeXML/Util/Pathname.pm
lib/LaTeXML/Util/Test.pm
t/81_babel.t
t/daemon/formats/citation.test.status

This was simpler than I thought. I copied the first [example appveyor build](http://blogs.perl.org/users/mauke/2017/10/automated-testing-on-windows-with-appveyor.html) online, and enabled appveyor on my fork, resulting in a working build:
https://ci.appveyor.com/project/dginev/latexml-hu4m2
I also added a nice visual badge to the README as an example. This only runs CI on a Windows installation without a MikTeX present, I am eagerly awaiting an opportunity to borrow the install steps for free from the [chocolatey-latexml](https://github.com/metanorma/chocolatey-latexml) bundle that inspired pushing this PR out today.

Continuous Integration for Windows

---

.travis.yml
t/97_manifest.t
tools/pre-commit

Main need for the manifest test is so that Travis/Appveyor informs us about any inconsistent pull requests. For main developer flow, we have a pre-commit hook which suffices.
Here are two example runs with this changeset:
```
$ make test
PERL_DL_NONLAZY=1 "/usr/bin/perl" "-MExtUtils::Command::MM" "-MTest::Harness" "-e" "undef *Test::Harness::Switches; test_harness(0, 'blib/lib', 'blib/arch')" t/*.t
t/97_manifest.t ........ skipped: Only checked in continuous integration.
$ CI=true make test
PERL_DL_NONLAZY=1 "/usr/bin/perl" "-MExtUtils::Command::MM" "-MTest::Harness" "-e" "undef *Test::Harness::Switches; test_harness(0, 'blib/lib', 'blib/arch')" t/*.t
t/97_manifest.t ........ ok                                             
```

Only run manifest test in CI

---

MANIFEST
lib/LaTeXML.pm
t/daemon/formats/lexmath.spec
t/daemon/formats/lexmath.status
t/daemon/formats/lexmath.xml
t/daemon/lexmath.tex

PR is ready for review and merge.
I found a pretty good example in a DL textbook I am reading for a semantic difference for a bold-x (a vector-valued random variable) and a bold-italic-x -- one of the individual values of bold-x.
So I decided to turn that into a test, also so that we exercise the option and avoid regressions.
That led me back into one of my most frustrating bits of programming, at the end of the convert call in LaTeXML.pm, where serializing into a UTF-8 marked string becomes an outright ordeal. I reread `XML::LibXML` carefully, and left detailed notes on my updated understanding of the circumstances. I think the code is now extra-robust, but I really dislike the design of the serialization in `XML::LibXML`. Not only are the defaults inconsistent between classes (Document …

Add math lexeme test

---

lib/LaTeXML/resources/CSS/LaTeXML-navbar-left.css
lib/LaTeXML/resources/CSS/LaTeXML-navbar-right.css

If the table of contents as left/right navigation pane was too long we found it was impossible to reach all sections. The attachment contains the test-file and the commands.
The pull-request fixes this by adding auto-scrolling for the navigation panes in the css-files. The automatic part means that it is only active for large table-of-contents; so it should be unproblematic for other cases.
[Test.zip](https://github.com/brucemiller/LaTeXML/files/2904894/Test.zip)

Auto Scrolling Table-Of-Contents for navigation

---

tools/maketests

I was advertising the `tools/maketest` utility script today [here](https://github.com/MathWebSearch/LaTeXML-Plugin-MathWebSearch/pull/7) and realized it is missing a piece of default logic that makes it useful with the simplest invocation.
Just matching the `doxml` default logic in the regular testing path actually.
So that:
```
perl tools/maketests t/daemon/profiles/fragment.spec
```
automatically creates the .xml file when it is missing or stale.

Freshen up: tools/maketest for spec tests

---

lib/LaTeXML/Package.pm

So it turns out TeX can get away with doing nasty hacks related to "namespacing" stepped counters, while latexml can't, mostly due to the requirement for xml:ids to be NCNames.
I traced down an example of this class of issues from the arXiv reports, a good paper being: https://arxiv.org/abs/1103.4198
which was dying with a Fatal when cross-referencing an equation, as its id was not valid for the XML parser. This is otherwise a very well-converting warning-level (math parsing) document, which really shouldn't have to suffer a Fatal.
The offending line of TeX that lead to all the drama was:
```tex
%                TO NUMBER EQUATIONS BY SECTION
%
\makeatletter \@addtoreset{equation}{chapter} \makeatother
```
Which, when used in this `\documentclass{article}` document, implied the leading …

Robust NCNames in LaTeX counter-based xml:ids

---

tools/symbolscan

While I was fishing for `texscan` runs, I ran a `symbolscan` run just out of curiosity and realized that script hasn't been updated to the latest LaTeXML API.
I did the minimal amount of changes to make it runnable on my machine (including using kpsewhich to find the unicode data file, which for me is only available in the texlive installation).

symbolscan maintenance refresh

---

lib/LaTeXML/MathParser.pm
t/daemon/formats/lexmath.spec
t/daemon/formats/lexmath.xml
t/daemon/lexmath.tex

Two advanced cases that kept staring at me when exploring the GloVe model trained over arXiv were formula lexeme cases for arrays and `\text`-like atoms.
I have attempted to improve the logic to compositionally enter and serialize those constructs, which worked quite nicely on two examples I've added as tests:
1. Arrays
- Formula:
```tex
\[ \begin{array}{cc} a+1 & b-2 \\ c+3 & d-4 \end{array} \]
```
- current lexeme (single word):
```
ARRAY:italic-a+1b-2c+3d-4
```
- improved lexemes (26 words):
```
ARRAY:start 
ROW:start CELL:start 
italic-a ADDOP:plus NUMBER:1 
CELL:end CELL:start
italic-b ADDOP:minus NUMBER:2 
CELL:end ROW:end
ROW:start CELL:start
italic-c ADDOP:plus NUMBER:3 
CELL:end CELL:start
italic-d ADDOP:minus NUMBER:4 
CELL:end ROW:end 
ARRAY:end
```
---
2. \text-like ATOMs
- …

Improve lexemes for arrays and internal text of formulas

---

lib/LaTeXML/Package/LaTeX.pool.ltxml

This was a satisfying fix, as it may be responsible for a range of hard-to-trace Fatal errors in arXiv. It may also be a very rare error, as it is a subtle edge case in splitting out the package options, combined with advanced option logic for revtex4.
A rather innocent looking minimal tex snippet is:
```tex
\documentclass[twocolumn,superscriptaddress,showpacs,preprintnumbers,amsmath
,amssymb,aps,prd]{revtex4}
minimal
\end{document}
```
As it turns out, the master branch of latexml splits by `,\s*`, hence obtaining the `amsmath\n` name and failing to load amsmath, which it kindly told me via:
```
Info:unexpected:options Unused global options: amsmath
at paper.tex; line 62 col 0 - line 62 col 16
```
In the example I was looking at, that in turn was followed by an error: …

Allow pre-comma spaces in package option lists

---

lib/LaTeXML/Core/Gullet.pm
lib/LaTeXML/Package/LaTeX.pool.ltxml

I was checking the too_many_fatals page, as it has been a long while since I looked at it, and the first entry already showed two patch opportunities that upgraded the task to a usable "error" status:
https://corpora.mathweb.org/corpus/arxiv_testbench/tex_to_html/fatal/too_many_errors/100?all=false
1. `\fmtversion` is apparently parsed at times, so it should really contain a real date to make the parse succeed. I used the date in my local `latex.ltx` file.
2. Curiously, when a `mouthstack` is empty during Gullet's `readingFromMouth`, it currently loops indefinitely, firing an error on each step and hence always Fatal-ing with "100 errors reached". So I just added a `last;` escape hatch, which lets the conversion continue and recovers at least part of the document. In the document I am …

\fmtversion and empty mouthstack fallback

---

lib/LaTeXML/Package/aastex.cls.ltxml

Another quick fix turning a Fatal into a warning (100 alignment errors again). Example was:
```tex
\documentclass[iop,revtex4]{emulateapj}
```
which (in pdflatex) lead to loading revtex4.cls , then longtable.sty, which defined `{longtable*}` which is where the 100 alignment errors were being triggered. Simply adding the loading behavior to the binding allowed for an error-free conversion run with a beautiful output, quite neat.

revtex4 option of emulateapj and aastex should load the binding

---

lib/LaTeXML/Package.pm
lib/LaTeXML/Package/TeX.pool.ltxml

It looks like `scriptHandler` was erroneously dropping empty `{}` groups that acted as script anchors, leading to a wrong message:
```
Error:unexpected:double-superscript Double superscript
```
for an otherwise reasonable formula: 
```tex
$\xi'{}_i^j$
```
This PR adds a minor patch keeping the `{}` for the grammar to try and parse on the "scripted decorated symbol". The grammar fails with a warning (cool extension opportunity!), but the document is upgraded to a "warning" status from the previous "error" status. Test was `0906.1692`.
I was originally interested in that file to check why the `U` fontmap wasn't being found, and added a couple of undef checks to make perl happy on the route to that, but that requires more infrastructure to improve on.

keep empty groups as script anchors during scriptHandler

---

lib/LaTeXML/Package/pgfkeys.code.tex.ltxml

Fixes #1143 .
A bit iffy of a fix, but the only "holistic" patch would be to go back to reading the raw tex from the style file. Thanks to @brucemiller  for debugging and binding help.
As always, may need another review, but I can verify that this binding successfully converts the [Tikz Basic](https://latexml.mathweb.org/editor?demo=tikz-basic) example from the showcase, both on a 2018 texlive machine, and on a 2015 texlive machine - I just tested both.
Feedback welcome!

Version-aware behavior of pgf macro, different in texlive 2018

---

lib/LaTeXML/Package.pm
lib/LaTeXML/Package/LaTeX.pool.ltxml
lib/LaTeXML/Package/latexml.sty.ltxml
lib/LaTeXML/Post/MakeBibliography.pm

Currently we search the entirety of `kpsewhich` for .bib paths. While that may sound perfectly legal for an ordinary document, it is not "careful enough" for the arXiv conversion.
In particular, I have an example document which depends on a `biblio.bib`, but in reality using `paper.bbl` for its arXiv compilation. The paper does not even include the .bib file in the bundle. However, in this case latexml finds a biblio.bib if you have a texlive installation, in particular:
```
$ kpsewhich biblio.bib
/usr/share/texlive/texmf-dist/bibtex/bib/msc/biblio.bib
```
Which leads to a couple of macro errors, as that bibliography contains macros. This PR is based on my claim that looking for `.bib` files inside the texlive installation should never be latexml's intent. Instead, we may want to look …

Localized search for `.bib` paths

---

lib/LaTeXML/Package/float.sty.ltxml

Theoretically smallest PR possible - just 1 character.
This is simply adding the perfectly diagnozed and patched fix at #1161 , I have reproduced the correct behaviour and can confirm the `#2` looks like an argument number typo. Full credit to @evoludolab for diagnosing and reporting this.

argument number oversight in \format@title@

---

lib/LaTeXML/Post/Manifest/Epub.pm

Cpantesters failed for cygwin with the epub test failing to find the CSS assets.
Reading around, I'm suspecting absolute paths don't agree in that setup, as discussed here:
https://www.cs.unc.edu/~jeffay/dirt/FAQ/cygwin-perl.html
As it turns out, the `-f` check was just "extra safety" but wasn't necessary due to the following asset name checks. So, hoping this was indeed the underlying issue, submitting this patch which simply omits the `-f` check for epub asset packing.

Make epub work under cygwin

---

release/Dockerfile

This PR updates the Dockerfile to use Alpine Linux 3.10 and removes newly redundant code in the Dockerfile.

Update Dockerfile to use alpine 3.10

---

.travis.yml
tools/travis/README.md
tools/travis/scripts/build-all.sh

The tests for perl 5.12 were removed in https://github.com/brucemiller/LaTeXML/commit/4217f4c862062c53bbc17293d11774ffa65c0f4e. In https://github.com/brucemiller/LaTeXML/pull/1169#issuecomment-509509520 @brucemiller suggested adding tests for perl 5.14. 
This PR adds tests for version 5.14.4. For this purpose I added a new Docker Image. An example test run can be found at https://travis-ci.org/brucemiller/LaTeXML/jobs/556303915.

Add Perl 5.14 Tests

---

MANIFEST
lib/LaTeXML/Package/neurips.sty.ltxml
lib/LaTeXML/Post.pm
lib/LaTeXML/Post/MakeBibliography.pm

Starting to take the "make sure your own arXiv submissions convert well!" mantra seriously.
This PR adds a simple binding for a base `neurips.sty` package, which has several variations in use in arXiv (the one I used is `neurips_2019.sty`).
More interestingly, I used `\url` consistently in my bibtex entries this time, so preloading the right macros was crucial to get the right output. Luckily the code was already there it was just being shy(?) and only letting inputenc through. I now made it possible to preload the full dependency tree, which gets a full "no problem" post-processing on my article!
I don't think this PR will have significant impact on arXiv, but it does get my paper error-free and looking good!

neurips binding and reliable preloads for bib conversion

---

lib/LaTeXML/Package/hyperref.sty.ltxml
lib/LaTeXML/Package/url.sty.ltxml

Fixes #1172 
Bug is fixed by simply consistently using the Gullet API from all binding levels. `\url` was being too low-level and was working directly on a Mouth object, not accounting for contexts in which tokens were already added to the Gullet's `{pushback}` stack, such as the `XUntil` parameter type read for `\institute`.
The PR produces the desired behaviour in the issue example.

avoid Mouth time-travel when preparing url from an XUntil context

---

lib/LaTeXML/Package/amsmath.sty.ltxml

I stumbled onto a note by @lab156 that a given arXiv document [did not finish at all](https://github.com/lab156/arxivDownload#problems) under LaTeXML. I checked in CorTeX, and it had my most hated type of fatal - [a memory leak](https://corpora.mathweb.org/preview/arxmliv/tex_to_html/1411.6225).
Inspecting the document, a near-minimal example reproducing the leak is:
```tex
\usepackage{amssymb,amsfonts,amsmath,amsthm,amscd}
\newcommand{\la}{\lambda}
\newcommand{\ph}{\varphi}
\makeatletter
\newenvironment{casks}{%
\matrix@check\casks\env@casks
}{%
\endarray\right.%
}
\def\env@casks{%
\let\@ifnextchar\new@ifnextchar
\left\lbrack
\def\arraystretch{1.2}%
\array{@{}l@{\quad}l@{}}%
}
\makeatother
\begin{equation*}
\begin{casks}
r\in\{3,4,5,6\},& …
```

add a stub for \matrix@check, avoiding memory leak fatals

---

lib/LaTeXML/Package/icml_support.sty.ltxml

All icml style files I've tested (2013-2019) require `algorithmic` package, but `algorithmicx` doesn’t define any `algorithmic` commands. [Here's](https://arxiv.org/pdf/1402.5766v1.pdf) an example of paper (using icml2014.sty) on which LaTeXML hangs during processing when `algorithmicx` is used.

Use algorithmic instead of algorithmicx in icml*.sty

---

lib/LaTeXML/Common/Error.pm

This PR may be more about the discussion than the change. I was inspecting an interesting selection of out-of-memory/timeout examples from the arXiv run, and noticed a few cases with a "deep recursion", which later lead to errors and uncontrollable behaviour.
Now that we have a "recursion error" category, I am wondering if we may also want to continue down that path and get a "recursion fatal" category, for cases where it isn't clear how to escape back into the main document processing. A perl deep recursion is such a case - it should almost never occur naturally, and most of the times it is seen it leads to uncontrollable errors following. I recall there are occasional exceptions, where a binding could trigger a deep recursion and remain functional, but it's usually a sign that it can be …

[Suggestion] elevate perl's deep recursion to Fatal level

---

lib/LaTeXML/MathParser.pm

I spotted some cosmetic bugs in reporting the unknown tokens in math parsing, when the math lexeme serialization is turned on. It did not affect any of the processing or output, just the (info-level) messages printed out - an unintended side-effect from reusing the `getGrammaticalRole` method.
Example in master:
```
latexmlc --whatsin=math --preload=llamapun.sty 'literal:\sqrt{x}'
```
with PR:

Silence side-effect warnings for math lexemes (otherwise harmless)

---

lib/LaTeXML/Post/MakeBibliography.pm
lib/LaTeXML/Pre/BibTeX.pm

Fixes #980 , but begrudgingly so.
We don't really have a clean API for passing a collection of documents for conversion (so that they reuse the same state), and there is no `\input` opportunity when we are in BibTeX mode. Which leaves me with the sole option of detecting a multi-`.bib` setup in post-processing, and concatenating the content of all of those files together, in order to have a `@preamble` from one bib file visible to all following.
This actually gets Michael's example working smoothly, but makes it annoying to debug cases where you've used several bib files and one of them encounters an error -- since the error message you'll get will be about a literal string that has nothing to do with the original files, even the line numbers are different.
In any case, I'm offering it as …

Unified conversion for multi-bib collections

---

lib/LaTeXML/Common/Config.pm

It turns out [the web manual](https://dlmf.nist.gov/LaTeXML/manual/commonmodules/LaTeXML_Common_Config.html) has a misleading example for using latexmlc from the Config.pm perldoc. Fixing here, and would also suggest regenerating the officially hosted manual when there is some available time. Tripped up @tkw1536 today (sorry).

Correct latexmlc example

---

lib/LaTeXML/Core/Document.pm

This is another one of those "too many moving parts" debugging streams, as sTeX usually is.
I localized a snippet that experienced a deep recursion on `Document::finalize_rec` when serializing, see `deep_rec.xml` at:
https://gist.github.com/dginev/4a1eaa48ca26b662a0f217da288642ad
It turned out it was looping on a trivial `ltx:text` element containing `foo`, as the `%pending_declarations` were never emptied. They contained a very artificial `{ element => {} }`, and thus the recursive call kept happening, until it bottomed out.
I am not really certain as to why/how sTeX got itself into that position, but here is a trace of what finalize_rec was seeing as arguments when it went into the loop:
```xml
finalize_rec on :
<omdoc:rendering _box="LaTeXML::Core::Whatsit=HASH(0x55bb206a2290)" …
```

Patch finalize_rec for stex ltx:text elements

---

release/docker/Dockerfile
release/docker/hooks/build

I've re-read the DockerHub documentation and figured out that it does support [custom build hooks](https://docs.docker.com/docker-hub/builds/advanced/). As such, I have to revise https://github.com/brucemiller/LaTeXML/issues/1178#issuecomment-517242737. With this PR I would like to merge a branch that has auto-builds (i.e. docker image build on every push) enabled. The generated images can be found at  [tkw01536/latexml](https://hub.docker.com/r/tkw01536/latexml/builds). 
To speed up the build process I made the following two optimizations:
- do not include TeXLive (i.e. `--build-arg WITH_TEXLIVE=no`)
- do not run perl tests during the build (i.e. installing with `cpanm --notest .`)
With these optimizations, building seems to take between 10-20 minutes for each commit.
Please note that …

Add support for DockerHub auto-builds (fixes #1178)

---

bin/latexml
bin/latexmlfind
bin/latexmlmath
bin/latexmlpost
lib/LaTeXML/Common/Config.pm

Fixes #1208 
Simple enough, just exit with 0 for `--help` and `--VERSION`.

exitval 0 for intended quick invocations such as --help and --VERSION

---

lib/LaTeXML/Util/Test.pm

When using the `latexml_tests` method to create test cases, LaTeXML is instantiated using `LaTeXML::Core->new` with appropriate default options.
This works fine for tests by LaTeXML itself, however it prevents the function from being used in test cases for custom plugins (as none of the profiles, bindings, etc.) can be loaded.
This PR adds a new option `core_options` to `latexml_tests`. When provided, this should be a hash of options passed to `LaTeXML::Core->new`. This allows plugin authors to customize the options used to instantiate LaTeXML for each test case.

Enable custom LaTeXML::Core options in 'latexml_tests'

---

lib/LaTeXML/Package/LaTeX.pool.ltxml

Part of #1214 .
This PR makes the following TeX snippet produce identical output with pdflatex and latexml:
```tex
\makeatletter
\edef\versioned{\@ifl@t@r\fmtversion{2019/10/01}{earlier}{later}}
\versioned
\end{document}
```
The code is transferred over from a texlive 2019 latex.ltx.

add \@ifl@t@r helper to LaTeX.pool

---

lib/LaTeXML/Package/xcolor.sty.ltxml

All tikz-related examples on texlive 2019 currently lead to an Error status under the latexml master, as the latest pgf kernel also invokes `\XC@tgt@mod` from xcolor.sty, which is not yet added to that binding.
I've added the basic version of the macro, which gets my basic showcase Tikz examples working. There is a separate regression to address with #1227 , which is unrelated to this basic fix.

Add missing xcolor primitive for basic Tikz load in texlive 2019

---

lib/LaTeXML/Common/XML/Parser.pm
lib/LaTeXML/Util/ObjectDB/Entry.pm

Simplify storage of XML in ObjectDB to only be single nodes (not DocumentFragment); this avoids the buggy parse_xml_chunk method of XML::LibXML which fails (sometimes) to bind the xml prefix to the namespace

Simplify storage of XML in ObjectDB to only be single nodes

---

lib/LaTeXML/Core/Box.pm
lib/LaTeXML/Core/List.pm
lib/LaTeXML/Package.pm
lib/LaTeXML/Package/etoolbox.sty.ltxml

The only purpose of this PR is to "plug" needless Fatals, and allow the processing to proceed further. I tested ~10 papers from the latest arXiv run, and ~5 of them switched to Error status, the others switching to `100 error` Fatals. 
I claim both are better outcomes, as the `Perl:die` fatal category is rather opaque to comb through, and we might as well gain some robustness for odd cases.
Changes:
- Adding stubs for Number/Pair methods to Box, so that cases where the arguments are misinterpreted can fail more gracefully. No need to Fatal a document because a List snuck into the number arithmetic. Though of course no sensible content will come out for that particular piece of the document.
- Be a little more careful with unblessed refs sneaking into `AddToMacro`, which is something I've …

Fatal-avoiding patches for a handful of arXiv cases

---

lib/LaTeXML/Package.pm
lib/LaTeXML/Post/MakeBibliography.pm

Today @stamer alerted me by email about another weakness in our attempt to faithfully convert bibliographies in the MakeBibliography post-processor.
Namely, he had an example which interpreted `some.cls` raw via `--includestyles` in the main processing, which then failed miserably when its `some.bib` file was being converted in post-processing. The failure is easy to explain - `--includestyles` is never made visible to the post-processor, so the search for the `.cls.ltxml` file fails and the entire conversion of the bib file surrenders.
Now, I had a very happy thought while understanding the error trace. During post-processing, all packages and classes that have been copied over from the Core processing have essentially been "vetted". Namely, if the core conversion managed to "succeed" …

Allow for raw definitions in bibliography post-processing

---

.travis.yml

Previously, when running Travis Tests, the Docker Images determined which commands (like 'make test' and friends) were run during the build.
This PR changes the behavior, and instead moves the commands to be run into `.travis.yml`. This will allow customizing travis behavior in the future (to e.g. run 'make fulltest' instead of 'make  test') without needing to rebuild the Docker Images.

Move Travis Test Commands into .travis.yml

---

lib/LaTeXML/Package/dcolumn.sty.ltxml

An Error-level patch for the latest arXiv run. I was looking at the `Error:malformed:XMApp` category:
https://corpora.mathweb.org/corpus/arxmliv/tex%5Fto%5Fhtml/error/malformed/ltx%3AXMApp?all=false
In particular, `cond-mat0001181`. The problem is that the authors treated the `d` column, which has an intent for numeric literal content, as "advisory" rather than "mandatory". In particular, this gorgeous table (PDF):
was typeset using a d-column with content:
```tex
($ 1 0 \frac{1}{2} $) 
```
Note that the parentheses are in text mode, while the fraction + other numeric literals are in math mode. This was breaking the current support in dcolumn.sty.ltxml.
I found a satisfying upgrade that seems to follow closer the "intent" of d-columns. Namely, I deactivated `T_MATH` (as `\relax`) for the …

Handle dual-mode content for {d} coulmns in dcolumn.sty

---

lib/LaTeXML/Package/LaTeX.pool.ltxml

Motivated by [this arxiv paper](https://arxiv.org/abs/cond-mat/0003484), while looking for what turned out to be an incidental [ltx:XMTok in ltx:p](https://corpora.mathweb.org/corpus/arxmliv/tex%5Fto%5Fhtml/error/malformed/ltx%3AXMTok?all=false) malformed error.
The main issue with the document is an old use of `\documentstyle` that really targets a `.sty` file, and one that is distributed together with the paper sources - a custom `jpsj.sty`.
I added a check for a finding `.cls` file, which when OK proceeds, but when failed tries to load a `.sty` file of the same name, with a preloaded OmniBus.cls. It improved the status of the document substantially (even threw in a `\@options` helper definition for it, but since alignments were involved it still failed flat after a certain point. I …

\documentstyle for .sty targets

---

lib/LaTeXML/Package/BibTeX.pool.ltxml
lib/LaTeXML/Package/LaTeX.pool.ltxml
lib/LaTeXML/Package/OmniBus.cls.ltxml
lib/LaTeXML/Package/amsrefs.sty.ltxml
lib/LaTeXML/Package/revtex4_support.sty.ltxml

Update users of beginBibliography to call beforeDigestBibliography when actually digesting bibitems so appropriate switches get set.  Particularly offensive was potential uses of ```\if@lx@inbibliography```.

Update users of beginBibliography

---

lib/LaTeXML/Package/LaTeX.pool.ltxml

This is a minimal/piecemeal PR, motivated from an arXiv article (hep-lat0006026) that had Fataled with  >100 errors, but which passes with a single error (undefined `\@cite`) when local .sty files are loaded.
It's piecemeal because the PR doesn't actually provide working TeX-level cite support, it just emulates the macro to the point of depositing placeholders akin to `[?,?]` -- still better than an error, and neat to see a Fatal-to-Warning transition.
We may or may not consider locking certain "core" macros in LaTeX.pool (such as `\cite`) when also interpreting local .sty files...

add \@cite macro from latex.ltx

---

lib/LaTeXML/Core.pm
lib/LaTeXML/Package.pm
lib/LaTeXML/Package/LaTeX.pool.ltxml
lib/LaTeXML/Package/latexml.sty.ltxml

A proposal pull request for the arXiv conversion, motivated by the hope that the recent timeout-resolving PRs buy us more time to do raw interpretation.
A wide range of arXiv articles contain custom `.sty` and at times `.cls` files, which are often easy for latexml to interpret. Until now we have ignored them, under the rightful fear that `--includestyles` will interpret texlive packages that latexml fails badly on, leading to otherwise avoidable Fatals and Errors. We've talked on a number of occasions that it would be informative to do an experiment that only loads raw files from the source directory of a conversion job, which should bring in more positives than negatives (in theory).
So, this PR offers one approach to start such an experiment, via a new experimental latexml.sty option. …

Restricted inclusion of raw styles to source directory

---

lib/LaTeXML/Package.pm

From the latest and greatest GenerateID speedups ( #1248 ) we have a regression, in some torture cases of documents with actual Errors.
You can explore the full list from the testbench here:
https://corpora.mathweb.org/corpus/arxiv%5Ftestbench/tex%5Fto%5Fhtml/fatal/perl/die?all=false
The one I tested with was `0704.2285`. The problem is that some `xml:id`s with the new mechanism get generated with a leading digit, and are hence no longer NCNames, breaking post-processing with a Fatal. You could find a better patch than mine, but it's probably workable just as well -- the `$prefix` setting and passing machinery has gotten a bit convoluted / hard to track. I think in certain cases it is possible to end up with the pregenerated numerical id while no prefix is set.

[regression] guard xml:id NCName for leading digit

---

lib/LaTeXML/Package/TeX.pool.ltxml

an arXiv fatal (`alg-geom9503004`) caused by an attempted macro improvement:
```tex
% intelligent \"; one can type	\"iiii instead of \"\i iii
%
\def\"#1{{\accent"7F \if#1i\i\else#1\fi}}
```
Looks easy enough to avoid with a small upgrade - `Expanded` letter argument for `\accent` fixes the specific issue. And I added a lenient fallback to `T_CS('\@empty')` when a token argument for a conditional is missing, so that the follow-up checks can go through without a perl die. Also shooting off an error in those cases.

Dont fatal when ExpandedIfToken is missing; expanded \accent arg

---

lib/LaTeXML/Common/Object.pm
lib/LaTeXML/Core/Box.pm

A follow-up to my great line of "robustness at all cost" reasoning that we explored in #1241 .
It turns out in the arXiv Fatals we also see cases of `getX`, `ptValue` or `valueOf` getting called on `Token` and `Tokens` objects, not just boxes. Luckily, there is a common thread -- all of these inherit from `Common::Object`!
Hence, this PR elevates the "fallback interface" up to Object, and I'm also throwing in `valueOf` which I noticed breaking one doc. Clawing my way to less Fatals, one fix at a time...

Elevate fallback interface to all LaTeXML::Common::Object

---

lib/LaTeXML/Package/pgfmath.code.tex.ltxml

Continuing my work on the line between a Fatal and an Error document, here is a PR that carefully avoids dividing by zero in pgfmath -- which happens at times in Error-level arXiv documents, instead using a pragmatic epsilon for such cases.
Will likely produce deeply broken output, but if you have one broken figure in a large document, you still get the rest of the document out.

avoid dividing by zero in pgfmath

---

lib/LaTeXML/Package/etoolbox.sty.ltxml

Paying for my own carelessness the previous time I improved the `\patchcmd` binding -- the tex example I looked at now matched on `\left(` , where the parenthesis remained unescaped, leading to a Fatal regex error.
I finally reached for the "official" way to escape all active regex characters in a string, and switched to using `quotemeta`. Improved the Fatal article in question `1604.01056` to warning status.
Fatal read:
```
Perl died at IS_FB_Capacity_MC_May_2015_FINAL_Part_2_V12.tex; line 53 col 0 - line 53 col 45 
Unmatched ( in regex; marked by <-- HERE in m/\\left( <-- HERE / 
at /home/deginev/perl5/lib/perl5/LaTeXML/Package/etoolbox.sty.ltxml line 1302, <$IN> line 53. 
In Core::Definition::Expandable[\patchcm... /home/deginev/perl5/lib/perl5/LaTeXML/Package/etoolbox.sty.ltxml; line …
```

Ensure we always match patchcmd patterns as literal chars

---

lib/LaTeXML/Package/algorithmic.sty.ltxml
lib/LaTeXML/Package/algorithmicx.sty.ltxml
lib/LaTeXML/Package/icml_support.sty.ltxml

A curve ball infinite loop from arXiv, a minimal snippet is:
```tex
\usepackage{icml2020}
\usepackage{algorithm}
\usepackage[noend]{algpseudocode}
\begin{algorithmic}[1]
\end{algorithmic}
\end{document}
```
The issue is that icml_support will load algorithmic, while algpseudocode will load algorithmicx. At time of writing, having both of algorithmic and algorithmicx loaded will lead to an infinite loop at `\begin{algorithmic}`, universally, which is the larger issue.
I took two measures, slightly redundant (which is good - extra safe!).
1. Have `icml` load algorithmic only if no package has defined `\algorithmic` by the time of reaching `\begin{document}`, using the hooks. It is the correct application logic upgrade for the specific arXiv paper, …

icml_support: load algorithmic only when needed

---

MANIFEST
lib/LaTeXML/Common/Object.pm
lib/LaTeXML/Core.pm
lib/LaTeXML/Core/Gullet.pm
lib/LaTeXML/Core/Parameter.pm
lib/LaTeXML/Core/Stomach.pm
lib/LaTeXML/Package/pgfkeys.code.tex.ltxml
lib/LaTeXML/Package/pgfmath.code.tex.ltxml
lib/LaTeXML/Package/pgfmathcalc.code.tex.ltxml
lib/LaTeXML/Package/pgfutil-common.tex.ltxml
lib/LaTeXML/Package/xcolor.sty.ltxml

Another mini-project motivated by arXiv conversion Fatal:timeouts. The minimal snippet was:
```tex
% source: arXiv 1002.3757
\usepackage{tikz}
\newcommand\dw[2]{\draw[#1!#2,fill=#1!#2]}
\begin{tikzpicture}
\def\LL{10}
\pgfmathsetmacro{\LLQ}{200/(\LL*\LL)}
\def\list{0,.2,...,\LL}
\foreach \x in \list {
\foreach \y in \list {
\pgfmathsetmacro{\d}{(\LLQ*(\LL*(\x + \y) - \x*\x - \y*\y))}
\dw{black}{\d} (\x, \y) +(-.1, -.1) rectangle ++(.1, .1);
}   
}
\end{tikzpicture}
\end{document}
```
In order to keep things fast I developed my speedups with `\def\LL{2}`. The times in question are on my x230 thinkpad laptop, so a little slower than usual:
| LL | converter | time sec |
|----:|----------:|-----------:|
| 2   | master | 95 |
| 10 | master | 1860|
| 2 …

PGF processing on a tighter compute budget

---

lib/LaTeXML/Core/Document.pm

Fixes #1271 (see discussion in issue for problem diagnostic)
The Document `floatToElement` method is getting a bit subtle for me, and this PR is just the patch that happened to come to mind when poking around the example. Unsure if it's the right general treatment however.
In short, there is a special case where `floatToElement` is returned almost immediately, when the first candidate is acceptable. The return is direct under the assumption that the first candidate is always the current Document node, which is _almost_ always exactly true. There is an exception in the case where the current node is a text node, rather than a "regular" node, in which case the master `floatToElement` would return the parent element, while leaving the text node as the currently open node.
If this reads a …

close text elements when floating to their parent element

---

lib/LaTeXML/Package/TeX.pool.ltxml

Paying off some technical debt, this tripped me up today as I am investigating the expansion details in `\edef`. The leftover `$expanded` flag can now be removed, having standardized towards using an `EExpanded` argument type for `\edef` and `\xdef`.

finish do_def refactor without $expanded

---

lib/LaTeXML/Package.pm
lib/LaTeXML/Package/pgfsys-latexml.def.ltxml

Fixes #1227 , and improves towards also fixing #1196 .
Second attempt after the previous #1255  PR hit a dead end. This time I decided to approach things a little closer to the TeX machinery. In particular, by making the `\lxSVG@begingroup@` , which is a constructor solely focused on the output XML markup, a little smarter.
To reiterate my previous realization, since TeX makes no inherent distinction between "drawing" and outputting "content", the pgf/tikz machinery intertwines the two at will without any negative consequences. Meanwhile, at least in the cases of `\hbox` generating `svg:foreignObject` we hit cases where the current open element in the document is in the `ltx:` namespace, but the insertion coming in is for an `svg:` construct. There are a wide range of configurations that …

Improve on svg:g scaffolding bindings

---

lib/LaTeXML/resources/XSLT/LaTeXML-jats.xsl

This adds templates for `sub` and `sup`, and tidies up the templates for `bold` and `italic`.
* Add `ltx:sub` => `sub`
* Add `ltx:sup` => `sup`
* Move `ltx:emph` => `italic`
* Move `ltx:text[@font='bold']` => `bold`
* Move `ltx:text[@font='italic']` => `italic`
* Remove duplicate `ltx:text[@font='italic']` => `italic`

Add subscript and superscript to JATS conversion

---

bin/latexmlpost
lib/LaTeXML.pm
lib/LaTeXML/Common/Config.pm
lib/LaTeXML/Common/Error.pm

Addresses the usability friction raised in [the discussion](https://github.com/brucemiller/LaTeXML/issues/649#issuecomment-627373957) in #649 .
Namely:
1. Raise "real" warnings when `--mathsvg` and `--mathimages` are used without `--destination` in both latexmlpost and the LaTeXML.pm API
2. Change the default single option behavior of `--mathsvg` to *only* provide SVG formulas, rather than implicitly including a presentation MathML base processor
3. Patch latexmlc to also provide the warning and disable `--mathsvg` without destination, as was always the case in latexmlpost. That features was never thoroughly tested in the latexmlc flow.

Mathsvg usability upgrades

---

lib/LaTeXML/Post/MathML/Presentation.pm

Fixes #1293 
In short, a libxml node snuck its way into a subroutine that only expected the arrayref representation of post nodes. I am also hearing bells go off about having too many `getQName`s in the codebase, but that may be a refactor for another day. Fixes the example in the reported issue, and seems reasonable as a patch.
Ideally, especially if we had a language with fast method dispatch, one could imagine a common internal node class that can dispatch equally well to either arrayref nodes or libxml nodes, but that may be itself a problem for another programming language.

associateNodeHook with both array and libxml ndoes

---

lib/LaTeXML/Post/Graphics.pm
lib/LaTeXML/Util/Pathname.pm

Fixes #1187 in the simplest possible way.
Greetings from my Windows OS. This PR is overly simplistic, but workable in standard cases where people don't use backslashes in Unix filenames. I am opening mostly to state that if the path is sanitized just before it is set as an `imagesrc` attribute, the change is nicely propagated to the result of post-processing, and I happily created an HTML that rendered as expected on a Windows Firefox. So a successful patch attempt over here. 
Happy to test alternatives too. The other bit of good news is that the latest latexml master still has all tests passing on my Windows machine, though that is with the expl3 tests skipped, as we're still avoiding them on Windows.

Avoid windows paths in post-processed graphics

---

lib/LaTeXML/resources/XSLT/LaTeXML-common.xsl

Fixing a rare post-processing fatal error from `arXiv:math0012024`. Simple enough, just being a little careful with double-dashes in creating comments in XSLT.
In this case the author had written `version 3 --- 5 mars 2001` as the date, hence the Fatal of 
```
LaTeXML-common.xsl line 82 element comment xsl:comment : '--' or ending '-' not allowed in comment
```

Sanitize date strings when generating xml comments

---

lib/LaTeXML/resources/XSLT/LaTeXML-webpage-xhtml.xsl

Fixes #1044 
Default continues to be javascript placement in head, say:
```
latexmlc --javascript=LaTeXML-maybeMathjax.js --dest=test.html 'literal:$\sqrt{x}$'
```
But you can now add an XSLT parameter `LATEJS` that will tell post-processing to deposit the javascript at the end of the body:
```
latexmlc --xsltparameter=LATEJS:true --javascript=LaTeXML-maybeMathjax.js --dest=test.html 'literal:$\sqrt{x}$'
```
Exact parameter name is open to change, it was the first name that came to mind. Turns out implementing this was way simpler than I was guessing, I can never tell with XSLT

allow specifying javascript inclusion at the end of <body>

---

lib/LaTeXML/Util/Image.pm

Another rare Fatal from arxiv in image scaling:
```
Warning:imageprocessing:Crop Image processing operation Crop (x, 0, width, 0, y, 1123, height, 0) returned Exception 310: geometry does not contain image `/tmp/material.jpg' @ warning/transform.c/CropImage/717
In Post::Graphics[@0x557cb4a47300] ->transformGraphic
Fatal:perl:die Perl died
Illegal division by zero at /home/deyan/perl5/lib/perl5/LaTeXML/Util/Image.pm line 331.
In Post::Graphics[@0x557cb4a47300] ->transformGraphic
```
We can avoid the division and short-circuit the scaling calls, leaving the document only with the warning, and retaining the otherwise good conversion. The Fatal example I am looking at (`0903.2803`) upgraded to a good-looking Warning doc with this PR.

Additional alertness for zero width/height values in image scaling

---

lib/LaTeXML/Package/calc.sty.ltxml

The next rare error comes from calc.sty, e.g. in arxiv `0907.3632`, and is again a case of division by zero.
I added a Warn and a fallback which improves that document to an Error-level with some HTML. Message example:
```
Warning:unexpected:<number> 
at calc: divisor should never be zero!
In Core::Gullet[@0x5632617bb6c0] /tmp/BFCA-INS.tex; from line 232 col 0 to line 232 col 75
```
Sadly, what comes out is quite broken, but it's a step in the right direction.

Explicit warnings on zero divisions in calc

---

lib/LaTeXML/Package/aas_support.sty.ltxml

Resolves the Errors in `astro-ph/0003429`, rooted in the [classic planotable construct](https://cds.cern.ch/record/304372/files/9605457.pdf) in AAS. Likely only helps with some handful of old AAS articles, but at least the resolution is simple - planotable seems to be largely identical to deluxetable, and aliasing them works wonders for the reference arXiv article - the three tables typeset well and error-free using the deluxetable internals.

Add {planotable} alias for {deluxetable} in aaspp4

---

MANIFEST
lib/LaTeXML/Package/english.sty.ltxml
lib/LaTeXML/Package/nil.ldf.ltxml

1. `\usepackage{english}` creates what is really a deprecation warning ("you should be using babel!") but does it via `\GenericError` so pollutes the cortex reports for arXiv with untrue error cases. I am adding a binding that does what the error suggests -- reroutes to a `\usepackage[english]{babel}`. 
2. There are a number of suspect related mini error reports in loading babel's English on monster, but I'm fixing one that I noticed on my 2019 texlive machine with the default loader (`nil.ldf`) for option-free babel. It turns out the recent `pdflatex` _also_ has babel primitives precompiled in. You can try running pdflatex on a single line of `\show\bbl@languages`, and you'll see it defined. So I read the contents of nil.ldf, saw it is expecting that macro defined, and am adding a …

[Babel] avoid loading english.sty and default nil.ldf errors-in-name-only

---

lib/LaTeXML/resources/javascript/LaTeXML-maybeMathjax.js

Updates mathjax to latest CDN recommended by mathjax documentation [here](http://docs.mathjax.org/en/latest/web/start.html#using-mathjax-from-a-content-delivery-network-cdn).

update mathjax url to recommended latest CDN

---

lib/LaTeXML/Core/Gullet.pm
lib/LaTeXML/Core/State.pm
lib/LaTeXML/Core/Stomach.pm
lib/LaTeXML/Core/Token.pm

Starting to put small piecemeal PRs to disentangle my expl3 work into acceptable chunks...
The first bit is correcting the catcode tables - we currently have 18 catcodes in Token.pm, indexed 0 through 17, and any catcode table should have exactly 18 elements, ideally chunked 4 per line, with a last line of 2 elements. I believe two of the Gullet tables had typos, as they trated Marker as array element 18 instead of 17, which spurred this. It became painfully clear when I added a new catcode and things were breaking. 
I also eliminated the use of raw integers in Token.pm for the `T_` constructors and relied on the `CC_` constants instead, to protect from possible typos.
Lastly, the linter warned me that the escapes `\'` and ``` \` ``` do not exist, so I dropped those backslashes from …

Fixes to catcode tables and minor lints

---

lib/LaTeXML/Package/TeX.pool.ltxml
lib/LaTeXML/Package/eTeX.pool.ltxml
lib/LaTeXML/Package/etoolbox.sty.ltxml
t/expansion/definedness.xml
t/expansion/meaning.xml
t/expansion/noexpand_conditional.xml
t/tokenize/hashes.xml

Detaching more of the (hopefully) independently reasonable upgrades that set the stage for the core upgrades needed for expl3 in texlive2020. Focus is on `\meaning`, `writableTokens` and some of the `\show`-like macros, which I think can be upgraded in isolation.
Curious to see if the Travis expl3 tests will pass.
(This PR was originally opened at [#5](https://github.com/dginev/LaTeXML/pull/5) and I am migrating it by hand, now that the main fork's master has moved)

upgrades to \meaning, \show-like macros, writableTokens

---

lib/LaTeXML/Package/physics.sty.ltxml
t/complex/physics.xml

Follow-up to commit 640cfc7a664f541f1e66ce4f3a805e8b51af1048
I was testing the a11y generation for all tests in `t/complex/physics.tex` and noticed sine of the names looked suboptimal (`asine`, `hypsine` etc). So I quickly edited them and regenerated the tests, feel free to review/adopt/adapt.

Adding even more consistent names in physics.sty

---

lib/LaTeXML/Core/Box.pm
lib/LaTeXML/Core/Document.pm
lib/LaTeXML/MathParser.pm
lib/LaTeXML/Package.pm
lib/LaTeXML/Package/TeX.pool.ltxml
lib/LaTeXML/Package/amscd.sty.ltxml
lib/LaTeXML/Package/amsmath.sty.ltxml
lib/LaTeXML/Package/physics.sty.ltxml
lib/LaTeXML/Post/MathML.pm
t/alignment/plainmath.xml
t/ams/cd.xml
t/ams/mathtools.xml
t/ams/matrix.xml
t/complex/physics.xml
t/math/array.xml
t/math/sampler.xml

Another iteration in cleaning up the mathematical semantics.  This one focusing on the confusion of "matrix" as a type vs a constructor.  First, we enforce (a bit more) the idea that if a math subtree has a meaning attribute, that is the meaning of the whole subtree.  Then, we take the view that when we are constructing an XMArray that we believe is matrix, rather than misguidedly giving the array a meaning attribute, we apply "meaning" to the array as a constructor. 
[This still leaves open any eventual type or property attribute where we may wish to assert that a particular symbol (say X) is a matrix]

Cleanup semantics

---

lib/LaTeXML.pm
lib/LaTeXML/Core.pm
lib/LaTeXML/Util/Test.pm

Fixes #1342 .
Mainly detaches using `includecomments` of LaTeXML::Core to be used only for comments, introducing a new internal option `includexmlpis` to handle processing instructions.
Importantly, adapted the test cases to add this new option, and (more hackily) had the daemon API use the explicit xslt parameter to figure out this is a test environment. Simplest refactor that avoid introducing any user-facing new constructs that came to mind.

Separate comments toggle from processing instruction toggle

---

lib/LaTeXML.pm
lib/LaTeXML/Core.pm
lib/LaTeXML/Util/Test.pm
tools/maketests

Further touchups on #1343 
* renamed option to `includepathpis`
* switched to using `LaTeXML::Util::Test` in `tools/maketests` for core test generation
* separated out the conversion and serialization subroutines in Test, to reuse the exact same code paths for generation and testing
* dropped the ability to control `--verbosity` in tools/maketests -- can reintroduce if considered important (I've never used it)

use LaTeXML::Util::Test in maketests, better pathpi option name

---

lib/LaTeXML/Common/Font.pm
lib/LaTeXML/Core/Mouth.pm
lib/LaTeXML/Package/LaTeX.pool.ltxml
lib/LaTeXML/Package/TeX.pool.ltxml

Fixes the texlive 2020 regression with expl3, while also enhancing further our `\meaning` emulation.
I double-coded [the previous PR](https://github.com/dginev/LaTeXML/pull/6) to avoid rebasing, since the diff was so small it was simpler to copy it directly over the new master.

add \meaning handling for \font-defined primitives

---

lib/LaTeXML/resources/RelaxNG/LaTeXML-math.rnc
lib/LaTeXML/resources/RelaxNG/LaTeXML-math.rng
lib/LaTeXML/resources/RelaxNG/LaTeXML.model

Today I noticed the (still experimental, per PR #947 ) lexemes attribute is naturally considered illegal in validation, so I thought I might as well add it to the schema. Feedback welcome on what would be the best way to document it.

adding lexeme attribute to ltx:Math schema

---

lib/LaTeXML/Package/caption.sty.ltxml

Just adding the optional argument, verified that pdflatex accepts it just fine.

Fixes #1352

---

lib/LaTeXML/Package/pgfmath.code.tex.ltxml

Fixes #1168 .
May not be the ideal fix, but I feel confident I debugged the root issues:
1. The original latex `\pgfmath@smuggleone` simply assumes it has a locally defined expandable macro on input, and re-defines it locally a level up after it closes a group with `\egroup`. 
- However, the latexml binding handles certain internal constructs by creating Primitives with subroutines as their definition, making the technique of smuggle one equivalent to `\def#1{#1}` i.e. an infinite loop.
- Solution: added a binding that checks for the non-expandable case, and only closes a group if in it (assuming that definition was already global).
2. Separately, our parameter type for `pgfNumber` didn't strike me as accurate. Here too I debugged with `\tracingmacros=1` and reading attentively the …

More precise binding for pgfNumber and pgfmath@smuggleone

---

lib/LaTeXML/Post/MathML.pm

Consider the first token in the following XMath (generated by a semantic macro `\fnderive{f}{n}`):
```xml
<XMath>
<XMApp>
<XMTok role="SUPERSCRIPTOP" scriptpos="post1" meaning="derivative-implicit-variable" name="fnderive@build"/>
<XMTok role="UNKNOWN" xml:id="p1.m1.1" font="italic" fragid="p1.m1.1">f</XMTok>
<XMDual xml:id="p1.m1.2" fragid="p1.m1.2">
<XMRef idref="p1.m1.2.1"/>
<XMWrap>
<XMTok role="OPEN" stretchy="false" fontsize="70%">(</XMTok>
<XMTok role="UNKNOWN" xml:id="p1.m1.2.1" font="italic" fontsize="70%" fragid="p1.m1.2.1">n</XMTok>
<XMTok role="CLOSE" stretchy="false" fontsize="70%">)</XMTok>
</XMWrap>
</XMDual>
</XMApp>
</XMath>
```
The first token is the main operator, with role `SUPERSCRIPTOP` and a macro-provided meaning `derivative-implicit-variable`. I claim the expected …

Use meaning over role in MathML::lookupContent

---

MANIFEST
lib/LaTeXML/Package/LaTeX.pool.ltxml
lib/LaTeXML/Package/OmniBus.cls.ltxml
lib/LaTeXML/Package/aipproc.sty.ltxml

Examining some arXiv errors, I am suggesting:
- add `\volume` and some sibling metadata macros to OmniBus.cls, since they seemed needed in cases where a custom `.cls` file was ignored by latexml when processing arXiv articles
- add [the arXiv artifact aipproc.sty](https://arxiv.org/list/physics/macros) with a specialized binding. 
The second point is a pain, because we also have a `aipproc.cls.ltxml`, from the arXMLiv Jacobs work, which seems to be developed for the later [aipproc.cls](http://dark.ft.uam.es/dsu2006/proc/AIPPROC/aipguide-6s.pdf), which is more evolved, e.g. expects key=vals for the `\author` macro rather than a simple strict.
It seems like a good default behaviour is to load the essentially revtex3-equivalent `aipproc.sty` when encountering `\documentstyle{aipproc}`, while …

aipproc.sty and extensions to OmniBus

---

lib/LaTeXML/Package.pm
lib/LaTeXML/Package/LaTeX.pool.ltxml

Quick follow-up to #1300 , I did some related testing with:
```tex
\documentstyle[xcolor]{article}
test \color{red} test.
\end{document}
```
and realized my kpsewhich found `article.sty` in texlive and tried to load it even though I did not provide `--includestyles`. So, patched!

ensure intended extensions only in FindFile wrt documentstyle

---

lib/LaTeXML/Package/LaTeX.pool.ltxml
lib/LaTeXML/Package/amsthm.sty.ltxml

Should be a mostly correct fix, getting a little closer to the TeX behavior for the head formatter of a new theorem environment. Here is a screenshot showing HTML-to-PDF parity with the example of the reporting issue:
If tests pass, it ought to be a safe chance, or at least no more dangerous than the code we have already :>

Fixes #1351

---

lib/LaTeXML/Package/aas_support.sty.ltxml
lib/LaTeXML/Package/aastex.cls.ltxml
lib/LaTeXML/Package/acmart.cls.ltxml
lib/LaTeXML/Package/deluxetable.sty.ltxml
lib/LaTeXML/resources/CSS/LaTeXML.css
lib/LaTeXML/resources/XSLT/LaTeXML-structure-xhtml.xsl
t/complex/aastex_test.xml

Quick & dirty PR aimed at content-preserving, but presentationally imperfect, aastex63.cls arXiv documents.
Took me way too long to wrestle down an error-free version of the `D` column - but I managed! Still, I am making a PR with some remaining visual issues, hoping to borrow wisdom from @brucemiller as to what should be improved before the release and what after. I'd like to get the additions in for the latest arXiv run, since I have seen new papers using aastex63.cls.
As to what I managed to achieve, my main focus was getting the `sample63.tex` official template converting without issues to HTML, [online PDF here](http://tug.ctan.org/tex-archive/macros/latex/contrib/aastex/sample63.pdf).
Here are two side-by-side tables stress-testing the tricky new `h` and `D` column specifiers. HTML …

Add basic support for newest aastex63

---

lib/LaTeXML/Package/hyperref.sty.ltxml
lib/LaTeXML/Package/url.sty.ltxml

Took a break from Hard Debugging with some easy debugging.
We have a simple Fatal:misdefined  in arXiv from the `__ANON__` subroutines, likely rare, in [this paper](https://arxiv.org/abs/astro-ph/0001345), related to hyperref's url. I isolated the tex and added a second variation to be sure I am seeing things right:
```tex
\usepackage{hyperref}
T1: {\url http://cossc.gsfc.nasa.gov/cossc/batse/}.
T2: {\url|http://cossc.gsfc.nasa.gov/cossc/batse/|}.
\end{document}
```
And noticed the PDF only takes in the first token in this aberrant situation:
while latexml is currently trying to use the leading `h` as an open delim. So this PR switches to the simpler pdflatex behavior. I also checked that this is indeed specific to hyperref itself, because if you …

Read single token if not balanced in hyperref \url

---

lib/LaTeXML/Package/LaTeX.pool.ltxml

Looking at the [error:unexpected](https://corpora.mathweb.org/corpus/arxmliv/tex%5Fto%5Fhtml/error/unexpected?all=false) report, I was surprised to see 1.18% of tasks sharing an error about an unexpected `\endlx@list` macro.
Debugging two articles:
1. In the first, [astro-ph/0001014](https://arxiv.org/abs/astro-ph/0001014), I noticed that the issue comes from redefining the bibliography macros in the custom local `.sty` file. We are successfully locking those when the new definition is done via `\def`, but for the ending macro the switch is done via `\let`:
```tex
\let\endthebibliography=\endlist
```
And locking macros against `\let`s isn't a viable strategy. However, I noticed we always execute a sub `beforeDigestBibliography` when `\thebibliography` is invoked, and it appears quite safe …

[arXiv patches] \endthebibliography, \@definecounter, low-level font size macros

---

lib/LaTeXML/Package/LaTeX.pool.ltxml

Another underscore error, [in this paper](https://arxiv.org/abs/cs/0208043), was wrongfully illegal in:
```tex
\newenvironment{theorem_cite}[1]
```
Turns out this is perfectly workable in the native TeX, due to `\csname` and `\endcsname` wrapping the `theorem_cite`. LaTeXML was doing a bit too much here, all the way to digesting, rather than simply expanding. So I switched to that and the paper seems to succeed well with the theorems looking good. latexml tests pass in a breeze. Should be an easy merge.

[arXiv patches] only need to expand in \newenvironment

---

lib/LaTeXML/Package/aas_support.sty.ltxml

A number of documents in the 1.77% [error:unexpected:_](https://corpora.mathweb.org/corpus/arxmliv/tex%5Fto%5Fhtml/error/unexpected/%5F?all=false) report seem to be due to underscores in captions, in particular at the filename optional argument, e.g. in [astro-ph/0001049](https://arxiv.org/abs/astro-ph/0001049):
```tex
\figcaption[dev_join.eps]{The equivalent number of Gaussian standard...}
```
It turns out this is handled correctly as semiverbatim in the aas_support binding with:
```perl
DefMacro('\@figcaption OptionalSemiverbatim {}', ...
```
but in the cases where the macro is used inside a `{figure}`, it gets redirected to the main LaTeX.pool `\caption` macro. And there the expected optional argument was plain, rather than semiverbatim. Changing that gets the article in question to …

[arXiv patches] Allow semiverbatim in \figcaption filenames

---

lib/LaTeXML/Package.pm
lib/LaTeXML/Package/LaTeX.pool.ltxml
lib/LaTeXML/Package/enumitem.sty.ltxml
lib/LaTeXML/Package/slides.cls.ltxml
t/ams/amsdisplay.xml
t/daemon/formats/jats.xml
t/daemon/formats/tei.xml
t/fonts/ding.xml
t/structure/amsarticle.xml
t/structure/article.xml
t/structure/book.xml
t/structure/enum.xml
t/structure/itemize.xml
t/structure/paralists.xml
t/structure/report.xml

This PR makes the ids of all nested lists (itemize, enumerate, description, ...) relative to the item's id (irrespective of what kind of list). Alas it makes the ids longer and the code is a bit more obscure, but avoids id clashes.

Itemization ids

---

lib/LaTeXML.pm
lib/LaTeXML/Post/Scan.pm

Very minor warnings (undef vs empty string) that showed up in some of the main latexmlc calls, best to get rid of them and keep the noise levels low.

minor perl warning appeasement in main latexmlc calls

---

lib/LaTeXML/Package/pdfTeX.pool.ltxml

All should be ignorable (at least for now) and minor, and shave off some noise from the arXiv error logs (which is how I got here).
Maybe enough time for one last small PR ?
I went through the list at section 7 here:
http://texdoc.net/texmf-dist/doc/pdftex/manual/pdftex-a.pdf
and added the bits that were missing. You may need `?w=1` to avoid looking at the relinted lines though.

More recent primitives for pdfTeX.pool

---

lib/LaTeXML/Common/Model.pm
lib/LaTeXML/Package/LaTeX.pool.ltxml

Certain arXiv articles seem to have an alternatively named .bbl file (because why not), and we're currently filing a hard Error for missing the wrongly expected bbl. For instance in this example, in file `main.tex`:
```tex
\input{OOD.bbl}
\bibliographystyle{ACM-Reference-Format}
\bibliography{OOD}
```
Even after emitting the Info message that `main.bbl` isn't found, we also emit an Error from trying to `\input` it anyway. This PR simply avoids trying to load a file we can't find. No other fix is needed since the alternative file `OOD.bbl` gets loaded just fine.
Also, made `canContain` a little quieter when called with an empty `$tag`, since this doc also did that a bunch.
Article in question was [1905.01726](https://arxiv.org/abs/1905.01726)

[arXiv patches] avoid loading a missing .bbl file

---

lib/LaTeXML/Package/LaTeX.pool.ltxml
lib/LaTeXML/Util/Pack.pm

Fixes [1905.00934](https://arxiv.org/abs/1905.00934). More importantly, it has the potential of avoiding confusion in detecting the main TeX source file from an arXiv paper directory. 
For the example of this paper, there were equally viable `main.tex` and `main.v10.tex` source files in the root directory. If following the official `arXiv::AutoTeX` logic, the first lexicographic entry would be considered primary, i.e. `main.tex`, but in this case that is the wrong choice. I didn't find official language how arXiv would have found the right file, and the timestamps seem identical.
However, one of the files has a `.bbl` of the same name, while the other doesn't. So, for arXiv, this looks like a meaningful heuristic as a final tie-breaker between otherwise equally viable files. The one with …

[arXiv patches] Use .bbl heuristic when unpacking; handful extra latex macros

---

lib/LaTeXML/Package/pdfTeX.pool.ltxml
lib/LaTeXML/Package/quantumarticle.cls.ltxml

I remembered engrafo has some [latexml-running tests](https://github.com/arxiv-vanity/engrafo/tree/master/tests/integration) for arxiv-vanity and tried to run them as sources of potential regressions yesterday. Still going through the last few, mostly OK.
A paper that was a bit "too loud" with pointless errors was [1803.07574](https://github.com/arxiv-vanity/engrafo/tree/master/tests/integration/papers/1803.07574), mostly due to expl3 wanting to bind some extra pdftex primitives which we hadn't added stubs for.
So I added stubs, trying to be at least a little precise with some of the argument specs (but not with all, just enough to get the paper+expl happy). I also added a missing `{acknowledgements}` definition to the rare class file of the article. Moving to the other tests...

[arXiv patches] Stubs for a few extra pdftex primitives, bound by expl3

---

lib/LaTeXML/Core/Document.pm
lib/LaTeXML/Package/OmniBus.cls.ltxml
lib/LaTeXML/Package/TeX.pool.ltxml
lib/LaTeXML/Post.pm
lib/LaTeXML/Post/Scan.pm
lib/LaTeXML/Post/XSLT.pm

Block recursion warnings in a few places where we traverse the XML tree from top-to-bottom, which can be deep, but without cycles.  Also increase the XSLT recursion limit.  These are mostly due to redundant `svg:g` elements, which we'll want to fix, but the results are often acceptable anyway.
Probably will be following up with a couple of semi-related patches.

Less restrictive of recursion (usually redundant svg:g)

---

lib/LaTeXML/Util/Pathname.pm

So, `paper.tex.tex` is something used as a main source file in arXiv at times. And I assume other variations of double extensions may exist... Paper in question is [cond-mat/0411005](https://arxiv.org/abs/cond-mat/0411005).
Fix is easy, and should only fire in specific cases where a search has a `file.ext` and also requests the same extension via `type=>'ext'` or `types=>['ext']`, when this PR will now also search for `file.ext.ext`. I was wondering why we were getting Fatals failing to find `.tex` files, now it makes sense:
https://corpora.mathweb.org/corpus/arxiv%5Ftestbench/tex%5Fto%5Fhtml/fatal/missing%5Ffile/%2Fdev%2Fshm%2F91FiBpkiy1%2Fpaper%2Etex?all=false

[arXiv patches] be able to find paper.tex.tex

---

lib/LaTeXML/Post/CrossRef.pm

I looked at the warning documents quickly and spotted a visual regression that we had addressed, before in #1150 , the empty `()` in citations without a year, mostly in the arXiv case of bbl-only information.
At some point the delimiter changed from ` year phrase2` to `{}year{}phrase2` and the guard wasn't migrated, so it didn't take effect. I've updated that regex and the following minimal-ish example converts more acceptably again:
```tex
\documentclass{revtex4-1}
Abdul-Rahman et al. in arXiv:1901.09297~\cite{Abdul-Rahman2019} provided an elegant approach and proved analytically ...
\begin{thebibliography}
\bibitem{Abdul-Rahman2019}
H. Abdul-Rahman, M. Lemm, A. Lucia, B. Nachtergaele, and A. Young,  A Class of Two-Dimensional AKLT Models with a Gap, arXiv:1901.09297. …
```

[arXiv patches] Maintain the empty () hack for revtex4-1 bibs with no year

---

lib/LaTeXML/Package/IEEEtran.cls.ltxml

One case of undefined `{keywords}` in arXiv was due to IEEEtran deprecating its older aliases, but older arXiv sources still using them (naturally).
An example article is cs0010013, downloadable [here](https://corpora.mathweb.org/entry/import/1824861).
I added the entire deprecation block from the end of [IEEEtran.cls](http://mirrors.ctan.org/macros/latex/contrib/IEEEtran/IEEEtran.cls), hopefully catching some of the other spurious errors.

Update to support noted deprecations from latest IEEEtran.cls

---

lib/LaTeXML/Package/mathtools.sty.ltxml

Another minor niggle from arXiv, found that an `\includegraphics` was used undefined in a recent 2019 paper. Turns out mathtools [now depends](http://lcd-www.colorado.edu/~axbr9098/tmp/chiral-mhd/paper2/mathtools.sty) on more packages, so I added the easy ones in.
The `mhsetup` one is interesting to look into with some care on a rainy day, deferring that one for now.

Add latest required packages of mathtools

---

lib/LaTeXML/Package/LaTeX.pool.ltxml

This is fundamentally very simple, but still kind of icky, since I am not sure where the perfect patch would be located.
The minimal example (found in arXiv) is the following valid use of `\usepackage`:
```tex
\usepackage{ams thm}
test
\end{document}
```
Turns out the arguments ignore/discard the spaces. Since we are handling the argument parsing for package and class loading macros in the `afterDigest` perl subroutines, I went ahead and changed a bunch of them to actively discard spaces before passing the names on into the Package.pm loader machinery. Could fix a number of weird missing style files? And ideally is a no-op for anything else.
I also used a tight imperative for loop instead of the multiple grep/map calls, since I keep remembering …

Ignore spaces in args for package and class loader macros

---

lib/LaTeXML/Package/elsart_support.sty.ltxml

In [1607.07653](https://corpora.mathweb.org/entry/import/1820146), I noticed two missing macros from Elsevier's class file, which seem to be documented in [newer versions of their manual](https://www.elsevier.com/__data/assets/pdf_file/0008/56843/elsdoc-1.pdf), Section 7.
Adding the two macros as aliases to `\newtheorem` gets that arXiv document passing nice and smooth.

add \newdefinition \newproof macros to elsart

---

lib/LaTeXML/Package/OmniBus.cls.ltxml

Oversight on my part last time I extended OmniBus, I missed {proof}, which has 0.53% reported at arXiv. Still checking if other packages need it, but the two papers I double-checked were falling back exactly on OmniBus.

add proof support in OmniBus

---

lib/LaTeXML/Package/LaTeX.pool.ltxml

A new common undefined report over arXiv comes from us interpreting local `.sty` files raw, which at times define/redefine environments using the internal boilerplate from latex.ltx.
I thought there may be an easy win in this regard, where we preserve the new name of the float, and use the generic `ltx:float` from latexml.
A self-contained example one can try to validate the PR is:
```tex
% originally defined in a local chart.sty
\makeatletter
\newcounter{chart}
\renewcommand\thechart{\@Roman\c@chart}
\def\fps@chart{tbp}
\def\ftype@chart{1}
\def\ext@chart{loc}
\def\fnum@chart{\chartname~\thechart}
\newenvironment{chart}
{\@float{chart}}
{\end@float}
\newenvironment{chart*}
{\@dblfloat{chart}}
{\end@dblfloat}
\newcommand\listofcharts{%
\section*{\listchartname …
```

add stubs for @float and @dblfloat from LaTeX

---

MANIFEST
lib/LaTeXML/Core/Definition/Constructor.pm
lib/LaTeXML/Core/Definition/Primitive.pm
lib/LaTeXML/Package/espcrc.sty.ltxml

The `espcrc` (1 and 2) part of the PR is easy, just a very old style used by arXiv that adds `\address`. 
The second part of the PR hit a phenomenally sinister bug, which hopefully was freshly introduced by "better" use of `RequirePackage`. Though I am _still_ not sure if it is fresh or old, and the exact mechanics behind the last steps of it.
A very good testing file is [cs/0309037](https://corpora.mathweb.org/entry/import/2272595) ran with includestyles, e.g.
```
latexmlc test.zip --dest=test.html --includestyles
```
If you observe the log and the raw loaded `aadebug.cls`, you will see a report of only **the first** of the following calls to `\RequirePackage`:
```tex
\RequirePackage[latin1]{inputenc}
\RequirePackage[T1]{fontenc}
\RequirePackage{palatino}
\RequirePackage[dvips]{graphicx} …
```

espcrc2.sty and Safe use of subs in bindings

---

lib/LaTeXML/Package/LaTeX.pool.ltxml
lib/LaTeXML/Package/OmniBus.cls.ltxml
lib/LaTeXML/Package/inst_support.sty.ltxml
lib/LaTeXML/Post/MathML.pm

A "caring for the wounded" PR, while examining the high-up entries in the "Error:undefined" arXiv report. I spotted [\snm](https://corpora.mathweb.org/corpus/arxmliv/tex%5Fto%5Fhtml/error/undefined/%5Csnm?all=false) pretty high up and there were also some related shorthand macros pertaining to doc metadata in non-standard .cls files. 
Some of the errors really require adding new bindings (e.g. `bbook`-related), or  reading the class file (e.g. local `\tfrac` definition), but others felt addressable directly in OmniBus, when there was hope for standard metadata infrastructure, or standard usage of amsthm.
This PR is testing on a single paper, [0709.3896](https://arxiv.org/abs/0709.3896), 
The conversion summary from a master run:
> Status:conversion:2 
>
> 178 warnings; 46 errors; 44 …

more infra in OmniBus; improve multi script Error message

---

lib/LaTeXML/Common/Font.pm
lib/LaTeXML/Core/Document.pm
lib/LaTeXML/Package/TeX.pool.ltxml
lib/LaTeXML/Package/pgfkeys.code.tex.ltxml
lib/LaTeXML/Package/pgfmath.code.tex.ltxml
lib/LaTeXML/Package/pgfsys-latexml.def.ltxml
lib/LaTeXML/Package/pgfutil-common.tex.ltxml
lib/LaTeXML/Package/tikz.sty.ltxml

This PR runs a cleanup of `svg:g` elements after they close to check for redundancies, or when they are completely masked by a child, or if a child establishes a complete set of the same attributes, and so can be pulled out.  This vastly reduces both the size and depth of tikz/pgf documents, particularly when run with post-2017 texlives.
In the process, a couple of other tikz regressions were suddenly discoverable and were fixed.  More can probably be found and fixed?  Also, since this fixes some tikz regressions that didn't cause outright failure, but very poor rendering, a rerun of arXiv tikz might be in order (when this is complete).

Pgf cleanup

---

MANIFEST
lib/LaTeXML/Package/LaTeX.pool.ltxml
lib/LaTeXML/Package/standalone.cls.ltxml

Fixes the easy `.cls` half of #678
I was trying out a TeX snippet from twitter (of all places) and noticed it's using standalone. Trying out `--includestyles` almost worked out of the box, and it wasn't really meant to do much, so I added a simple binding that delegates to the raw `.cls` implementation, as a quick&easy fix.
The snippet actually creates very nice HTML5 with the latest latexml master, with embedded MathML in the (neat and to the point) SVG.
```tex
\documentclass[border=1cm]{standalone}
\usepackage{tikz}
\usetikzlibrary{positioning}
\begin{tikzpicture}
%draw a polygonal chain that traces the order on a tiny finite fragment of the product
\draw (0,0) -- (0,1) -- (1,0) -- (1,1) -- (0,2) -- (1,2) 
-- (2,0) -- (2,1) -- (2,2) -- (0,3) -- (1,3) -- (2,3) -- (3,0) …
```

Try out raw support for standalone.cls

---

lib/LaTeXML/Package/listings.sty.ltxml

Fixes #1400 with a simple patch that allows cleveref and listings to co-exist.

Allow smooth loading of cleveref with listings

---

lib/LaTeXML/Package/iopart_support.sty.ltxml

Upgrades [cond-mat/0002162](https://arxiv.org/abs/cond-mat/0002162) from Error to Warning status. Small oversights in iopart binding.

[arXiv patches] iopart support tweaks

---

lib/LaTeXML/Package.pm

I was a bit confused by reports of undefined [\citealp](https://corpora.mathweb.org/corpus/arxmliv/tex%5Fto%5Fhtml/error/undefined/%5Ccitealp?all=false) and doubly so after I realized they _do_ load natbib correctly.
It turned out that in certain cases natbib would load _before_ OmniBus.cls does, which exposed an interesting conditional related to `DefAutoload`.
It seems that conditional was only checking if the raw TeXy file was loaded, but not if the `.ltxml` binding may have been loaded (as was the case for natbib). Additionally, I think that method should set a command sequence only if it was undefined so far, and never override an existing assignment - so I added a check for `LookupMeaning`.
I tested on the first doc in this report category, cond-mat/0001011

Avoid DefAutoload unless truly certain

---

lib/LaTeXML/Package/LaTeX.pool.ltxml
lib/LaTeXML/Package/OmniBus.cls.ltxml

So, um, I hope you don't take this the wrong way...
But people are doing weird stuff with the latex.ltx primitives in arXiv! In particular, [gr-qc/0003053](https://arxiv.org/abs/gr-qc/0003053) uses `\savebox1{arg...}` and `\usebox1`, rather than the officially documented backslash-starting box name.
And.. well, it actually works, because the native latex.ltx code allows it to work!
I'm a little hestient to suggest merging here, but I am wondering what other tests one would need to be convinced the native TeX definition works well. It seems to be improving the arXiv article in question at least, but... lilkely worth discussing :>

closer to native latex.ltx, add \abstracts to OmniBus

---

lib/LaTeXML/resources/XSLT/LaTeXML-structure-xhtml.xsl

I finally felt brave enough to open a `no_problem` article in arXiv, namely [the HTML of 1504.05855](https://corpora.mathweb.org/preview/arxmliv/tex_to_html/1504.05855?style=simple), and spotted a cosmetic oversight.
The current XSLT allows a `\date{}` to propagate into the HTML as `<div class="ltx_dates">()</div>`, due to a test which checks only if a node exists, but not whether it is empty.
Not my most notable PR ...

Ensure empty dates dont deposit any content in HTML

---

lib/LaTeXML/Post/Graphics.pm

some (old?) arXiv documents use graphic files with a `.postscript` extension as in e.g.
```tex
\psfig{figure=340p0_jonker.postscript,height=2.in}
```
from [astro-ph/0001167](https://arxiv.org/abs/astro-ph/0001167). Supporting these seems as easy as whitelisting the extension in Post::Graphics. Currently they fail to be found with the warning:
```
Warning:expected:source No graphic source found; skipping
source was 340p0_jonker.postscript
In Post::Graphics[@0x5647a075c8a8] ->processGraphic
```

[arXiv patches] support graphics with .postscript extension

---

MANIFEST
lib/LaTeXML/Package/LaTeX.pool.ltxml
lib/LaTeXML/Package/filehook.sty.ltxml
lib/LaTeXML/Package/standalone.sty.ltxml

Fixes #678
At least a basic use of standalone.sty should be supported now.
Example [from the docs](https://ctan.math.illinois.edu/macros/latex/contrib/standalone/standalone.pdf), if you have two files:
- main.tex
```tex
% Main file
% Real document class:
% Use the ’standalone’ package:
\usepackage{standalone}
% Load all packages needed for all sub−files:
\usepackage{tikz}
% Inside the real ’document’ environment
% read the sub−file with ’\input’
% ...
\begin{figure}
\input{fig}
\caption{A subfile}
\end{figure}
% ...
\end{document}
```
- fig.tex
```tex
\documentclass[tikz]{standalone}
\usetikzlibrary{calc}
\begin{tikzpicture}
\draw (0,0) rectangle (2,1) node [midway] {Example};
\end{tikzpicture}
% Further ’tikzpicture’ environments …
```

Basic support for standalone.sty

---

lib/LaTeXML/Package/TeX.pool.ltxml

Fixes #1455 
A bit of a losing battle, but since there is only a finite number of primitives, might as well fight another round. I excepted 3 command sequences that are TeX primitives and used as such via `\meaning`, but are currently defined via `DefMacro` in latexml.
It is starting to dawn on me that `\meaning` is a bit of an information bottleneck for this distinction - in most (all?) instances where the primitive vs macro difference is relevant to a module developer or tex author, it is accessed through `\meaning`. So ensuring pdftex parity in the definition of `\meaning` itself is viable, and much easier than refactoring all `DefMacro`s into equivalent `DefPrimitive`s.
Expedient suggestion, but maybe expedience is appropriate?

add exception guards to \meaning for some primitives

---

lib/LaTeXML/Package/LaTeX.pool.ltxml
lib/LaTeXML/Package/TeX.pool.ltxml

Fixes #1430 
Apparently we need to add some of the token hooks of TeXBook p.275 to their respective callers. I would assume there is more to add, but this should be a reasonable start which addresses the minimal example in the issue.
I also snuck in a tiny internal latex.ltx macro, and a small fix that properly prints the `\meaning` of a tokens register with the `\toks` prefix.

add \everymath and \everydisplay hooks

---

lib/LaTeXML/Package/texvc.sty.ltxml

Encountered while "lexematizing" StackExchange, which loads the texvc macro subset (via mathjax).
It turns out that the catcode switch for `$` and `%` are quite rocky over SE expressions, and were not playing along with `\text` well. So I opened the latest texvc.sty I could find, which seems to be:
http://www.tug.org/texlive///Contents/live/texmf-dist/tex/latex/texvc/texvc.sty
and authored by @physikerwelt some years back?
Since that file only introduces macros, I reworked our binding to do that as well. Updated packages+macro set as well. Would be nice to have merged soon, but I can also keep a local SE conversion running on this branch, fine with me either way.

Updated texvc.sty

---

lib/LaTeXML/resources/CSS/LaTeXML-navbar-left.css
lib/LaTeXML/resources/CSS/LaTeXML-navbar-right.css
lib/LaTeXML/resources/CSS/LaTeXML.css
lib/LaTeXML/resources/XSLT/LaTeXML-html5.xsl
lib/LaTeXML/resources/XSLT/LaTeXML-webpage-xhtml.xsl

This is an attempt at modernising the generic HTML5 output.
I have added a meta viewport tag, strictly for the HTML5 output only, with default value `width=device-width, initial-scale=1, shrink-to-fit=no` (taken from [arXiv Vanity](https://www.arxiv-vanity.com/)). This should make the output mobile friendly in most cases. I think it's reasonable to turn it on by default, as the current output is generally bad on mobile, and the tag has no effect on desktop anyway.
I'd like to make a few more changes like this, so I thought of adding XSLT parameters to configure these updates. As I mentioned on the mailing list, inlining SVG images and using `<img>` instead of `<object>` would be next, and for that a parameter like `INLINE_SVG` is probably warranted to maintain compatibility with old …

Modernize HTML5: add viewport meta tag

---

lib/LaTeXML/Package/texvc.sty.ltxml

Thanks for merging #1466 ! It unlocked another debugging round for me, which led to my seeing a construct that had previously dodged my attention - the MathJax-postulated `\unicode` macro. Thankfully that is incredibly simple, docs here:
http://docs.mathjax.org/en/latest/input/tex/extensions/unicode.html
It's used in StackExchange, which relies heavily on texvc.sty, and I think it is a rather good location to unify all not-quite-tex extensions. But if you'd like a stranger `mathjax.sty.ltxml` contribution, I could also refactor to that...

add \unicode extension from MathJax to texvc.sty

---

lib/LaTeXML/resources/XSLT/LaTeXML-misc-xhtml.xsl

These are the uncontroversial parts of #1444, needed to fix standards-compliance as per #1440 and to achieve some low effort accessibility improvement.

Replace object alt attribute with aria-label and text fallback

---

lib/LaTeXML/Util/Test.pm

Check LATEXML_KPSEWHICH variable, when detecting TeXLive version for testcase exclusions

Improve TeXlive detection during testing

---

lib/LaTeXML/resources/XSLT/LaTeXML-epub3.xsl

Quick fix for #1457 until a better solution is available.

remove download button from listings in EPUB3

---

lib/LaTeXML/Package.pm

I think we're a little too zealous trying to find an ltxml fallback file in the case where we're already using `INTERPRETING_DEFINITIONS`. In the bug report `filehook.sty` tries to load `filehook-2019.sty`, but the fall back "corrects" this back into `filehook.sty`!
Hopefully, this still does all the right things in an arXiv context?
fixes #1470

don't force fallback to .ltxml if INTERPRETING_DEFINITIONS

---

lib/LaTeXML/Core/Gullet.pm
lib/LaTeXML/Package/TeX.pool.ltxml

fix \endinput to preserve pushback'd tokens; update gullet->flushMouth to do that job.
Fixes #1481

fix \endinput

---

MANIFEST
lib/LaTeXML/Package/minimal.cls.ltxml
lib/LaTeXML/Package/proofwiki.sty.ltxml

After texvc.sty, I've now stumbled on proofwiki.org and its mini macro language for MathJax. The binding is a direct copy-over from the mathjax macro definitions on each proofwiki page, and seems quite straightforward.

Binding with proofwiki's mini macro language for MathJax

---

lib/LaTeXML/Core/Stomach.pm

Fix the badfix (begin/endgroup should NOT look like braces for alignments)

fix halign hack

---

t/expansion/utflettercase.tex
tools/maketests

Here is one suggestion to provide a hint to compile a testcase. It solves the problem that t/expansion/uflettercase.tex needs xelatex to successfully compile. But maketests tries to either pdftex or pdflatex if called with --pdf option. Use a simple hinting (compatible to llmk) to find out which compiler should be used. 
t/expansion/utflettercase contains `% tex = xelatex`. This is detected and xelatex is used to successfully compile the testcase to pdf. If no hint is given, previous detection for pdflatex is used.

Suggestion for hinting for maketests

---

lib/LaTeXML/resources/CSS/LaTeXML-navbar-left.css
lib/LaTeXML/resources/CSS/LaTeXML-navbar-right.css
lib/LaTeXML/resources/CSS/LaTeXML.css
tools/xtest

This makes two column layout use CSS flexbox, and adds media query to have the 2 columns unwrap when the screen is too narrow.
Also fixes a couple of minor typos from #1442.
@xworld21 Could you take a look that I've not undone anything important to your work?

CSS tweaks

---

lib/LaTeXML/Package/LaTeX.pool.ltxml
lib/LaTeXML/Package/utf8.def.ltxml

Fixes #1508 
A bit of a "request for comments" PR, since I am unsure what the best general strategy would be for latexml, given how the unicode situation is dramatically different between pdflatex and perl.
First, some good news:
1. The native definitions of `\MakeUppercase` and `\MakeLowercase` seem to work like a charm. I refactored to them to play around, leaving them in for effect.
2. A restricted attempt to use perl's `uc` and `lc` commands for these macros achieves the desired effect for cyrillic -- seemingly without currently known side effects?
Then the tricky bits:
- fontenc itself is a bit of a mixed bag... We are defining only a core set of the cyrillic macros, and indeed another way to get rid of the errors mentioned in the issue is to define the advanced/rarer macros …

Enable fontenc-aware lower/uppercase for cyrillic

---

lib/LaTeXML/Package/eTeX.pool.ltxml
t/expansion/multi_escaped_param.xml
tools/maketests

This is a more accurate implementation of `\scantokens`, which sets up a mouth for the imaginary file, but defers reading from it, so that expansion/digestion interleaving works as expected.
To make things interesting, it seems to introduce an extra space (as a newline in LaTeXML's case) in the `multi-escaped-param` test. But if you examine the pdf carefully, I think you'll find that there are 3, not 2, spaces before the result.
And even more interesting, `tools/maketests` formerly discarded blank lines, which gave different test results between `make test` and `maketests`.
What fun! Should be all better now.
Fixes #1515

Fix scantokens

---

lib/LaTeXML/Package/latexml.sty.ltxml
lib/LaTeXML/texmf/latexml.sty

This adds a boolean package option to `latexml.sty` to control the automatic guessing of the headers in tabulars; `guesstabularheaders` turns it on, `noguesstabularheaders` turns it off. As usual can be controlled from the source with
```
\usepackage[noguesstabularheaders]{latexml}
```
or `--preload=[noguesstabularheaders]{latexml}` on the commandline.
Fixes #1512
The default is still to guess. Many of the testcases have tables with guessed headers, so to change the default to no, we either have to remake many test cases, or find a clean way to change the option within the testcases.

Add package keyword option (no)guesstabularheaders

---

lib/LaTeXML/Package/LaTeX.pool.ltxml
lib/LaTeXML/resources/XSLT/LaTeXML-tei.xsl

As it says; this should make the TEI stylesheet work correctly on tabulars with and with `ltx:thead` and `ltx:tbody` (which are produced either by extra markup, or `GUESS_TABULAR_HEADERS`)
This was discovered on a tangent to #1518

fixup tei stylesheet for tabular with and without thead/tbody

---

lib/LaTeXML/resources/XSLT/LaTeXML-jats.xsl
lib/LaTeXML/resources/XSLT/LaTeXML-tei.xsl

These stylesheets took the expedient of stripping whitespace from all elements, rather than just block ones, which caused empty elements which should have had a space.
Fixes #1521

In JATS, TEI only strip-space selectively

---

lib/LaTeXML/Package/TeX.pool.ltxml
lib/LaTeXML/Package/stmaryrd.sty.ltxml
t/ams/mathtools.xml
t/fonts/stmaryrd.xml

This PR uses the correct (I think) Unicode for various `\bigXXX` symbols in TeX and also a few in stmaryrd.  It also treats those in the latter style as having movable scripts.
I couldn't find large size Unicode for `\bigbox, \bigcurlywedge,\bigcurlyvee,\bigtriangledown,\bigtriangleup`, so I kept the Big sizing.  If you find the right codes, let me know! (Also the rendering for `\bigparallel` is dubious, but the codepoint seems to be the correct one).
Fixes #1502
Thanks, @xworld21

Fix bigop sizes

---

lib/LaTeXML/Core/Alignment.pm
lib/LaTeXML/Core/Definition.pm
lib/LaTeXML/Core/Definition/Conditional.pm
lib/LaTeXML/Core/Definition/Constructor.pm
lib/LaTeXML/Core/Definition/Expandable.pm
lib/LaTeXML/Core/Definition/Primitive.pm
lib/LaTeXML/Core/Definition/Register.pm
lib/LaTeXML/Core/Gullet.pm
lib/LaTeXML/Core/KeyVals.pm
lib/LaTeXML/Core/Parameter.pm
lib/LaTeXML/Core/Parameters.pm
lib/LaTeXML/Core/State.pm
lib/LaTeXML/Core/Stomach.pm
lib/LaTeXML/Core/Tokens.pm
lib/LaTeXML/Package.pm
lib/LaTeXML/Package/LaTeX.pool.ltxml
lib/LaTeXML/Package/TeX.pool.ltxml
lib/LaTeXML/Package/amsgen.sty.ltxml
lib/LaTeXML/Package/pdfTeX.pool.ltxml

Yep, misspelled. A series of smallish, but cumulative, optimizations. The main strategy is avoiding layers of subroutine calls, using operations that are faster in Perl, and open-coding accessors where not too offensive. Generally focussed on speeding up the expl3 test case, which appears to be 20% faster (tikz samples about 10%, make test around 7-8%)

Expl3 optimizatoin

---

doc/manual/manual.tex

As noted in #1527 there is a typo in the documentation. This PR fixes the typo. 
Thanks @samzhang111 for spotting it.

Fix typo in manual (Closes #1527)

---

lib/LaTeXML/resources/XSLT/LaTeXML-jats.xsl
lib/LaTeXML/resources/XSLT/LaTeXML-tei.xsl
t/daemon/formats/jats.xml
t/daemon/formats/tei.xml

Quite by accident, I discovered some oddities in these stylesheets and that they were not reusing the base LaTeXML stylesheet modules as much as I had expected. Among other things that made it quite easy to use the `mml` namespace prefix (even if it annoys :> ). And also discovered that instances `ltx:MathFork` (used for aligned sets of equations) was getting *all* math branches copied, resulting in redundant math.  Along with other general stylesheet formatting, namespace cleanup.
Fixes #1499.
Please @rgieseke, @xworld21 and any other JATS or TEI users, please take a look that I haven't inadvertently broken anything.

JATS, TEI stylesheet cleanup

---

lib/LaTeXML/Package/todonotes.sty.ltxml

Spotted a weird Fatal error on arxiv related to `todototoc`:
```
Fatal:misdefined:odototoc Unrecognized parameter type in "odototoc"
at todonotes.sty.ltxml; line 37
```
And indeed there was a minor typo to fix. While there I opened [the docs](http://tug.ctan.org/macros/latex/contrib/todonotes/todonotes.pdf) and smoothed in a couple of other bits. All in all, an elbow grease PR.

minor macro patches for todonotes.sty

---

MANIFEST
lib/LaTeXML/Package/ifplatform.sty.ltxml

This PR adds a binding for the 'ifplatform.sty' package, emulating the package as closely as possible.
This commit does not add any tests for the package, because the output is operating system dependent. As such it would likely fail for a large part of users of LaTeXML. 
Fixes #1531.

Add binding for 'ifplatform.sty'

---

bin/latexmlc
lib/LaTeXML/Package/LaTeX.pool.ltxml

An impressive book-sized manuscript made the rounds recently, at [arXiv:2105.10386](https://arxiv.org/abs/2105.10386), totaling 419 PDF pages.
With this PR, the conversion with latexml parses over 16,000 math expressions, makes an index of 500 entries and finishes in a total of 12 minutes, without errors. It has 415 warnings, mostly due to math parsing.
The run seems to do quite well with the custom `.sty` file of the book, OmniBus recovers well the custom `.cls` and loads the dependencies. Impressively latexml does quite well with raw interpretation of three unsual styles: `nomencl.sty`, `combelow.sty` and `letltxmacro.sty`, all of which are loaded raw.
The book can be converted into a 8.5MB-sized ePub file, which I'll attach here for a preview until we merged. Also, here's a screenshot …

[arXiv patch] more internal \input macros, typo and lighter font Info logs

---

lib/LaTeXML/Package/LaTeX.pool.ltxml

Debugging [arXiv:1606.02688](https://corpora.mathweb.org/preview/arxmliv/tex%5Fto%5Fhtml/1606.02688), I noticed that `{titlepage}` currently gives up on collecting any metadata, until better recognition algorithms come to mind.
However, in that arXiv article, it gave up a bit prematurely, as the metadata is provided properly and a `\maketitle` macro is explicitly used within the titlepage. So I added a check that upon encountering `\maketitle` will unwind/unwrap the `ltx:titlepage` element and revert back to the default handling with healthy metadata.
Fixes that article, and may be an easy upgrade? I am separately looking into improving the `\maketitle` machinery to be closer to the latex.ltx implementation for issue #1536 , but that is a lot more far-reaching and involved. This PR …

Recognize \maketitle in titlepage

---

lib/LaTeXML/Core/Stomach.pm

Another angle of attack for reducing the Fatal errors in arXiv and other yet-to-be-remediated long documents.
Currently, latexml will raise an error for every unexpected alignment token it encounters outside of some tabular environment. So in a document with e.g. `xymatrix` today, after 100 cells, the processing will emit 100 errors, hence a Fatal error and halt.
A random document I drew from cortex is [math0002083](https://corpora.mathweb.org/preview/arxmliv/tex%5Fto%5Fhtml/math0002083), encounters 40 errors of this nature. With this PR, that document only encounters 9 errors, 7 of which for alignments - and indeed we can count exactly one such error per used xymatrix environment.
The trick I found was to let the alignment to `\relax` for just the **current local TeX scope**, which …

Softer alignment errors

---

lib/LaTeXML/Package.pm
lib/LaTeXML/Package/expl3.sty.ltxml

Fixes #1454 .
Now that I updated my texlive and can reproduce locally, I traced this issue to one of my older patches in `Package::InputDefinitions` which hardcoded a little too closely the LaTeX 2 behavior of a standalone `Digest(T_CS('\@pushfilename'))` while loading e.g. a new .sty package with definitions.
In LaTeX 3 that internal macro gets extended to do more token interplay with the rest of the input stream, so my standalone `Digest` call creates the errors reported in the issue - and I could reproduce those clearly.
However, the expl3 metadata fishing is a bit of a hack in all honesty: It relies on the exact placement of `\@pushfilename` in the original `latex.ltx`. You move that macro e.g. a line or two down, or worse - change the definition pattern on the line after - and it …

Patch expl3.sty regression on texlive 2020

---

MANIFEST
lib/LaTeXML/Common/Model.pm
lib/LaTeXML/Common/XML.pm
lib/LaTeXML/Core/Alignment.pm
lib/LaTeXML/Core/Gullet.pm
lib/LaTeXML/Core/Parameters.pm
lib/LaTeXML/Package/OmniBus.cls.ltxml
lib/LaTeXML/Package/amsmath.sty.ltxml
lib/LaTeXML/Package/listings.sty.ltxml
lib/LaTeXML/Package/pgfmath.code.tex.ltxml
lib/LaTeXML/Package/psfrag.sty.ltxml
lib/LaTeXML/Package/siunitx.sty.ltxml
lib/LaTeXML/Package/svg.sty.ltxml
lib/LaTeXML/Package/xfrac.sty.ltxml
lib/LaTeXML/Post/CrossRef.pm
lib/LaTeXML/Util/WWW.pm

This cleans up a handfull of random fatals that were easy to isolate & fix with the generally cleaned up state of things.
Most significant may be a stubby binding for `psfrag`. It doesn't actually add the fragments, but creates footnotes to inform of what would have been added to the figures. So an imperfect, but error free, result.  Could be non-trivial move of error to warning, since psfrag was used a lot in older arXiv papers.
Still WiP, since I may sneak in a few other minor cleanups.

Less arxiv fatals

---

MANIFEST
lib/LaTeXML/Package/prettyref.sty.ltxml

I saw prettyref on [this list](https://github.com/brucemiller/LaTeXML/wiki/Porting-LaTeX-packages-for-LaTeXML) and I know it works with `--includestyles` because I use it regularly, so this is an easy one.
A small example:
```latex
\usepackage{amsthm}
\usepackage{prettyref}
\newtheorem{thm}{Theorem}
\newtheorem{prop}[thm]{Proposition}
\newrefformat{prop}{Proposition~\ref{#1}}
% the thm format is builtin
\begin{thm}
\label{thm:theorem}
A theorem.
\end{thm}
\begin{prop}
\label{prop:proposition}
A proposition.
\end{prop}
References: \prettyref{thm:theorem}, \prettyref{prop:proposition}.
\end{document}
```

Add binding for 'prettyref.sty'

---

lib/LaTeXML/resources/javascript/LaTeXML-maybeMathjax.js

Something I spotted in quick PR by @dginev: MathJax version 3 is being called with the options meant for version 2 (see [Loading MathJax](http://docs.mathjax.org/en/latest/web/configuration.html#loading-mathjax) versus the old [Combined Configurations](https://docs.mathjax.org/en/v2.7-latest/config-files.html#combined-configurations)).
I believe the url below is the intented one (MathML input, CommonHTML output; there is [no "or MathML" anymore](http://docs.mathjax.org/en/latest/web/components/output.html#output-chtml)).

update MathJax url to load mml-chtml component only

---

MANIFEST
lib/LaTeXML/Package/actuarialangle.sty.ltxml

As per subject, this is a small binding for [actuarialangle](https://mirrors.ctan.org/macros/latex/contrib/actuarialangle/actuarialangle.pdf). It translates `\actuarialangle` to the corresponding MathML `menclose` and `\overanglebracket` to its Unicode equivalent.
The output quality is hit and miss, unfortunately. Firefox renders the angled bracket properly, but messes up the actuarial angle; MathJax does the opposite.
Edit: here is a small example
```latex
\usepackage[thinspace]{actuarialangle}
\[ \actuarialangle{n} \quad a_{\actuarialangle{n}} \]
\[ \angl{ab} \quad \angln \quad \anglr \quad \anglk \]
\[ \overanglebracket{abcde} \quad \group{xy} \quad A_{\group{xy}:\angln} \]
\end{document}
```
which `pdflatex` renders as

Add binding for 'actuarialangle.sty'

---

lib/LaTeXML/Util/Test.pm
t/931_epub.t

Reason: most tests above 90 fail when a parent folder contains a space, or if a required Perl module has a space in its path (noticed on Windows, where it's much more likely to actually happen). ~~I have added double quotes around all paths.~~
Edit: I replaced the `$invocation` strings with arrays of strings, each representing the argument in its plain form (unquoted, unescaped). I think this is the most correct solution.
If you like this approach, I can grep for all the other `system()` and backticks and do the same, because e.g. the kpsewhich calls are also giving me problem related to spaces in the arguments.

Invoke commands by passing the arguments in a list of strings

---

lib/LaTeXML/Common/Error.pm

Small update to #1575... I forgot the easy part of the PR, which is to only execute the console changes if `$IS_TERMINAL` is true.

Enable Windows VT100 emulation only if in a terminal

---

lib/LaTeXML/Package.pm
lib/LaTeXML/Package/LaTeX.pool.ltxml
lib/LaTeXML/Package/xparse.sty.ltxml

This PR fixes some regressions (or lags, rather) for TeXLive 2021 (at least, the included tests).
It is an alternative to #1569 that I couldn't flesh out, without trying it out. (Sorry for stealing the glory) After experimentation, I pretty much ended up following @dginev's idea of recording the files that we are willing to interpret (so they don't hit the binding fallback).  [Not yet a full API for this yet, but could evolve into something where we'd simply have a list of interpretable files, rather than trivial bindings]
Hopefully this will resolve #1566 and #1565 ? @xworld21, @flyn-org could you check?

Texlive 2021

---

Makefile.PL

Another Windows paper cut: the MathGrammar compiles properly, but the `-e "MathGrammar.pm";` test fails because the perl code is passed in single quotes, and Windows does not do single quotes.

Use double quotes when compiling MathGrammar

---

lib/LaTeXML/Core/Gullet.pm

The previous setting of autoclose when flushing seems no-longer necessary (if ever? it would seem to be tested by `t/expansion/endinput`, which still passes) and occasionally causes mouths to be closed too early; chaos ensues (esp. pgfplots).

Don't set autclose when flushing an input mouth

---

lib/LaTeXML/Core/Token.pm
lib/LaTeXML/Package/diagbox.sty.ltxml

Stumbled on a curious fatal error in the [sandbox reports](https://corpora.mathweb.org/corpus/sandbox%5Farxiv%5F1905/tex%5Fto%5Fhtml/fatal/perl/die?all=false), namely:
> Can't locate object method "getCatcode" via package "LaTeXML::Core::Tokens" at /usr/local/share/perl/5.30.0/LaTeXML/Core/Token.pm line 146
A quick check reveals a number of `reversion` attributes of `DefParameterType` declarations in TeX.pool which return a `Tokens` object rather than a perl list of `Token` objects. For now I made `UnTeX` more robust, where it will actively expect `Tokens` objects and unlist them.
In a hypothetical rewrite, I see I have made the choice of standardizing DefParameterType reversions to always return a single `Tokens` object. Which is almost identical to a list of individual Token objects, …

Guard for Tokens in UnTeX

---

lib/LaTeXML/Common/Model/DTD.pm

Fix #1571.
After reading more than should have been necessary, I am convinced that this approach (reading the file into a string, then call `parse_string`) works correctly re DTD encoding. The DTD will not know its `public_id` but it hardly seems relevant.
The only other approach is to turn `$dtdfile` into a `file://` URI, but that would be more code (or a `URI::file` dependency).

Read $dtdfile into a string before parsing

---

lib/LaTeXML/Common/Locator.pm

Try not to treat a Windows pathname `C:\foobar` as a url.
Fixes #1567 (hopefully)

more portable test for urls (esp. Windows)

---

Makefile.PL
lib/LaTeXML/Version.in

Another Windows motivated PR. The `update_revision` part of the Makefile essentially expects a POSIX system, but we can do without. This is a bit delicate, I think I have tested it properly, but please double check.
The changes:
1. Only check that `.git` exists (sometimes it is a file, e.g. when using submodules - not Windows related, but relevant);
2. Replace backticks with `$(shell ...)`, and fiddle with the quotes, again because Windows does not understand them;
3. Replace `test` with a tiny perl script, because `test` is not available from Windows.

Portable update_revision

---

lib/LaTeXML/Package/amstext.sty.ltxml
lib/LaTeXML/Package/natbib.sty.ltxml
lib/LaTeXML/Package/revtex4_support.sty.ltxml

Apparently seeing an arXiv PR gets one curious to also make another small arXiv PR...
This patch upgrades `arXiv:cond-mat/0003435` from a timeout Fatal to a Warning status (due to math parsing).
* lock more natbib macros to avoid redefinitions in arXiv that lead to badly broken misinterpretation with infinite loops in `\bibitem`.
* Also make sure we have enough locked to keep the citation filling operational.
* add some minor internal revtex macros to silence some otherwise unimportant errors.
Hopefully no unintended consequences... 
There is a general pattern I've spotted, which is that quite often we don't want to allow redefining macros which have a constructor in their expansion, especially for core features of LaTeX, but maybe in general. OR, vice-versa, only allow a redefinition if …

Timeout-related arXiv patches

---

t/931_epub.t

Apparently, Windows is more picky with `open3`: if you don't consume the output, the command hangs and `waitpid` waits forever. So consuming the output and calling `close` is the way to go, rather than `waitpid`.
This is the last Windows fix!

Consume output of latexmlc invocation and close pipe in EPUB test

---

lib/LaTeXML/Util/Pathname.pm
lib/LaTeXML/Util/Test.pm

Another fix about passing the arguments in a list so that they are escaped correctly. With this, Windows passes all tests except for `931_epub.t`, so it's very close to working out of the box!
On the other hand, this is only a stopgap measure because Perl may still mangle the arguments under certain conditions. My suggestion would be to add a small `LaTeXML::Util::Run` module with say `run` and `capture` in order to deal with this properly.
In the meanwhile, this PR should cover like 99.9% of the situations correctly.

Safe(r) backticks

---

lib/LaTeXML/Core/Stomach.pm
lib/LaTeXML/Package/TeX.pool.ltxml
lib/LaTeXML/Package/hyperref.sty.ltxml

Rescues a short undergrad thesis posted on arXiv from a Fatal to an Error. In particular, [1905.00636](https://arxiv.org/abs/1905.00636).
The main challenge was a custom tabular environment `{game}` defined in their local `sgamevar.sty` style file. I don't think we're quite there with interpreting custom aligned environments, but we ought to be good enough to not fatal for a mid-sized document.
I extended the same trick I introduced for `&`, also for `\omit`, `\noalign` and `\span`, and added a boxing group when encountering these via `->bgroup`. That reduced the document down to 33 errors, and produced an HTML with basically all content present, save for the custom tables.
A minor bit that I also spotted in the doc was that `[colorlinks]` loads `color.sty` in hyperref, so that the …

arXiv patch: custom tabulars emit less errors

---

doc/manual/manual.tex
doc/site/index.tex
doc/sty/latexmlman.sty
doc/sty/latexmlman.sty.ltxml

This PR contains three small fixes for the website and manual that I discovered by running a linkchecker over the website.
- Fixing an `\href{}` without a URL in it to ImageMagick (51d47549db6716f3f39485ef3058a0429116c50c)
- Fixing a broken link inside the Archlinux installation instructions (fb8f096aa0e14b9db1ea6d8c74b9dccd13ffcc9d)
- Exchanging `http://` links with `https://` because it's 2021 and we should be using https where supported (
b34056247c84827ee4022481f91cc3692dca7286)

Minor website fixes

---

lib/LaTeXML/Util/Pathname.pm

These should clearly never happen, but I saw a broken tikz case where they did. The terminal logs:
```
Missing argument. Try `kpsewhich --help' for more information.
Missing argument. Try `kpsewhich --help' for more information.
Missing argument. Try `kpsewhich --help' for more information.
Missing argument. Try `kpsewhich --help' for more information.
Missing argument. Try `kpsewhich --help' for more information.
Missing argument. Try `kpsewhich --help' for more information.
Missing argument. Try `kpsewhich --help' for more information.
Missing argument. Try `kpsewhich --help' for more information.
```
And I think I've seen these blocks of STDERR prints fly by also in the arXiv conversion logs.
The immediate fix is a one-liner, just don't do anything in `pathname_kpsewhich` when called …

avoid empty kpsewhich calls

---

lib/LaTeXML/resources/XSLT/LaTeXML-structure-xhtml.xsl

Indeed, the redundant dates wasn't intentional.  Your approach is basically correct, but I think (hope) this test is a more general way of excluding the dates.
fixes #1478

Avoid adding date to split-off pages

---

lib/LaTeXML/resources/XSLT/LaTeXML-structure-xhtml.xsl

One character patch adding one missing space in a stylesheet between the colon and the following keywords. I grepped the other `<xsl:text>:` and this seems to be the only offender re spaces.

add space before keywords

---

lib/LaTeXML/Package/LaTeX.pool.ltxml

I was seeing some rather broken tokenization examples in `\mathrm` that lead to bad rendering in HTML. To reproduce an example, you can try:
```tex
\usepackage{fouriernc}
$\mathrm{Tribes}_{w,s} $
\end{document}
```
converted with `--includestyles`. The `fouriernc.sty` file was being loaded in an arXiv job as it was requested from within a different `.sty` file, and thus being allowed in raw. Turns out, that package has the definition:
```tex
\DeclareMathAlphabet{\mathrm}{T1}{fnc}{m}{n}
```
which derailed latexml's tokenization so that each letter in the example became its own `XMTok`. I am not sure what the ultimately best upgrade is in this regard, but for now we can guard existing macros with a simple `IsDefined` check, hence this PR.
Edit: to be …

Guard existing macros from \DeclareMathAlphabet

---

lib/LaTeXML/resources/XSLT/LaTeXML-structure-xhtml.xsl

More arXiv pain (e.g. [here](https://corpora.mathweb.org/preview/arxmliv/tex%5Fto%5Fhtml/math-ph0001001) ), this time continuing the battle with empty `()` parens for space-only dates.
E.g. `\date{ }` or `\date{  }` etc, still produced empty parentheses upon post-processing to HTML. `normalize-whitespace()` gets rid of such cases.

No parens for \date with spaces

---

lib/LaTeXML/Package/TeX.pool.ltxml

Motivating example: the two `[0.4cm]` leftovers in the rendering of [hep-ph0001194](https://corpora.mathweb.org/preview/arxmliv/tex%5Fto%5Fhtml/hep-ph0001194).
Some title pages on arXiv are held in a `{center}` environment, and the spacing information for `\\[0.4cm]` was remaining dropped as content, due to `\inner@par` not being prepared for such complications.
I simply added the arguments in without using them, which looks much better, and could be improved further if one gets very picky one day.

Accept and ignore spacing args in \inner@par

---

bin/latexmlmath
bin/latexmlpost

Fixes #1417 
This PR adds exit codes to the 'latexmlpost' and 'latexmlmath' executables, as suggested in https://github.com/brucemiller/LaTeXML/issues/1417#issuecomment-751760914.
The first commit uses a patch suggested by @epifanovsky.

Add Exit Codes to 'latexmlpost' and 'latexmlmath' (Fixes #1417)

---

lib/LaTeXML/Common/Error.pm
lib/LaTeXML/Package/AmSTeX.pool.ltxml
lib/LaTeXML/Package/LaTeX.pool.ltxml
lib/LaTeXML/Package/TeX.pool.ltxml
lib/LaTeXML/Package/amsbook.cls.ltxml
lib/LaTeXML/Package/amsthm.sty.ltxml
lib/LaTeXML/Package/etoolbox.sty.ltxml
lib/LaTeXML/Package/longtable.sty.ltxml
lib/LaTeXML/Package/twoopt.sty.ltxml
lib/LaTeXML/Package/xargs.sty.ltxml

A handful of smaller fixes during my CSS prototyping sessions with two books and ~10 articles from the arXiv corpus:
- an experiment supporting the "psfile" key in `\special` to get graphics into some of the older docs
- [astro-ph0001188](https://corpora.mathweb.org/corpus/arxmliv/tex%5Fto%5Fhtml/no_problem) is one example
- slightly cleaner warning text for generic "perl warning" and "redefinition" messages
- using `$stomach->digest` instead of `Digest` in a couple of obvious places
- `\inputlineno` register and using it via the `\on@line` internal, 
- some `\listi` internals for amsbook
- a stub for `\setlongtables` in etoolbox
- some internal skips for amsthm
There are still a couple of errors in the big books I was testing with, but already some improvement. The heavier lifting in …

arxiv fixes from css sprint

---

lib/LaTeXML/Package.pm
lib/LaTeXML/Package/LaTeX.pool.ltxml
t/structure/article.xml

Searching for more trade-offs, this PR introduces:
* lock \maketitle;
* sanitize ltx:personname for punctuation abuse
* allow optional arg for \author and lock
* keep locked definitions locked if they get extended (via bindings) by the `AddToMacro` utility 
---
1. Locking \maketitle avoids doubling the frontmatter when a custom `.sty` file redefines it, as in [cs0010030](https://corpora.mathweb.org/preview/arxmliv/tex%5Fto%5Fhtml/cs0010030)
2. Similarly, locking `\author` avoids issues where an otherwise correct author entry does not make it to the frontmatter infrastructure. But, at least one redefinition introduces an optional argument (example I saw: adds a note marker). So I made provisions to accept and drop that.
3. Lastly, some papers redefining `\author` abused it somewhat, where …

[arXiv] more frontmatter guards

---

lib/LaTeXML/resources/XSLT/LaTeXML-structure-xhtml.xsl

Fixes #1607
One can play around with the issue by defining:
```tex
\def\datename{\textit{Date}:}
```
with and without a colon. I think carrying that as-is to the XML `ltx:date` element is correct, and then we can make a provision for it in the XSLT with a simple if. Since I don't think we support using colons inside the date itself, a simple conditional can do the job.

no XSLT date delimiter

---

lib/LaTeXML/Package/TeX.pool.ltxml

I really want to move on from styling but way too frequently previewing a new arXiv article reveals a brand new edge case... 
```tex
\documentclass{aa}
\title{title}
\keywords{planets and satellites: formation -- methods: N-body
simulations -- astrobiology}
\section{Introduction.}
The core accretion hypothesis of giant planet formation postulates
that giant planets originate in a cool location in a protoplanetary...
\end{document}
```
Upon converting that, one sees the text of the introduction is bold, and in the case of the full article - the entire document gets bold.
Turns out the definition in `aa_support.sty.ltxml` runs into trouble:
```perl
DefMacroI('\keywordname', undef, '\sffamily\bfseries Key Words.');
```
where the font switches escape out of the \keywords …

[arXiv] sandbox frontmatter expansions

---

lib/LaTeXML/Package/TeX.pool.ltxml

Fixes #1618 
After being fooled around by Perl's object orientation and error reporting combo, I finally figured out there was a Glue serialized as a string and then recast as a Dimension which caused the warning.
1. Simply put, the width in an XMHint can be a Glue, so build that preemptively.
2. I also spotted that TeX.pool has the same registers defined twice, so compressed that.
3. Also added some extra spaces between the glue keywords in some skip definitions for extra cleanliness

widths in math cleanup should be Glue-capable

---

lib/LaTeXML/Package/LaTeX.pool.ltxml
lib/LaTeXML/Package/TeX.pool.ltxml

Better technical implementation for #1621 , as suggested by Bruce.
When the frontmatter of a document contains only a single `ltx:abstract` at the point of frontmatter insertion, do not perform it. Instead, defer inserting the abstract until the exact location where the abstract was originally digested.
I can also confirm this successfully corrects the test article in question (hep-ph0001194).
After merging here, I think we're ready for a rerun of the arXiv sandboxes, which I can start right away.

[arXiv] 2nd try, recover abstract order in raw frontmatter uses

---

lib/LaTeXML/Package/pgfplots.sty.ltxml
lib/LaTeXML/Package/pgfplotstable.sty.ltxml

Avoid warnings by setting pgfplots to its most recent version, rather than a specific one. pgfplotstable doesn't need to set the version, since it loads pgfplots.

Set pgfplots version to the most recent version;

---

lib/LaTeXML/Post/Manifest/Epub.pm

This should be my last last-minute non-XSLT PR about EPUB3.
Should the user ever provide their own `nav.xhtml` or `content.opf` (by means of `RequireResource()`, so definitely not by accident), latexmlc should not overwrite them. So I have added two `if (-f ...)`'s around the relevant code and an Info message.
I do plan to use this to replace the default `nav.xhtml`, which is almost unusable with large documents. Once I figure out how to generate a good `nav` from within latexmlc (which may need a small refactoring), I'll send a PR, I promise!

epub: do not overwrite files supplied by the user

---

lib/LaTeXML/Post/Manifest/Epub.pm

As promised, a quick improvement on #1635. In short:
- recognise all 'core media types' listed in the EPUB3.2 spec, not just the arbitrary css/png/svg (incidentally, the `.css` match was still case-sensitive);
- be excessively accurate with `@id`, down to encoding invalid characters as `-xNNN-` so that there can't be collisions or invalid id's, ever ~; files starting with a digit would have caused problems so we might as well do the right thing™; the regex is almost a copy and paste from the XML 1.0 spec (collision is still a risk, but a small one, and easy to fix on the user side)~
- use `URI::file` to make sure the `href`'s are actual URLs; things would have probably exploded on Windows
- fix a tiny bug that causes invalid output when using `--splitnaming=*relative`
- do not include the …

epub: allow all core media types; safer ids; portable href's

---

lib/LaTeXML/Core/Document.pm

Make sure closeText runs ligatures when using setNode to move insertion point. This can happen when a floating insertion (like `\label` or `\index`) appears within text, which causes the insertion point to move,  but previously the ligatures didn't get applied to the preceding text.
Creating a PR just so @dginev can see it, but since I need it, I'm going to immediately merge.

Fix ligatures

---

lib/LaTeXML/Package/LaTeX.pool.ltxml

Minor PR, catching another peculiar generic warning to clean up our messages. It improves from say:
```
Warning:latex:\space\space\space  LaTeX Warning: Citation `kumar2020marketplace' on page 0 undefined at main.tex; line 115 col 112
```
to the slightly more manageable for the CorTeX reports:
```
Warning:latex:\GenericWarning LaTeX Warning: Citation `kumar2020marketplace' on page 0 undefined at main.tex; line 115 col 112
```

Expect the \space\space\space variant of generic warnings

---

lib/LaTeXML.pm
lib/LaTeXML/Post/LaTeXImages.pm

Fixes #1669 
From what I understood while reading the File::Temp documentation, I didnt see how the downgrade to medium could cause any immediate security issues when using latexml.
So if we can avoid unnecessary test failures (and likely usability issues on some server-like deployments), might as well.

Downgrade to medium security of File::Temp

---

lib/LaTeXML/Package/deluxetable.sty.ltxml

Trying to get just a bit closer to the raw [deluxetable.sty](https://fits.gsfc.nasa.gov/standard30/deluxetable.sty) so that notes work correctly when casually deposited before `\enddata`.
An example affected source from arXiv is [astro-ph/0001016](https://ar5iv.org/html/astro-ph/0001016), which has the misfortune of the note getting deposited in a table cell:
By accumulating the notes in `\tblnote@list` and then depositing them at `\end{deluxetable}` via `\spew@tblnotes`, we are guaranteed to get the timing right - at least as right as the original sty file.
This PR upgrades the example in question to:
Caveat 1: both screenshots use my arxmliv.css experiment, rather than the default latexml css.
Caveat 2: I haven't really tested this PR extensively, wanted to see if there is obvious …

Better timing for deluxetable.sty notes

---

lib/LaTeXML/Package/LaTeX.pool.ltxml

Minor PR (I hope).
An arXiv paper relied directly on `\@footnotetext` in a custom footnote definition. Which we can support just as we do `\footnotetext`, I think.
At least that paper's footnote looked reasonable with this PR.
Edit: FWIW, 0.14% of arXiv articles had this as an undefined macro, so at least somewhat tangible benefit in merging.

add \@footnotetext for arxiv:1807.00181

---

lib/LaTeXML/Package/longtable.sty.ltxml
lib/LaTeXML/Package/tabulary.sty.ltxml
lib/LaTeXML/Package/varioref.sty.ltxml

This is an independent PR from me randomly checking a Fatal-error conversion from arXiv, which had an easy patch. The PR upgrades to a Warning status, where one of the remaining issues is my minimal example in #1703 
So, the main problems encountered here were due to:
* capitalization typo in some longtable registers, and adding some extras
* locking the \tabulary definition, as redefinitions using the .sty internals lead to unpredictable errors+loops, which lead too 100+ error fatals.
* locking the \vref and related macro definitions in varioref.sty.ltxml, since modifying them using the internal .sty code also leads to unpredictable breakages.
That's all! The resulting HTML is very high quality from what I could tell, again with the notable exception of the \label issue in #1703 .

Table and ref fixes for arxiv:1804.11028

---

MANIFEST
lib/LaTeXML/Package/babel_support.sty.ltxml
lib/LaTeXML/Package/txtbabel.def.ltxml

Fixes #1715 .
Simply put, in texlive 2021, our babel tests end up loading `txtbabel.def` instead of `babel.def`, and thus never load the binding upgrades located in `babel.def.ltxml`.
As one simple patch, I factored those out in a new `babel_support.sty.ltxml` (or should it be `.def.ltxml`?) and tests pass again on texlive 2021.
Let's see if this PR passes the Miktex CI again...

Patch babel for texlive 2021

---

lib/LaTeXML/Package/graphics.sty.ltxml

Minor, but annoying in the arXiv previews - articles that used the `\graphicspath` macro were [not picking up](https://ar5iv.org/html/1804.11028) their images, as the source directory wasn't getting used (and the ZIP inputs change it).
If one wants to reproduce the issue:
```
latexmlc 1804.11028.zip --dest=test.html
```
Once the source directory is properly used, it gets propagated to post-processing via the usual path and the HTML has images again, even in a zip-to-zip conversion.

patch \graphicspath for ZIP inputs

---

lib/LaTeXML/Post.pm
lib/LaTeXML/Post/CrossRef.pm
lib/LaTeXML/Post/LaTeXImages.pm
lib/LaTeXML/Post/XSLT.pm
lib/LaTeXML/Util/Pathname.pm

Yet another Windows problem. Some paths need to be converted to URLs, or Windows will end up with lots of `%5C` instead of slashes. This PR seems to fix:
- images
- math images
- resources in subfolders
- `--splitnaming=*relative`
If you know of any other path that is being shoved into an attribute, can you please check and add `pathname_to_url`? I am not sure I fixed all of them.
~PS: I took the opportunity to replace some `URI::file->new` with `pathname_to_url` since it does the same job.~ Edit: with apologies for the forced pushes, I realised that `URI::file` and `pathname_to_url` are probably not equivalent, as the latter does not encode the string.

convert paths to urls

---

lib/LaTeXML/MathParser.pm

Fixes #1465 .
Addresses the two easy+obvious cases in the issue, deferring more advanced problems (long annotations, color lexemes) for 2022.
This should be all that's needed for the arXMLiv 2021 rerun, lexeme-wise.

Lexeme fixes from arXMLiv 2020

---

lib/LaTeXML/Core/Gullet.pm
lib/LaTeXML/Core/MuDimension.pm
lib/LaTeXML/Package/hyperref.sty.ltxml
lib/LaTeXML/Package/latexml.sty.ltxml

I'm anticipating a large wait on timeout jobs in the next arXiv rerun, as we have a large number of first-time converting articles, a new texlive 2021, and a contingent of [previously infinitely-looping jobs](https://corpora.mathweb.org/corpus/arxmliv/tex%5Fto%5Fhtml/fatal/timeout?all=false). I've done a small boost to my available hardware to mitigate, but software guards are a much cheaper solution.
So, to borrow an old TeX idea - token limits.
latexml's Gullet already maintains a very adequate counter in a `{progress}` field. What the PR adds is a keyval option to latexml.sty called `tokenlimit`, and raises a Fatal once the limit is surpassed. By default the current behavior is used, i.e. the limit guard is off/disabled.
So, testing in arXiv, I found that a limit of 100,000,000 (one …

Add "token limit" guard; fix two regressions

---

lib/LaTeXML/Package/IEEEtran.cls.ltxml
lib/LaTeXML/Package/aa_support.sty.ltxml
lib/LaTeXML/Package/amsppt.sty.ltxml
lib/LaTeXML/Package/amsthm.sty.ltxml
lib/LaTeXML/Package/elsart_support.sty.ltxml
lib/LaTeXML/Package/llncs.cls.ltxml
lib/LaTeXML/Package/sv_support.sty.ltxml

As we've known for a while now, we have some arxiv articles that get emulated as "fork bombs" due to some latex macros being instead defined as latexml primitives/constructors. Spotted a really simple one today, which feels too simple to go unfixed:
```tex
\edef\qqed{\qed}
\def\qed{\qqed \medskip}
```
Allocates over 4 GB of RAM in 6 minutes when `\qed` is first invoked in the body of the document and dies through the [out-of-memory guard](https://corpora.mathweb.org/corpus/arxmliv/tex%5Fto%5Fhtml/fatal/cortex/oom?all=false). If `\qed` is always defined as a macro, that entire busy loop can be avoided.
Tested on [arXiv:math/0109221](https://ar5iv.org/html/math/0109221)

\qed needs to be expandable for arXiv

---

lib/LaTeXML/Package.pm
lib/LaTeXML/Package/graphicx.sty.ltxml

Seemingly harmless(?) addition of unwrapping quoted filenames in input directives, such as `\input{"epsf.sty"}`.
Seen in long-tail cases e.g. in the [arxmliv warning report](https://corpora.mathweb.org/corpus/arxmliv/tex%5Fto%5Fhtml/warning/missing%5Ffile?all=false). There's also [a couple of SE comments](https://tex.stackexchange.com/questions/191930/spaces-in-files-names-in-input-or-includegraphics#comment442865_191930) mentioning that as the preferred method when the filename has spaces.

Unwrap quoted filenames in \input

---

MANIFEST
lib/LaTeXML/Common/Object.pm
lib/LaTeXML/Core/Alignment.pm
lib/LaTeXML/Core/Box.pm
lib/LaTeXML/Core/Definition/Conditional.pm
lib/LaTeXML/Core/Gullet.pm
lib/LaTeXML/Core/Whatsit.pm
lib/LaTeXML/MathParser.pm
lib/LaTeXML/Package/LaTeX.pool.ltxml
lib/LaTeXML/Package/TeX.pool.ltxml
lib/LaTeXML/Package/amsmath.sty.ltxml
lib/LaTeXML/Package/icml_support.sty.ltxml
lib/LaTeXML/Package/latexml.sty.ltxml
lib/LaTeXML/Package/subeqn.sty.ltxml

I combined a few diverse bits in what is hopefully my last "tour of the territory" PR for arXiv before we start the big run.
* misc macros added: `\vsplit`, `\icmladdress`, `\@killglue`
* added a small binding for subeqn.sty
* locked the math font directives such as `\mathbf`
* silenced a couple of cosmetic perl "undef value" warnings from recent commits
* new guards following `tokenlimit` from #1736 - `iflimit` and `absorblimit`, which allow to catch some out-of-memory errors early, as well as reduce timeouts in those two code paths down to ~5 minutes.
Guard values that I've used that get the large books to pass:
* tokenlimit: `99,999,999`
* iflimit: `199,999`
* absorblimit: `1,099,999`
* pushbacklimit: `99,999`
The absorb limit value may be a little tight, it is just enough to get the …

New guards: iflimit, absorblimit; subeqn.sty; misc patches

---

lib/LaTeXML/Package/LaTeX.pool.ltxml
lib/LaTeXML/resources/CSS/LaTeXML.css
t/alignment/tabbing.xml

Fixes #1719 
* adding `\par` breaks around {tabbing}
* adding a `ltx_tabbing` class to hook any custom styling downstream of latexml.

add a ltx_tabbing styling hook; \par around {tabbing}

---

MANIFEST
lib/LaTeXML/Package/ijcai.sty.ltxml

The only bit after subfigures that was left to make 2105.04404 render well and error-free. Thought might as well...
Simple new binding for a conference style (and thanks to fallback handling ijcai13.sty to ijcai21.sty)

[minor] New binding for ijcai confs

---

lib/LaTeXML/Package/TeX.pool.ltxml
lib/LaTeXML/Post/Graphics.pm

This PR is meant to be a small stir of a recent hot pot :>
I was debugging [arXiv:hep-ph/0105138](https://ar5iv.org/html/hep-ph/0105138) which is no longer a timeout in the latest master. But, that allowed to notice the images reached HTML rather skewed, with an artificial A4/Letter-sized white frame. In other words, the same problem we started discussing at #1683 
Unsurprisingly, adding the `autocrop => 1` flag to the `.ps` case of Graphics.pm specifically reaches an optimal looking figure, as you can enjoy in this screenshot:
The images in question all come from the `\special` directive which I recently enabled in #1616. In this case the source was:
```tex
\special{psfile=g0.ps   voffset=-200
hoffset=-20  angle=0   vscale=80  hscale=80 }
```
I'm not sure if these options would be useful …

Emulate more psfile options via includegraphics

---

lib/LaTeXML/resources/CSS/LaTeXML.css

Fixes #1720 .
Unsure what other common uses there are of parbox, but since there is a desire to use it outside of a figure context then the flexbox solution (in #1700)  isn't the best fit. Styling its display as inline-block is a good pragmatic fix, to the degree I understand the applications.

inline-block styling for ltx_parbox

---

lib/LaTeXML/Post/Graphics.pm
lib/LaTeXML/Util/Pathname.pm

Debugging with [2105.04404](https://ar5iv.org/html/2105.04404), I noticed an image that was failing to get picked up.
The author wrote:
```tex
\includegraphics[width=0.9\textwidth]{illu_blur_MNIST.pdf}
```
but included the file `illu_blur_mnist.pdf`. Naturally,  pdflatex finds the file despite the discrepancy in case, while latexml didn't - as we're looking for exact matches.
To add a simple and effective patch, I created a fallback sub `pathname_findall_nocase`, which takes the slow route of checking all paths, normalized to lowercase, for the desired one, also normalized to lowercase.
Hopefully this catch improves the visuals for all kinds of arXiv articles that were authored on case-insensitive file systems.

Fallback to case-insensitive path search

---

lib/LaTeXML/Package/mathtools.sty.ltxml
t/ams/mathtools.xml

Fixes #1672 .
It is a partial upgrade (the centering of the vdots is not *yet* supported). The issue description seemed to be happy with that as a first step, so here it is.
Minimal example from the mathtools docs:
```tex
\usepackage{mathtools}
\begin{align*}
a &= b \\
& \vdotswithin{=} \\
& = c \\
\shortvdotswithin{=}
& = d
\end{align*}
\end{document}
```
before:
after:

scaffold of support for \vdotswithin

---

lib/LaTeXML/Common/Font.pm
lib/LaTeXML/Core/Alignment.pm
lib/LaTeXML/Core/Stomach.pm
lib/LaTeXML/Package/LaTeX.pool.ltxml
lib/LaTeXML/Package/TeX.pool.ltxml
lib/LaTeXML/Package/colortbl.sty.ltxml
lib/LaTeXML/Package/xcolor.sty.ltxml
t/alignment/colortbls.xml
t/ams/amsdisplay.xml
t/graphics/xcolors.xml

So, it appears that reversion is getting used for more substantial things than creating tex/content-tex strings for math & images, so we have to be more careful about what disappears and when. Ultimately may need a more fundamental fix, but this works for the most obvious case.
fixes #1703

Make \label not disappear on reversion, except for tex strings

---

lib/LaTeXML/Package/LaTeX.pool.ltxml
lib/LaTeXML/Package/pdfTeX.pool.ltxml
lib/LaTeXML/Package/pdftexcmds.sty.ltxml

First patches for minor errors caught by the sandboxes, due to the upgrade to texlive 2020 in particular. I double-checked the signatures with [lthooks](https://ctan.math.illinois.edu/macros/latex/base/lthooks-doc.pdf)
fixes 2111.00034, and improves the raw interpretation of eso-pic.sty to be trouble-free

Stub in some latex3 hooks used in texlive 2020

---

lib/LaTeXML/Util/Pack.pm

Between fixing the path bug that was failing to find graphics, adding the `magnify=2` visual upgrade and arXiv getting quite bigger in 2021, I've ended up rather low on space on my server machines.
Maybe this small PR could be a big help, opting to deflate all assets, rather than only the main HTML one. I definitely had missed the `.log` files, but even `png` assets see a 1-3% size reduction, depending.

deflate the full ZIP output

---

lib/LaTeXML/Package/OmniBus.cls.ltxml

Spotted an easy macro that adds a literal mark in some newer journal styles, added it to OmniBus. 
This also requires [dedicated css rules](https://github.com/dginev/ar5iv-css/commit/d8e77ba0a0aae8116663fd52a89c4a51e6bd0a6a) for the arxiv preview, which disable the interactivity in these verbatim cases.
[example article](https://ar5iv.org/html/2111.14377)

add \affilnum in OmniBus

---

lib/LaTeXML/Package/authblk.sty.ltxml

An oversight on my part, not realizing the `^` float marker in replacement strings must be in the leading position.
As a result the arXiv rerun has a number of literal `^` chars deposited in the frontmatter of articles using autblk, which will have to be rerun.
[example article](https://ar5iv.org/html/1709.02756)

fix: autblk.sty.ltxml float marker 

---

lib/LaTeXML/Package/latexml.sty.ltxml

New `\lxRequireResource[options]{source}` to require resources, such as javascript, css, potentially others in future.  Typical option `type=text/javascript`, unless it can be inferred from the source extension.
Fixes #1721

new \lxRequireResource

---

lib/LaTeXML/Core/Alignment.pm
lib/LaTeXML/Package/JHEP.cls.ltxml
lib/LaTeXML/Package/LaTeX.pool.ltxml
lib/LaTeXML/Package/aas_support.sty.ltxml
lib/LaTeXML/Package/acmart.cls.ltxml
lib/LaTeXML/Package/algorithm2e.sty.ltxml
lib/LaTeXML/Package/article.cls.ltxml
lib/LaTeXML/Package/book.cls.ltxml
lib/LaTeXML/Package/elsart_support.sty.ltxml
lib/LaTeXML/Package/float.sty.ltxml
lib/LaTeXML/Package/floatfig.sty.ltxml
lib/LaTeXML/Package/floatflt.sty.ltxml
lib/LaTeXML/Package/listings.sty.ltxml
lib/LaTeXML/Package/newfloat.sty.ltxml
lib/LaTeXML/Package/report.cls.ltxml
lib/LaTeXML/Package/rotating.sty.ltxml
lib/LaTeXML/Package/subcaption.sty.ltxml
lib/LaTeXML/Package/subfig.sty.ltxml
lib/LaTeXML/Package/subfigure.sty.ltxml
lib/LaTeXML/Package/subfloat.sty.ltxml
lib/LaTeXML/Package/wrapfig.sty.ltxml
lib/LaTeXML/resources/XSLT/LaTeXML-para-xhtml.xsl
lib/LaTeXML/resources/javascript/LaTeXML-maybeMathjax.js
t/alignment/supertabular.xml
t/alignment/tabularstar.xml
t/ams/mathtools.xml

This PR deals with several issues with the new flex approach to multiple figures/subfigures that turned up with DLMF.
* It adds the bookkeeping to maintain `\columnwidth` (as distinct from `\textwidth`)
* It uses the `\columnwidth` to make decisions about subfigure layout, rather than trying to sniff out an intended size.
* It introduces two helper functions (`beforeFloat` and `afterFloat`) that arrange for the various floats to record the current `\columnwidth` while digesting (since the value at construct-time is no longer the correct one), while distinguishing between single and double column floats.
* It patches the the XSLT to recognize more figure content types (but there is still too much potentially inconsistently duplicated testing in LaTeX.pool and the stylesheets that will …

Column flex fixes

---

lib/LaTeXML/Package/newtxmath.sty.ltxml

Spotted a missing `\binom` for a paper using newtxmath.sty, and subsequently realized the dependencies don't accurately match the ones from the texlive `.sty` file.
So this PR updates them to match - hopefully easy & simple.

Add more dependencies for newtxmath.sty

---

lib/LaTeXML/Post/Graphics.pm

Something I thought we had fixed before, but arXiv is painfully unforgiving of (people's filenames...). Example with a PNG file named `my.1.png`:
```tex
\usepackage{graphicx}
\includegraphics{my.1.png}
\end{document}
```
Apparently this case is saved in the `graphic` attribute as `my.1`, which is then used in post-processing. But that passes through `pathname_split` during `Graphics::findGraphicFile`, mostly to obtain the directory in absolute-pathname cases. And then the `1` from `my.1` gets detached into `$reqtype` and discarded -- mostly since the code didn't expect the custom dotted suffixes.
This patch is _a_ fix, not sure if the best one. Feedback welcome!

Recognize graphic names with type-like suffixes

---

lib/LaTeXML/Post/Graphics.pm

A PR that achieves nothing except making the W3C validator a little happier.
`width` and `height` attributes need to be integers, as can be seen for [cond-mat/0103099](https://ar5iv.org/html/cond-mat/0103099) at [its validator check](https://validator.w3.org/nu/?doc=https%3A%2F%2Far5iv.org%2Fhtml%2Fcond-mat%2F0103099)
Just use the `int()` cast in a the final attribute placement of Graphics.pm, and we seem better? Works for the example article at least.

Ensure integers in width and height attributes

---

MANIFEST
lib/LaTeXML/Package/LaTeX.pool.ltxml
lib/LaTeXML/Package/OmniBus.cls.ltxml
lib/LaTeXML/Package/aa_support.sty.ltxml
lib/LaTeXML/Package/ams_support.sty.ltxml
lib/LaTeXML/Package/amsaddr.sty.ltxml
lib/LaTeXML/Package/doi.sty.ltxml
lib/LaTeXML/Package/graphicx.sty.ltxml
lib/LaTeXML/Package/inst_support.sty.ltxml

I looked into a variety of issues this morning, and rapidly patched a number of very easy missing bits from various report levels. 
Feel free to read through and veto anything that seems too brave - I've left the paper names in the commit messages / code comments. 
Mostly extensions to OmniBus itself, a couple of easy bindings, and some optional arguments to standard macros that help in OmniBus use.
At times I wondered whether I should be writing journal-specific bindings, but the utility of adding constructs such as `{thm}` and `{lem}` to OmniBus seems much higher for arXiv, where all kinds of journals may be rediscovering the same constructs.

Variety patchup from arXiv 2021 holiday run

---

lib/LaTeXML/Package/LaTeX.pool.ltxml
lib/LaTeXML/Package/OmniBus.cls.ltxml
lib/LaTeXML/Package/TeX.pool.ltxml
lib/LaTeXML/Package/aas_support.sty.ltxml
lib/LaTeXML/Package/cleveref.sty.ltxml
lib/LaTeXML/Package/deluxetable.sty.ltxml
lib/LaTeXML/Package/emulateapj.cls.ltxml
lib/LaTeXML/Package/emulateapj.sty.ltxml
lib/LaTeXML/Package/natbib.sty.ltxml
lib/LaTeXML/Package/pgfsys-latexml.def.ltxml
lib/LaTeXML/Package/revtex4_support.sty.ltxml
t/babel/numprints.xml

This PR fixes a variety of problems revealed as Error/Malformed in the recent arXiv run; typically things like `ltx:section` appearing out of place due to mismanagement of lists, itemizations, bibliographies, tables and such.
Still some tempting candidates to look at ...

Arxiv malformed

---

MANIFEST
lib/LaTeXML/Package/LaTeX.pool.ltxml
lib/LaTeXML/Package/amsmath.sty.ltxml
lib/LaTeXML/Package/l3keys2e.sty.ltxml
lib/LaTeXML/Package/listings.sty.ltxml
lib/LaTeXML/Package/multicol.sty.ltxml
lib/LaTeXML/Package/tcolorbox.sty.ltxml

It turns out we can get mostly correct behavior when enabling raw interpretation for tcolorbox.sty. It is a [0.43%](https://corpora.mathweb.org/corpus/arxmliv/tex%5Fto%5Fhtml/warning/missing%5Ffile?all=true) contributor to the total  missing_file entries in arXiv.
I added a few partially related macros and registers, which get [2110.06581](https://ar5iv.org/html/2110.06581) fully passing, as well as most of the official [tcolorbox-example.tex](http://mirrors.ctan.org/macros/latex/contrib/tcolorbox/tcolorbox-example.tex), but with lipsum removed (see #1762 for that piece).
With a little further love and care we may be able to perfectly emulate all pieces of tcolorbox.sty. This PR is already 80-90% of the way there, but I won't have the strength to immediately muscle through the remaining …

Add tcolorbox.sty and l3keys2e.sty

---

lib/LaTeXML/Package.pm
t/002_unit_findfile.t

We discussed this recently in our group meeting, and I claimed fallbacks were implemented - but indeed rather limited in what they did. I spotted a case that could've used a mildly better application of the regexes, and also a handful of simple cases that could be swept in with an easy rule or two.
Here's a minimal example of what the PR could do that couldn't be done before:
```tex
\documentclass{svjour3-id}
\usepackage{my-emulateapj_ed,amsmath-arxiv-v2021,aastex62_rev}
```
induces:
```
Info:fallback:svjour3-id.cls Interpreted 3-id as a versioned package/class name, falling back to generic svjour.cls at test.tex; line 2 col 11
Info:fallback:my-emulateapj_ed.sty Interpreted my-..._ed as a versioned package/class name, falling back to generic emulateapj.sty at test.tex; line 3 col 6 …
```

More rigour in package fallback

---

lib/LaTeXML/Package/LaTeX.pool.ltxml

Looking at recent uses of acl.sty, we have some rather custom tricks, such as:
```tex
\let\endthebibliography=\endlist
```
Which, naturally, causes a latexml error since the opening will not match the close. The beginning is redefined via `\def` in this package, which we succeed in guarding with the macro lock -- but the ending slips through, so we end up mismatching.
Well, it will slip through no more - at least in the cases where it is redefined before `{thebibliography}` begins.

guard \theendbibliography from \let

---

lib/LaTeXML/Package/setspace.sty.ltxml

I kept stumbling on some [new articles](https://ar5iv.org/html/2111.00082) that use \setstretch, so looked into what the issue was.
It seems we had a handful of more stubs to add in the setspace.sty binding. Nothing interesting, another easy PR.

Some additional stubs for setspace.sty

---

lib/LaTeXML/Package/acmart.cls.ltxml

I spotted that 2111.03657 was using an undefined `\toprule` and after digging through the loaded packages traced that to a booktabs.sty dependency of acmart.cls.
Checking the texlive 2021 version of that file on my disk, I spotted a handful of other bindings we have that it is now loading -- hence the PR.
latexmllint also alerted me of a wrongly escaped `\#` and I realized two of the definitions should have been single-quoted.
All in all, another simple&quick PR.

acmart.cls updates

---

lib/LaTeXML/Package/LaTeX.pool.ltxml

One of my fix attempts in the #1766 PR was to avoid spurious errors in `make_message`.
That PR got things right in the cases where the expected macros was used, but not when some alias was `\let` to that macro.
And it turns out csquotes.sty has a regression for us in texlive 2020, where each minimal file just loading that package produces an error.
Cause:
```tex
\let\csq@noline\@gobble
%...
\protected\def\csq@info#1{
%...
\PackageInfo{csquotes}{#1\csq@noline}
%...
\csq@info{Trying to load configuration file 'csquotes.cfg'..}
```
I think ultimately, the only reliable way to pretend we're expanding "fairly" these sandboxed messages is to pad them with two trailing spacing macros. Then reuse the regex cleanup I had added earlier, which erases said trailing macros, to clean up the message. …

pad make_message for csquotes.sty

---

lib/LaTeXML/Package/titling.sty.ltxml

as stated. I spotted some errors in using `\droptitle`, and that led me to port a handful of extra ones.

Additional macros from titling.sty

---

lib/LaTeXML/Package/LaTeX.pool.ltxml

We load `glossaries.sty` raw from the ltxml binding, and in the 2021 texlive that raw file uses:
```tex
\DeclareRelease{v4.46}{2020-03-19}{glossaries-2020-03-19.sty}
\DeclareCurrentRelease{v4.49}{2021-11-01}
```
Maybe we can do something useful with that metadata? Until we figure out what, I suggest a stub is better than an error.

stub in \DeclareRelease

---

lib/LaTeXML/Package/authblk.sty.ltxml
lib/LaTeXML/resources/XSLT/LaTeXML-structure-xhtml.xsl

authblk.sty was a bit too carefree about the many-to-many relationship between authors and affiliations, and the way the marks were written down.
I rewrote the code to do the rearrangement in a single pass, at the end of the document, cloning each affiliation note under each author that uses it. I am a bit uncertain about the intended XML markup for multiple affiliations, so this is still a work in progress, until I get some help from @brucemiller . But once we get that in, I can style it in the CSS and rerun all authblk articles.
Pretty much any authblk.sty paper would be a good test, the one I had in front of me was arXiv:2111.15452 .
The 2021 texlive style file had some extra macros (in particular the \affilsep was used), so I updated the binding coverage as well.

revisit authblk.sty model

---

lib/LaTeXML/MathParser.pm

I stumbled on a curious deep recursion Fatal error
```
Fatal:perl:deep_recursion Deep recursion on subroutine "LaTeXML::MathParser::parse_kludgeScripts_rec" at /home/deyan/perl5/lib/perl5/LaTeXML/MathParser.pm line 578.
at String; line 0 col 0 - line 0 col 0
Stack Trace:
LaTeXML::MathParser=HASH(0x55c112074fe0)->parse_kludgeScripts_rec(ARRAY(0x55c1121feb30),ARRAY(0x55c112102560),ARRAY(0x55c1120c3dc8),ARRAY(0x55c1120be400),ARRAY(0x55c11213eef0),ARRAY(0x55c1120f0928),ARRAY(0x55c1121020e0),ARRAY(0x55c1121024e8),ARRAY(0x55c1120f0e20),...) @ /home/deyan/perl5/lib/perl5/LaTeXML/MathParser.pm line 578
```
with a real formula from arXiv is a minimal example:
```tex
\documentclass[11pt,reqno]{amsart}
\usepackage{amsmath,amssymb,amsthm,amsfonts}
\def\ZZ{\mathbb{Z}}
\def\R{\mathbb{R}} …
```

Allow deep recursion in kludge on large formulas

---

lib/LaTeXML/Common/Number.pm

This PR does **not** claim we shouldn't be fixing the underlying problems that lead to these divisions by zero. We should!
But in the meantime, we may get some Error-ing documents convert to their end, without perl dies.

Avoid divisions by zero in Number, 2022 edition

---

lib/LaTeXML/Post/Graphics.pm

... we just can't write enough tests to cover all corner cases
My previous PR #1757 that had started to properly recognize cases where `$reqtype` was a non-standard name suffix such as `.1.png`, was overly permissive with its check for `defined($reqtype)`. 
This regressed a wide range of images within paper subdirectories, in particular one of our old subfigure tests - arxiv:1602.07188
The fix is incredibly easy, just recognize that this case exists and test for `length($reqtype)>0` instead, so that we only append it when there is *some* character in it (including `0`, which would fail a simple boolean test).
The really frustrating part is that this regression slipped in in the first place, and that I only found it by accident when double-checking my CSS for certain subfigures. I think …

Fix regression in subdir-graphic candidates without extension

---

lib/LaTeXML/Package/IEEEtran.cls.ltxml
lib/LaTeXML/Package/comment.sty.ltxml

One-line PR that recovers `arXiv:1905.05970` back from the land of the Fatals to an almost fully functioning Error-status document.
I copied the macro definition as-is from its .sty file

add \csarg from comment.sty

---

lib/LaTeXML/Package/acmart.cls.ltxml

This is our first externally contributed error report for ar5iv that pertains to a latexml binding.
Nice and easy too!

Add missing macro to acmart.cls

---

lib/LaTeXML/Package/LaTeX.pool.ltxml

This PR allows standard fences at the start/end positions of `ltx:personname` content.
In international author names in arXiv, sometimes there are cases where a second language is written as a parenthetical. An example is:
```tex
\author{Jian-Ming Tang (湯健銘)}
```
The current regex I had written that avoids issues with commas and other punctuation, was also removing the trailing fence, creating a rather unpleasant string that is only open but not closed.
I keep wondering whether a blacklist is better than a whitelist, and switched again. In a simple world I would only remove comma characters, but there is more possible noise... For now let's just allow the fences?
Ready for review.

Allow standard fences as author name embellishments

---

lib/LaTeXML/Package/xcolor.sty.ltxml

We are reusing the `\fcolorbox` of color.sty, but the xcolor.sty one allows the extended color specification as well. Example input:
```tex
\usepackage{xcolor}
\fcolorbox{black!5}{orange!30}{My text}
\end{document}
```
I copied over the definition of `\fcolorbox` and allowed the extended by spec by using `ParseXColor` instead of the usual `ParseColor`.

allow x-color spec in \fcolorbox

---

lib/LaTeXML/Package/todonotes.sty.ltxml

This was reported for ar5iv [here](https://github.com/dginev/ar5iv/issues/24), as potentially harmful -- published articles with "disabled" todonotes should have the notes hidden.
Easy patch I think, ready for review.

Disabled todonotes should not create notes

---

lib/LaTeXML/Package/proof.sty.ltxml

I find myself missing a test for the current math-enabling treatment of `\infer` in proof.sty.
Until I manage to dig one out, here is a minimal test of something that is breaking with the current binding, but works just fine if its return value is simplified:
<details>
```tex
\usepackage{amsmath}
\usepackage{proof}
\usepackage[usenames,dvipsnames,svgnames,table]{xcolor}
\def\InputModeColorName{MidnightBlue}
\def\OutputModeColorName{Maroon}
\newcommand\InputMode[1]{{\color{\InputModeColorName}{#1}}}
\newcommand\OutputMode[1]{{\color{\OutputModeColorName}{#1}}}
\newcommand\sequent[2]{\ensuremath{\InputMode{#1}\gg#2}}
\newcommand\infers[2]{\ensuremath{\InputMode{#1}\Rightarrow{\OutputMode{#2}}}}
\newcommand\isset[1]{\ensuremath{\InputMode{#1}\;\mathit{type}}} …
```

No math check for \infer in proof.sty?

---

lib/LaTeXML/Post/MakeBibliography.pm

Now that the arXiv build is using a custom `--path` to extended bindings, it has become apparent that paths weren't passed into the MakeBibliography inner `->convert` call.
Which is quite important if one was working on say a custom biblatex binding...
perltidy reindented too many lines, my only actual change is on line 219.

allow bibliography post-convert to see the custom paths

---

lib/LaTeXML/Package/TeX.pool.ltxml

Simplifying to a single definition of \lastkern

Remove redundant \lastkern definition

---

lib/LaTeXML/Package/LaTeX.pool.ltxml
lib/LaTeXML/Package/OmniBus.cls.ltxml
lib/LaTeXML/Package/article.cls.ltxml
lib/LaTeXML/Package/chapterbib.sty.ltxml
lib/LaTeXML/Package/natbib.sty.ltxml

Fixes for 2110.02279 and 1811.01740, also reported [in ar5iv](https://github.com/dginev/ar5iv/issues/38).
The changed pieces are:
* `\begin{thebibliography}{} \nocite{*}` was causing malformed errors, so I deferred the XML construction for `\nocite` to the document end, where a paragraph should be easy to auto-open. I also tried floating up, but that felt more fragile.
* I hit two other unsupported cases where `\title[]{}` was used with an optional argument. One was due to an unrecognized class, so I added the argument to OmniBus. But the other was due to a raw-interpreted unknown package that redefines `\title`. Since we are using `locked => 1` in LaTeX.pool (which is reasonable+mostly robust), I think we should allow the optional argument for any latex article. Nothing is really lost, …

[arXiv] avoid malformed \nocite, short titles in OmniBus

---

lib/LaTeXML/Package/LaTeX.pool.ltxml

This PR avoids one risk of an infinite loop on Error-severity documents. The example I was debugging is `2003.0149`, which has multiple hard aspects left (including yet another infinite loop).
But the one simple loop I could trace looked like:
```
\lx@bDM@in@equation [for \lx@saved@BEGINDISPLAYMATH] ->\lx@saved@BEGINDISPLAYMATH \let \@@ENDDISPLAYMATH \lx@saved@ENDDISPLAYMATH 
\lx@bDM@in@equation [for \lx@saved@BEGINDISPLAYMATH] ->\lx@saved@BEGINDISPLAYMATH \let \@@ENDDISPLAYMATH \lx@saved@ENDDISPLAYMATH 
\lx@bDM@in@equation [for \lx@saved@BEGINDISPLAYMATH] ->\lx@saved@BEGINDISPLAYMATH \let \@@ENDDISPLAYMATH \lx@saved@ENDDISPLAYMATH 
\lx@bDM@in@equation [for \lx@saved@BEGINDISPLAYMATH] ->\lx@saved@BEGINDISPLAYMATH \let \@@ENDDISPLAYMATH \lx@saved@ENDDISPLAYMATH 
...
```
This code was …

avoid infinite loops caused by Errors misdefining \lx@saved@... macros

---

lib/LaTeXML/Package/TeX.pool.ltxml

The PR simply uses the definitions from the TeXbook for `\item` and its neighboring definitions in the pre-latex TeX.pool setting.
The created markup is not "modern", but is better than the simpler stubs, at least in providing the intended vertical layout for the items.
As an example of the current behavior, see the single line references at:
https://ar5iv.labs.arxiv.org/html/hep-th/9601178#id2519.4.1
With the underlying TeX:
<details>
```tex
\centerline{\bf REFERENCES}
\item{[1]}  E. Martinec, Phys. Lett. ${\underline{B171}}$ (1986) 189 - 194
\item{[2]}   R. Kallosh and A. Morosov, Phys. Lett. ${\underline{B207}}$ (1988)
164 - 168
\hfil\break
A. Restuccia and J. G. Taylor, Phys. Rep. ${\underline{174}}$ (1989) 283 - 407
\item{[3]}   N. Berkovits, Nucl. Phys. ${\underline{174}}$ (1989) …
```

improve the TeX.pool \item

---

lib/LaTeXML/Package/enumitem.sty.ltxml

This PR may be _too_ expedient, but I am not sure I understand the enumitem.sty implementation on my own to do better. Help from @brucemiller will be appreciated (pointing me in the right direction would suffice, if this is the wrong one).
Here is a minimal TeX snippet:
```tex
\usepackage{enumitem}
\begin{itemize}[nolistsep,noitemsep]
\item \emph{Epidemiology} - test
\end{itemize}
\end{document}
```
Which produces the error:
```
Error:undefined:\KV@enumitem@noitemsep@default The token T_CS[\KV@enumitem@noitemsep@default] is not defined. at sep.tex; line 4 col 0
```
I am unsure what the actual usefulness of declaring the unused KeyVal options is, but that is done in enumitem.sty.ltxml:
```perl
DefKeyVal('enumitem', 'noitemsep',    'UndigestedKey'); …
```

Silence pointless enumitem errors

---

lib/LaTeXML/Post/XSLT.pm

Example where that was needed is `arXiv:1612.02710`.
With the 500 depth, post-processing died with a Fatal error. With 1000, it succeeded smoothly.

Give XSLT more depth

---

lib/LaTeXML/Package/LaTeX.pool.ltxml

Fixes `arXiv:gr-qc/0405052` by locking one more internal macro.
We simply aren't prepared to interpret raw in the low-level equation numbering machinery, and documents hit 100 Errors rather quickly when they try.

Avoid deep recursion by locking \@eqnnum

---

lib/LaTeXML/Package/epsf.sty.ltxml

Tested with `hep-ph/0009104`, avoids the Fatal
```
Undefined subroutine '&LaTeXML::Package::Pool::image_candidates' called at at /usr/local/share/perl/5.34.0/LaTeXML/Package/epsf.sty.ltxml line 51
```
[found here](https://corpora.mathweb.org/corpus/arxmliv/tex%5Fto%5Fhtml/fatal/misdefined/LaTeXML%3A%3APackage%3A%3APool%3A%3A%5F%5FANON%5F%5F?all=false)
It's fine if we catch more of these - easy to rerun the ones that leave Fatal traces.
Since we are rerunning a whole lot of epsf.sty, I am happy to merge here quickly and update the reruns.

Add missing use to epsf.sty.ltxml

---

lib/LaTeXML/Package/LaTeX.pool.ltxml
lib/LaTeXML/Package/aa.cls.ltxml

We have arXiv:astro-ph/0203101 using aa.cls with amsmath.sty {cases}, as in:
```tex
\documentclass[]{aa520}           
\usepackage{natbib,amssymb,amsmath,curves,epsfig}
% ...
\begin{equation}
\iota(i)\equ
\begin{cases}
i-\hlf &\text{for\quad} \beta_i > 0 \,, \\
i+\hlf &\text{else}\,. \\
\end{cases} 
\end{equation}
```
However, the `aa.cls.ltxml` binding, through `aa_support.sty.ltxml`, loads `amsmath.sty` and then disables its cases environment, reverting it back to a simple macro `\cases{}`. That leaves us in a bit of a pickle - 100 errors starting from misinterpreted align `&` chars.
Rather than refactoring aa_support - which is used in a wide variety of helpful arXiv nooks and crannies, I think a pragmatic change is to hide the fact that amsmath.sty was loaded when relying on aa.cls …

Possible to use aa.cls with amsmath.sty {cases}

---

lib/LaTeXML/Package/revtex4-1.cls.ltxml

Today I found out that revtex4-1.cls unconditionally loads a `\jobname.rty` file with custom definitions, when it is available on disk.
And of course I found that out by investigating an arXiv document's Fatal status, namely `1305.1045`, which has the files:
```
chgauge.pdf             
smodel.bbl              
smodel.rty              
smodel.tex   
```
This PR simply adds the check to revtex4-1.cls.ltxml and loads the `.rty` file when it is available.

load \jobname.rty for revtex4-1, when present

---

doc/manual/manual.tex

This PR fixes a small typo in the manual. The capitalization of the `maybeMathjax.js` script in the manual was incorrect.
Thanks to Deyan Ginev and Nasser M. Abbasi for noticing.
See also:
https://github.com/brucemiller/LaTeXML/issues/1845#issuecomment-1091960411
https://lists.informatik.uni-erlangen.de/pipermail/latexml/2022-May/002550.html

Fix `maybeMathjax.js` typo in manual

---

lib/LaTeXML/Core/Rewrite.pm

This awkward naming threw me in for a loop while porting the Rewrite code.
I couldn't immediately figure out if there is an actual bug or perl's variable shadowing worked just right to still get the desired behavior.
To be sure, here is a renaming that doesn't test the limits of perl's expressiveness here.

avoid variable name reuse in Rewrite

---

MANIFEST
lib/LaTeXML/Package/ed.sty.ltxml

This PR adds a new binding for the 'ed' package found at https://ctan.org/pkg/ed.
The binding can directly read the '.sty' file, and no additional hooks are needed.

Add binding for 'ed.sty'

---

lib/LaTeXML/Core/Alignment.pm
lib/LaTeXML/Package/LaTeX.pool.ltxml
lib/LaTeXML/Package/TeX.pool.ltxml
lib/LaTeXML/Package/pgfsys-latexml.def.ltxml

Generalized the SVG support for various primitives and foreignObject, moved from the pgf driver to TeX.pool.  This allows it's use for xy binding.

Svg infrastructure

---

lib/LaTeXML/Post/LaTeXImages.pm

As it says; leaving "@" as letter breaks cases where it's expected to be other.  If there are "@" letter cases leaking into the image sources, those are bugs that need to be fixed.
[I'll probably merge this in shortly, but making a PR to draw attention to it]

MUST make @ other during latex image processing

---

lib/LaTeXML/Package/LaTeX.pool.ltxml
t/80_complex.t

The "if" clause should appear *before* the file is input!  This fixes the 2020 babel greek regression.

Fix ordering bug in \InputIfFileExists

---

lib/LaTeXML/Package/beamer.cls.ltxml

beamer automatically includes graphicx and therefore many source files that use beamer
do not include an explicit \usepackage{graphicx}. Without this addition images that are included
by \includegraphics are not displayed.
The other two lines come from latexmllint in order to satisfy the pre-commit hook.

require graphicx in beamer.cls

---

lib/LaTeXML/Package/amsthm.sty.ltxml

This is a minor patch from an odd-looking error I spotted while debugging 2205.11657, related to amsthm.sty
It turns out, you can invoke/activate a `\theoremstyle{theorem}` for an undefined style name, and pdflatex succeeds error-free, with only mild warning in the log file:
```
Package amsthm Warning: Unknown theoremstyle `theorem' on input line 92.
```
Looking at amsthm.sty, that simply reverts to plain as seen here:
```tex
\newcommand{\theoremstyle}[1]{%
\@ifundefined{th@#1}{%
\PackageWarning{amsthm}{Unknown theoremstyle `#1'}%
\thm@style{plain}%
}{%
\thm@style{#1}%
}%
}
```
So, this PR introduces that mild warning + fallback to plain, hiding the current error for (in this case) an undefined `\th@theorem`.

Warn and revert to plain on missing \theoremstyle in amsthm.sty

---

.gitignore
MANIFEST.SKIP

The Mac OS X Finder app (the file explorer GUI) adds a .DS_Store file to every directory the user interacts with.

ignore .DS_Store

---

lib/LaTeXML/resources/CSS/LaTeXML-marginpar.css

In LaTeXML-marginpar.css, a margin note's content should be positioned with `absolute`, so that it can scroll with its anchor point.

Change marginpar position from fixed to absolute

---

lib/LaTeXML/Package/hyperref.sty.ltxml

As reported in #1831, hyperref treats the first argument as 'Verbatim' and does not expand it.
This PR fixes the issue by making it a regular argument.

Fix #1831: Make \hyperref expand first argument

---

lib/LaTeXML/resources/XSLT/LaTeXML-webpage-xhtml.xsl

Simple fix to a lack of css class consistency

be consistent in adding class to TOC Contents heading

---

lib/LaTeXML/Package.pm
lib/LaTeXML/Package/aas_support.sty.ltxml
lib/LaTeXML/Package/deluxetable.sty.ltxml
lib/LaTeXML/Package/emulateapj.sty.ltxml

Rude to usurp #1823, but expedient since by the time I'd sorted out all the false clues, it was basically done.
Once `coerceCS` (used by `DefMacroI` etc) properly recognized the `\csname...\endcsname` idiom, it's less mysterious to just define `\deluxetable` and `\enddeluxetable` (and all the variants), rather than go through the `\begin{deluxetable}` route and then try to patch on top of that.
I didn't do anything about `flushrt`; not sure what that was.
And, I'm assuming you have ar5iv sty.ltxml bindings for   aasms4 aaspp4 aas2pp4 aj_pt4 apjpt4 astro ? Many of the documents referenced in #1823 start off `\documentsyle[aasms4]{article}`  (they work fine if you change article to aastex). I assume the bindings are just like aasms.sty.ltxml.  We can include them in distribution if you …

Deluxetable alt

---

lib/LaTeXML/Package.pm

LaTeXML should now be able to recognize that a load of `myemulateapj.cls` can directly use `emulateapj.cls.ltxml`.
The PR allows the 3 currently registered prefixes - `my`, `rx` and `preprint` - to be glued to the file names.

Allow optional separator for the prefixes in FindFile_fallback

---

doc/manual/genpods
doc/manual/manual.tex

As noted in #1872, the `./doc/manual/genpods` generates distinct files `doc/manual/pods/latexml.tex` and `doc/manual/pods/LaTeXML.tex`. These file names clash on case-insensitive filesystems, potentially overwriting one another and preventing a proper generation of the manual.
This PR fixes the issue by generating pods for the executables with a new `exe_` prefix. This commit furthermore adjusts their inclusion in `doc/manual/manual.tex`.

Fix #1872: Generate executable pods with prefix

---

lib/LaTeXML/Util/Pack.pm

Fixes #1882 , fixes [ar5iv#27](https://github.com/dginev/ar5iv/issues/27), fixes [ar5iv#145](https://github.com/dginev/ar5iv/issues/145).
This PR bundles a few improvements for the `--whatsin=archive` mode of conversion, which accepts a ZIP bundle on input. Namely:
- `.txt` extension is recognized as a possible TeX source
- two arXiv directives from `00README.XXX` are recognized - `toplevelfile` and `ignore`
- an extra special case rule is added to tie-break high scoring files, where `main.tex`, `ms.tex` and `paper.tex` will get preferred to any non-standard names (such as the template name `bare_adv.tex`). This has to be done carefully, as a last check of the high-scoring files, to make sure we're choosing legitimate document sources.

Improve TeX detection for archive inputs

---

lib/LaTeXML/resources/XSLT/LaTeXML-para-xhtml.xsl

As it says...
This assumes that the inconsistency mentioned in #1887 was unintentional.
fixes #1887

Make caption positioning XPath consistent between before and after positions

---

lib/LaTeXML/Package/listings.sty.ltxml

start \lstinline with \leavevmode to keep alignments from expanding

---

lib/LaTeXML/Package/gensymb.sty.ltxml

Internal symbols in gensymb need aliases (and macros probably protected)

---

lib/LaTeXML/Package/LaTeX.pool.ltxml

Give \ref a size, not the size of its args

---

lib/LaTeXML/Package/LaTeX.pool.ltxml

Examines the optional argument to `\pagebreak[]`, and outputs the XML only when the argument is 3 or 4.  (The alternative would be to end up with vertical spacing equal to `(argument/2)em`, but this would require more complicated XML and also changing the CSS, not to mention still needing to decide whether to break the page in epub.)
Fixes #1802.

Use optional argument to pagebreak

---

MANIFEST
lib/LaTeXML/Package/tikzbricks.sty.ltxml

Following samcarter's lovely talk about tikzbricks.sty, I discovered latexml can already interpret it raw with good outcomes. For example:
```tex
\usepackage{tikzbricks}
\begin{wall}
\wallbrick[color=blue]{2}{1}
\wallbrick[color=red]{1}{1}
\addtocounter{brickx}{1}
\wallbrick[color=orange]{1}{1}
\newrow
\addtocounter{brickx}{1}{1}
\wallbrick[color=cyan]{4}{1}
\end{wall}
\end{document}
```
produces:
This PR just lets latexml use the raw definition, seeing that it already knows how to.

add native support for tikzbricks.sty

---

lib/LaTeXML/Package/neurips.sty.ltxml

Spotted an error in [arXiv:2205.15868](https://ar5iv.labs.arxiv.org/html/2205.15868) so I pulled the most recent [neurips_2022.sty](https://neurips.cc/Conferences/2022/PaperInformation/StyleFiles) and added the missing definitions.
Also prepared some option-related flags in case we decide to implement more.

neurips.sty 2022 update

---

bin/latexmlc
lib/LaTeXML.pm
lib/LaTeXML/Post/Writer.pm

Fixes #1800 .
I hope. It seems to be correct for all variations I tried, but that testing is limited to my `perl v5.34.0`, `libxml version 20913`, using the latest latexml.
The pieces that continue to feel solid are:
- Any standard run with a provided destination will rely on Writer.pm, which has been robust in terms of encodings for a very long while.
- The fragment/math serialization routes which rely on `->toString(1,1)` are also quite robust in providing a properly encoded UTF-8 string.
- The other output cases are the ones I keep juggling code until I get the incantation right, especially for printing to STDOUT.
I double-checked that the Mojolicious web editor also continues to work correctly with the PR changes, so maybe they are closer to the correct setup (or even - completely …

Serialization encoding fixes for LaTeXML.pm

---

lib/LaTeXML/Package/TeX.pool.ltxml

This is a discussion starter PR (but maybe already useful?)
I was quickly trying to tackle a timeout from arXiv, using [arXiv:math/0601709](https://arxiv.org/abs/math/0601709), [ar5iv log](https://ar5iv.labs.arxiv.org/log/math/0601709).
It turns out that document has 2162 uses of `$,$` to control comma spacing, which creates - as expected - 2162 math elements with a single comma in them.
I think the markup is cleaner if these kinds of "typesetting abuse" uses of math modes start to gradually get teased away back into text mode. And since latexml is "filled to the brim with heuristics", might as well keep adding more of those.
Not necessarily the best strategy, but I quite like that we now have the `cleanup_Math` subroutine to host such considerations.

prune single XMTok math to text, if PUNCT or PERIOD

---

lib/LaTeXML/Package/comment.sty.ltxml

allow whitespace in \end{comment} line

---

lib/LaTeXML/MathParser.pm
t/complex/physics.xml

I knew there was something peculiar there! When parsing the contents of an `XMWrap` fails, we don't need to add an extra wrapper, but can simply mark the container (the `XMWrap`) as unparsed; but *not* mark the children, since they are often quite legitimate and referred to by the content branch of an `XMDual`.

Fix unparsed

---

bin/latexmlmath

Repair the HACK that disables cleanup_Math, so text in math doesn't disappear

---

lib/LaTeXML/Package/pgfsys-latexml.def.ltxml

Like xy, these matrices end up as a bunch of explicitly positioned fragments, so pruning empty cells only leads to spacing errors.
Fixes #794

Tikz matrices don't need to be pruned (they aren't real tables)

---

lib/LaTeXML/Util/Pack.pm

Fixes an edge cases reported in [ar5iv#43](https://github.com/dginev/ar5iv/issues/43), which lead to wrongly recognizing a dependent TeX file as the primary article source.
The arXiv "veto" algorithm works well, but there was a need to remove trailing spaces before appending the `.tex` extension.

Avoid trailing spaces in vetoed filenames for ZIP inputs

---

lib/LaTeXML/Package/LaTeX.pool.ltxml
lib/LaTeXML/Package/TeX.pool.ltxml
lib/LaTeXML/Package/framed.sty.ltxml
lib/LaTeXML/Package/ntheorem.sty.ltxml
lib/LaTeXML/resources/CSS/LaTeXML.css
lib/LaTeXML/resources/XSLT/LaTeXML-tabular-xhtml.xsl
t/graphics/framed.xml
t/theorem/ntheorem.xml

Several seemingly related patches regarding frames and blocks, and side issues that cropped up in the process. This places more uniform spacing around frames; more consistent handling of some theorem features.  It makes slight improvements to `insertBlock`, but future work will need to generalize better.  Also slightly improves the validation & styling of rowspan and colspan on tables that are faked with span-soup due to HTML's schema.
Fixes #1704 
Fixes #1706
Fixes #1709

Blocks n frames

---

lib/LaTeXML/Package/TeX.pool.ltxml

A [social report](https://twitter.com/isomorphisms/status/1556444329811578881) spotted a particular lack of images in arxiv-vanity that also affects ar5iv, namely caused by:
```tex
\graphicspath{{figs/}{anc/}}
```
which our convenient `DirectoryList` parameter type wasn't parsing correctly. I added another level of indirection for the unbracing, and this should now work. The article in question is [1801.04486](https://ar5iv.labs.arxiv.org/html/1801.04486), in particular Figure 1.

recognize \graphicspath{{dir1/}{dir2/}}

---

lib/LaTeXML.pm
lib/LaTeXML/Package/LaTeX.pool.ltxml
t/structure/book.xml

Simple fix for #1606. I think `scope='global'` is safe here – `\tableofcontents` is supposed to generate a TOC for the entire document after all, just like for the list of figures, tables, etc.

generate global toc for \tableofcontents

---

lib/LaTeXML/Package/todonotes.sty.ltxml

Caught my eye in [arXiv:2205.10770](https://ar5iv.labs.arxiv.org/html/2205.10770) which is otherwise without any issues.
Looking at the [todonotes docs](http://tug.ctan.org/macros/latex/contrib/todonotes/todonotes.pdf), we are not emulating the full in-depth features yet, so just adding some harmless scaffolding to keep the conversions clean.

add \setuptodonotes stub

---

lib/LaTeXML/Post.pm

Fix #1654. Assuming the code I removed is really safe to remove. I don't see the use case, so I am guessing it is an historical artefact (maybe `addDate` was originally run on the top document as well?).

do not create new dates in split documents

---

tools/latexmllint

This PR documents the list of cpan packages required for the latexmllint program to function properly.

tools/latexmllint: Document required policies

---

lib/LaTeXML/texmf/latexml.sty

lxRequireResource is defined in latexml.sty.ltxml, but not latexml.sty.  This defines it to do nothing.
Since I was editing the file, I also moved lxKeyWords to come before lxContextTOC, in order to match the order in latexml.sty.ltxml.

providecommand for lxRequireResource

---

lib/LaTeXML/Package/graphicx.sty.ltxml

just a stub for `\Gin@esetsize`, that currently causes errors [in CorTeX](https://corpora.mathweb.org/corpus/arxmliv/tex%5Fto%5Fhtml/error/undefined?all=true) for 0.16% of arXiv articles (~3000 articles).
I quickly examined `1511.02120`, and I think the macro is invoked as a side-effect from the adjustbox.sty machinery (which we interpret raw), but likely we can't do much more than nod along for now.

stub \Gin@esetsize

---

lib/LaTeXML/Package/csquotes.sty.ltxml
t/babel/csquotes.xml
t/structure/csquotes.xml

Fix #1930.
My theory is that the current meaning of `ltx_quote` (the class for `<ltx:quote>`) is not the same as it was in 2013. Since inline quotes in the sense of csquotes have little to do with `<ltx:quote>`, I changed the class name to `ltx_csquote`. I hope that doesn't break anything else.

make csquotes commands inline

---

lib/LaTeXML/Package/LaTeX.pool.ltxml

Fixes an out-of-memory Fatal caused by low-level interpretation of a style file in [ar5iv#189](https://github.com/dginev/ar5iv/issues/189).
A nice find, since the fix is simply introducing a couple of missing macros from latex.ltx.

add \not@math@alphabet

---

lib/LaTeXML/Package/jheppub.sty.ltxml

As it says. I was looking at examples that do not have `\preprint` defined and this was a package we already had a binding for - so I updated it with some help by `tools/texscan`.
A sample article is [arXiv:1210.8038](https://ar5iv.labs.arxiv.org/html/1210.8038), which had a local copy of jheppub.sty.
---
Related thoughts:
The frontmatter for the example article is still clunky however (unchanged from the latexml master). I would like to improve it, but I don't have a grasp of 
1. our full frontmatter vocabulary and 
2. the interplay of the `\@add@to@frontmatter` macro language, in particular between affiliations and author marks.
I remember knowing the bits here a little better some time ago, but those memories have now started fading. Maybe there is a path to documenting more about the …

updated macro set for jheppub.sty

---

lib/LaTeXML/Package/revtex4_support.sty.ltxml

I spotted that `\replace@command` is used in arXiv:1112.1218, and its lack was currently causing a (circumstantial) infinite loop in that document conversion.
Looks harmless enough to provide in the revtex support binding, hence this PR.
The document in question converts successfully, with only two minor errors remaining (missing support for `\sanitize@url` and `\@email`)

Add a couple of revtex internals

---

lib/LaTeXML/Package/OmniBus.cls.ltxml

Adding fallback support for two extra easy cases:
- `{aug}` used as an author block can simply be unwrapped, as we handle the frontmatter building ourselves.
- `\newremark` can use the same fallback for `\newproclaim`
Future note: The `.cls` examples I was testing with could one day benefit from also picking up more of the raw interpretation, in particular `\def` and `\newcommand` entries, but also recognizing some more subtle `\RequirePackage` uses, e.g. hidden in hooks such as `\AtEndOfClass`.

omni support for {aug} and \newremark

---

lib/LaTeXML/Package/elsart_support_core.sty.ltxml

As it says - someone in a hurry must have forgotten the argument signature for a couple of frontmatter macros.
Spotted while debugging arXiv:math0603447

fix binding typo - missing argument in elsart_support_core

---

lib/LaTeXML/Package/LaTeX.pool.ltxml

Fixes [ar5iv#89](https://github.com/dginev/ar5iv/issues/89)
We currently don't implement the font specifics behind `\DeclareFixedFont` and `\DeclareErrorFont`, but we should at least stub in the implied macros to avoid needless errors.
Elevates the article in question from Error to Warning (just math parsing).

stub in fixed font macros as \relax

---

lib/LaTeXML/Post/MathML.pm

Fixes #1801 .
Questions to @brucemiller : 
- Should we use the `em` units MathML Core recommends, instead of `pt`, so that spaces scale along with font-size?
- Is the PR correct so far?
I can claim the current commit phases out the old values, as a grep for "mathspace" doesn't find any other active code with them. But so far this is the kind of change that someone completely new to latexml would made, since I consider myself mostly novice when it comes to the post-processing unit considerations.
Thanks for any tips!

phase out *mathspace mspace values

---

lib/LaTeXML/Package/LaTeX.pool.ltxml
lib/LaTeXML/Package/hyperref.sty.ltxml
lib/LaTeXML/texmf/latexml.sty

I was quickly surveying mdframed.sty articles, and got side-tracked into adding some minor boilerplate that removes spurious PDF-related errors from arXiv:1306.2973
Mostly no-ops, list is:
- add `\@thefnmark` and lock the footnote macros, as they will almost certainly produce broken markup upon redefinition.
- add a handful of latex.ltx internal macros that may get exercised during raw interpretation, but have no real effect in latexml processing (PDF-related)
- add `\@removeelement` with its real definition from latex.ltx
- fix a typo of the macro `\pdfstringdef` which was written `\pdfstring` in hyperref
- add stubs for the PDF bookmark macros in hyperref
- sanitized `\MessageBreak` into a newline when it made its way into our custom generic messaging subroutine
- even more minor: my …

Minor boilerplate / latex.ltx fixes

---

lib/LaTeXML/Package/TeX.pool.ltxml
lib/LaTeXML/Package/babel_support.sty.ltxml
lib/LaTeXML/Package/csquotes.sty.ltxml
lib/LaTeXML/Package/eTeX.pool.ltxml

Fixes #1963 .
After the usual wild goose chases, I identified two causes for the test suite failing with the latest texlive 10.2022.
1. We were missing support for `\the\font`, which I added via 
- a special case in the `Register` parameter type
- a special case in `\the`.
- For now the PR returns a stub font CS, namely `\tenrm`
2. The more sinister error was in the depths of expl3, namely loading of data `.txt` files, and in particular `SpecialCasing.txt` and `GraphemeBreakProperty.txt`
- the fix here boiled down to respecting `\endlinechar` in the `\readline` reader in eTeX.
- though that seems to slow down expl3 loading even further - maybe there is a faster way?
The font side is obvious, so I'll just add a bit of detail on the expl3 side:
After a multi-hour debugging session, I could …

Address texlive 10.2022 regressions

---

lib/LaTeXML/resources/XSLT/LaTeXML-webpage-xhtml.xsl
t/daemon/formats/citation.xml
t/daemon/formats/citationraw.xml
t/daemon/formats/mixedmath.xml
t/moderncv/cs_cv.html

Fixes #1626 .
- I defaulted to "en", since it is allowed, and we have no real reason to assume US over UK/AU.
- Only in XSLT, so that the default only impacts (X)HTML formats, where we know there is benefit.

Default the html language to "en"

---

.github/workflows/windows.yml

As it says.
Let's not waste the CPU cycles in Github Actions for a >20min test that we know will fail.
(for reasons completely independent of latexml)

Yank miktex test from CI

---

t/170_grammar_coverage.t
t/83_expl3.t
t/97_manifest.t

My patch in #1969 results in a more correct latexml interpretation of expl3, but it *also* results in a slower interpretation.
1. The `t/83_expl3.t` tests now take 7 minutes on my local PC, which has a decent CPU. 
- In comparison, the second slowest test is `t/80_complex.t` which takes 3.5 minutes .
2. Separately, the expl3 test was a reason for raising a flag in the Debian "AutoPKG test suite", where the latexml package builds failed due to expl3 no longer loading error-free in interpretation.
3. I think it is a great goal to stay compatible with LaTeX 3, to keep that test, and to **always** run it in CI.
4. But at the same time I think regressions in our processing of LaTeX 3 should not be a reason for the latexml package builds to fail. Similarly to tikz, which may regress and we …

only run t/83_expl3.t in CI mode

---

lib/LaTeXML/resources/XSLT/LaTeXML-common.xsl

so they get the right priority.  This fixes a bug introduced in #1960.
Would be good to merge this quickly as it fixes a bug where `href` attributes don't get rewritten, breaking dlmf.

Better organization of copy-attribute templates 

---

Makefile.PL
lib/LaTeXML/Common/Error.pm

This PR fixes something ugly I did pre-0.8.6 to make LaTeXML work in Windows consoles, which is to try importing `Win32::Console` rather than properly checking the platform, declaring the `Win32::Console` dependency in the Makefile, etc.
To declare the PR done, I want to make it behave properly under `$^O eq 'cygwin'`, but my Windows machine is taking its time. In the meanwhile, I sense an impending release, so please let me know if there is something obviously wrong here!

declare Windows specific dependencies

---

lib/LaTeXML/Package/IEEEtran.cls.ltxml

Minor, adds a missing macro that gets arXiv:1801.03552 from Error to a Warning status.
Maybe one day we can do more here, but it appears to hinge on raw `.bst` interpretation.

add missing stub for \bstctlcite

---

lib/LaTeXML/Util/Pack.pm

Fixes [ar5iv#265](https://github.com/dginev/ar5iv/issues/265) by adding the `TeX::AutoTeX` heuristic detection of pdftex sources in a ZIP archive input for latexml.
This aligns the ZIP conversion another small step closer to arXiv's selection of the main TeX file.
The main novelty in the PR is the `heuristic_check_for_pdftex` subroutine. The rest is some minor code refactoring for more consistency.

add includegraphics heuristic for TeX source detection

---

lib/LaTeXML/Package/longtable.sty.ltxml

This ignores `\pagebreak` within `{longtable}`, resolving #2000.  (I have checked that `\pagebreak` still works after the environment ends.)
This also removes the `{longtable*}` environment, which doesn't exist in TeXLive (and if it's supposed to mimic `{tabular*}{width}{colspec}`, then it's missing the `{width}` parameter).

ignore pagebreak within longtable

---

lib/LaTeXML/Package/enumitem.sty.ltxml

Fixes #1966 . But only "the symptom".
For a general upgrade:
Maybe we ought to refactor/revisit the enumitem "ref" capability (and I need to learn more about it in general) to see if we can sidestep the quick-and-dirty internal use of `\theenumi` in latexml.
I see that the raw sty file uses a delayed expansion trick via `\enit@delayedkeys`, which may be something to emulate. But it is all so roundabout compared to the current binding code that I'd rather not touch it on a short notice - so just preventing an infinite loop in this PR.

Hotfix for infinite loop in enumitem ref

---

lib/LaTeXML/Package/pstricks.sty.ltxml

`arXiv:math/0109128` was dying with 100 Errors for a curious reason - `\scalebox` from pstricks.sty.
It turns out that macro is fully usable without a pspicture, and LaTeXML kept firing schema errors each time an `ltx:g` was attempted to be inserted into an XMTok. One example being:
```tex
\newcommand{\simplex}{{\scalebox{1.3}{\color{gray}\blacktriangle}}}
```
This PR simply disables/neutralizes the scaling in non-pspicture contexts, which recovers that article to an Error status.

neutralize \scalebox outside of pspicture

---

lib/LaTeXML/Post/MathML.pm
lib/LaTeXML/Post/MathML/Linebreaker.pm
t/math/sampler.tex
t/math/sampler.xml

This PR introduces the changes implied by [removing `<none>` in MathML Core](https://github.com/w3c/mathml-core/issues/173), by simply switching latexml's use of that element for an empty `<mrow>`.
---
LaTeXML seemingly also has an interesting choice in the "gray zone" of the MathML spec, by using an empty `<mi></mi>` element for slots where it expected tokens, but they were "absent":
```perl
DefMathML("Token:?:absent", sub { return ['m:mi', {}] });
```
These _could_ also be transitioned to empty mrow elements, especially since they get used in the base child slot of `mmultiscripts`. As an example: `${}_a^b {}_c^d$`, produces:
```xml
<mmultiscripts>
<mi/>
<mi>c</mi>
<mi>d</mi>
<mprescripts/>
<mi>a</mi>
<mi>b</mi>
</mmultiscripts>
```
where the recommendation used to be a use of `<none/>` …

move away from using MathML <none>

---

lib/LaTeXML/Package/multicol.sty.ltxml
t/structure/columns.xml

This PR adds `ltx:pagination` markers when switching the number of columns using the `multicol` package.  It uses markers rather than wrapping the content, since the multicolumn content does not necessarily nest with the document structure tree (see the discussion in #1711).  Although these markers can't be directly used by CSS, hopefully they will be of some use.
Fixes #1711

Multicol markers

---

lib/LaTeXML/Post/MathML.pm
t/daemon/formats/lexmath.xml

As it says; was unnecessarily scanning the children of `XMText`, resulting in multiple `mtext`.
Fixes #1846

Don't complicate mtext if no nested math

---

lib/LaTeXML/Package/LaTeX.pool.ltxml

since they end up indirectly used to sort out font styles in CSS
fixes #1713

Probably safe (and wise) to lock \ttdefault, etc,

---

lib/LaTeXML/Package/LaTeX.pool.ltxml
lib/LaTeXML/Post/MathML.pm
t/daemon/formats/lexmath.xml

This is an alternative fix for #1846 to avoid breaking MathJax.  It basically reverts #2009, but defines `\emph` so as to use `ltx:text` when within math, rather than `ltx:emph`.   We can better distill `ltx:text` down to essentials, but `ltx:emph` sticks around and finds its way inside the eventual `m:mtext`.  MathJax can't cope with this. So (arguably) the issue in #1846 is not the `mathvariant` on `m:mtext`, but rather the redundant html `<em>` inside of it.

Refix mtext nesting

---

lib/LaTeXML/Package/listings.sty.ltxml

This PR dumbs down CS given to `\lstinline` that have already been tokenized by Gullet, eg within a `\caption'
fixes #1377 
(sorry for the delay!)

Careful about CS that have already been tokenized in \lstinline

---

lib/LaTeXML/Package/TeX.pool.ltxml
lib/LaTeXML/Package/tikz.sty.ltxml

Improves arXiv:2010.15940 from (deep recursion) Fatal to Warning status.
- simply allow for deep recursion in `adjustBoxColor_rec`
- start with a `\tikz@align@temp` that is defensively initialized to `\relax`
**Debugging details:**
<details>
Here is a Firefox screenshot of the responsible tikz diagram that had the recursion, after it succeeds in getting generated with the PR changes:
It still needs some upgrades to the sizing/measuring logic, but I think it is a rather good reasonable output compared to a Fatal error.
</details>

allow deep recursion in adjustBoxColor_rec; add \tikz@align@temp

---

lib/LaTeXML/Package/amsmath.sty.ltxml

This PR locks the binding definitions of amsmath.sty.ltxml's:
- `\tag`, `\align`, `\endalign`, `\align*`, `\endalign*`, `\aligned`, `\endaligned`, `\alignedat` and `\endalignat`.
Doing so recovers arXiv:2210.17255 from a Fatal error to a Warning status.
**Debugging details**
<details>
That article included a local `.sty` file which had redefinitions of the following flavor:
```tex
\def\tag#1$${\iftagsleft@\leqno\else\eqno\fi
\hbox{\def\pagebreak{\global\postdisplaypenalty-\@M}%
\def\nopagebreak{\global\postdisplaypenalty\@M}\rm(#1\unskip)}%
$$\postdisplaypenalty\z@\ignorespaces}
\def\align#1\endalign{\def\tag{&}\plainvspace@\plainallowdisplaybreak@\plaindisplaybreak@
\iftagsleft@\plainlalign@#1\endalign\else
\plainralign@#1\endalign\fi}
```
which may be a bit too challenging of a …

lock amsmath alignments (arXiv robustness)

---

lib/LaTeXML/Post/CrossRef.pm
lib/LaTeXML/Post/MakeBibliography.pm
lib/LaTeXML/Post/Scan.pm

Try to emulate BibTeX's (curious) behavior: It uses case-insensitive lookup to find entries in the bib file, but then uses the key with the case as cited for the aux file, since LaTeX's labels & cites are case-sensitive.
fixes #1674

Citationkey case

---

lib/LaTeXML/Package/natbib.sty.ltxml

Feeling a little proud of spotting this one-liner PR.
There was a Fatal with `arXiv:1104.3156` due to a long chain of malformed ltx:bibitem of the form
```
Error:malformed:ltx:bibitem <ltx:bibitem> isn't allowed in <ltx:p> 
```
Upon inspection, this was due to a peculiar custom parsing algorithm in natbib.sty.ltxml, called `NAT_peel_arg`, which had a fascinating (and hard to hit) bug in using an array `pop` instead of `shift` in one of the recognized cases.
Changing that switches this Fatal to a Warning status.
minimal TeX to reproduce:
```tex
\usepackage{natbib}
\begin{thebibliography}{1}
\bibitem[\protect\citeauthoryear{Chabrier} {2003}]{cha03} Test
\bibitem[Cooper et al.(2008)]{coo08} Test2
\end{thebibliography}
\end{document}
```

patch \bibitem buglet in natbib

---

bin/latexmlpost
lib/LaTeXML.pm
lib/LaTeXML/Package/TeX.pool.ltxml
lib/LaTeXML/Post/Manifest/Epub.pm
lib/LaTeXML/Util/Pack.pm

Quick example implementation of SOURCE_DATE_EPOCH (intended to address #1919). Not sure if it is complete. I just grepped "time" and changed modification times in Util::Pack.
The spec asks that LaTeXML "should" throw an error if SOURCE_DATE_EPOCH is set to an invalid value (i.e. not made of just digits) but I don't know where to do it.
I suppose one could refactor `localtime` into a function in some Util module.

use SOURCE_DATE_EPOCH instead of current time

---

lib/LaTeXML/Core/Definition/Expandable.pm
lib/LaTeXML/Core/Gullet.pm
lib/LaTeXML/Core/Stomach.pm
lib/LaTeXML/Package/TeX.pool.ltxml

Avoids another deep recursion Fatal in arXiv, useful for some large tikz diagrams.
<details>
Motivating tikz example screenshot from `arXiv:2210.11132`:
That article recovers from Fatal to Error, in 8 minutes total conversion time.
</details>

allow more recursion on invokeToken

---

lib/LaTeXML/Core/Token.pm
lib/LaTeXML/Package/latexml.sty.ltxml

Fixes #1393 .
This PR keeps the current behavior of latexml as-is, but it exposes a new global toggle through latexml.sty, which can set/unset the line-breaking **default** of the `UnTeX` helper subroutine. That can still be overridden using the optional second argument of `UnTeX`.
The expected use case (which I will test in the next ar5iv run) is to disable the line-breaks globally, via:
```bash
latexmlc  --preload=[nobreakuntex]latexml.sty \
'literal:$111111111+2222222222+333333333+444444444+555555555+
66666666+777777777+888888888+99999999$'
```
which will generate the tex attribute:
```
tex="111111111+2222222222+333333333+444444444+555555555+66666666+777777777+888888888+99999999"
```
in contrast the default would generate an extra line-break via `%\n`, as in:
``` …
```

allow to globally toggle line-breaking of UnTeX

---

lib/LaTeXML/Post/MathML.pm

Alternative to #2028 per Bruce's suggestion.

deprecate MathML Full use of relative height/depth attributes for yoff

---

lib/LaTeXML/resources/CSS/ltx-article.css

`\documentclass{article}` defines `\part` (just not `\chapter`).  We currently do not style the resulting html.  This PR applies the same styling to parts in articles that we apply to parts in books.

apply CSS to parts in article

---

lib/LaTeXML/Util/Pack.pm

Very minor, just hides a pointless perl warning in a recently added conditional from #1889

avoid definedness warning 

---

bin/latexmlc

As noted in #2069, `latexmlc` and friends were unlinking and re-creating logfiles. This was not a problem in the regular case, however on certain system when `make test` is run with root rights, this caused `/dev/null` to be deleted and re-created as a regular file.
This PR updates the behavior of `latexmlc` to only unlink the logfile if it is a regular file.
Fixes #2069.

latexmlc: Only unlink logfile when it is a regular file

---

lib/LaTeXML/Package/TeX.pool.ltxml

As it says. Spotted while auditing the alignment code (and small enough to fix fast).

Patch: attribute typo in "invisible" flag

---

lib/LaTeXML.pm
lib/LaTeXML/Core/Definition.pm
lib/LaTeXML/Core/Definition/Expandable.pm
lib/LaTeXML/Core/Gullet.pm

This PR gets the profiling option (to `latexml.sty`) working again.
@dginev I've added a call to `LaTeXML.pm` so that `latexmlc` also provides reports, but I'm not sure I added in the ideal place.

Fix profiling

---

MANIFEST
lib/LaTeXML/Package/cmap.sty.ltxml

With `--includestyles`, the package cmap causes a LaTeXML `Warning:latex:(cmap) Package cmap Warning: pdftex not detected - exiting`.  But the purpose of cmap is 'to make the PDF files generated by pdflatex "searchable and copyable"'.  Therefore, the only thing to do is check off any global options and exit successfully.
This is one possible fix for #2035.  It appears that we've already fixed the problem with `\PackageWarningNoLine{}{}` leading to an Error, so that issue is completely resolved.

"implement" cmap.sty

---

.github/workflows/windows.yml
lib/LaTeXML/Package/LaTeX.pool.ltxml

A little compiler birdie told me that a `$ctr` very similar to the one we have in `\@startsection` is never used.
I double-checked and indeed, some wasted compute cycles can be eliminated. Enjoy!

$ctr is never used in \@startsection

---

lib/LaTeXML/Common/XML.pm
lib/LaTeXML/Core/Document.pm
lib/LaTeXML/Core/Gullet.pm
lib/LaTeXML/Core/Parameter.pm
lib/LaTeXML/Core/Rewrite.pm
lib/LaTeXML/Core/Stomach.pm
lib/LaTeXML/Package.pm
lib/LaTeXML/Package/LaTeX.pool.ltxml
lib/LaTeXML/Package/TeX.pool.ltxml
lib/LaTeXML/Package/amscd.sty.ltxml
lib/LaTeXML/Package/amsmath.sty.ltxml
lib/LaTeXML/Package/amsppt.sty.ltxml
lib/LaTeXML/Package/amsthm.sty.ltxml
lib/LaTeXML/Package/beamer.cls.ltxml
lib/LaTeXML/Package/caption.sty.ltxml
lib/LaTeXML/Package/cite.sty.ltxml
lib/LaTeXML/Package/listings.sty.ltxml
lib/LaTeXML/Package/llncs.cls.ltxml
lib/LaTeXML/Package/lxRDFa.sty.ltxml
lib/LaTeXML/Package/mathtools.sty.ltxml
lib/LaTeXML/Package/natbib.sty.ltxml
lib/LaTeXML/Package/physics.sty.ltxml
lib/LaTeXML/Package/xcolor.sty.ltxml

This PR deals more consistently with comments, whether Tokens, digested or XML nodes, appearing in places we previously didn't expect them.
The function `IsEmpty` tests whether a tokens or list  is empty, ignoring comments, and is generally preferred over `scalar($x->unlist )`; `element_next($node), element_prev($node)` are usually preferred over `$node->previousSibling`.   Also, avoid splitting xml text nodes with comments, pushing them to the front.
Also, remove an obsolete form of `DefMathLigature`.

Comments welcome

---

lib/LaTeXML/Core/Definition/Conditional.pm
lib/LaTeXML/Core/Definition/Constructor.pm
lib/LaTeXML/Core/Definition/Expandable.pm
lib/LaTeXML/Core/Definition/Primitive.pm
lib/LaTeXML/Core/Definition/Register.pm
lib/LaTeXML/Core/Whatsit.pm
lib/LaTeXML/Global.pm
lib/LaTeXML/Package/TeX.pool.ltxml
lib/LaTeXML/Package/latexml.sty.ltxml
lib/LaTeXML/texmf/latexml.sty

This combines the tracing and profiling flags into a single bitmask, which reduces the number of lookups required (and we're usually not tracing or profiling).  This is a performance boost since it is happening frequently and at lower level.
Yes, magic numbers; but context should make them clear & the hassle (in Perl) of faking constants isn't worth it.

Tracing optimization

---

lib/LaTeXML/Common/Error.pm
lib/LaTeXML/Core/Definition/Conditional.pm
lib/LaTeXML/Core/Definition/Expandable.pm
lib/LaTeXML/Core/Document.pm
lib/LaTeXML/Core/Gullet.pm
lib/LaTeXML/Core/Mouth.pm
lib/LaTeXML/Core/State.pm
lib/LaTeXML/Core/Stomach.pm
lib/LaTeXML/Core/Token.pm
lib/LaTeXML/Core/Tokens.pm
lib/LaTeXML/Package/TeX.pool.ltxml
lib/LaTeXML/Package/pdfTeX.pool.ltxml
lib/LaTeXML/Package/pstricks.sty.ltxml

Given a bit more wisdom about gullet, after #2126, I couldn't resist another session with NYTProf for some optimizing... with some promising improvements.  A bit more to come.

More optimization

---

doc/manual/manual.tex

As noted by @davpoole in #2152, there is a typo in the manual that references an option which does exist.
This PR fixes the typo.

Fix #2152: Update 'splitxpath' => 'splitpath'

---

MANIFEST
lib/LaTeXML/Package/boxedminipage.sty.ltxml

As suggested in #2110, this implements the package boxedminipage by inputting the style file.

support for boxedminipage

---

MANIFEST
lib/LaTeXML/Package/marginnote.sty.ltxml

marginnotes are marginpars that (1) do not float and (2) have an optional argument to move them vertically.  (1) is the responsibility of CSS.  And as long as CSS is going to start moving them around, (2) probably doesn't make much sense.  The TeX package also provides a few commands to hook into styling a marginnote.

add support for marginnote.sty

---

lib/LaTeXML/resources/CSS/LaTeXML.css

This aligns rules to the baseline, resolving #1995.  It also provides default dimensions (otherwise, vrules end up with a width of text-indent).  Some other notes:
* hrule should be in vertical mode but isn't.  (I think that's the correct terminology: TeX put the hrule on its own line and subsequent text on another line; LaTeXML put everything on the same line.)
* I don't appear to have html.sty, so I'm not sure what html.sty.ltxml is trying to emulate.
* TeX.pool.ltxml claims that hrule and vrule can appear [as rules within an alignment/table](https://github.com/brucemiller/LaTeXML/blob/c3aea809d9b677b8237103f9166dfb43328e5d0f/lib/LaTeXML/Package/TeX.pool.ltxml#L2353).  I was unable to see this behavior in LaTeXML: all tabular rules were rendered via a ltx:td/@ltx:border attribute, not a …

align rules to baseline

---

lib/LaTeXML/Package/aa_support.sty.ltxml

This PR addresses placement and style of `\abstract` in aa class documents.
Fixes #2129
Fixes #2130 
Fixes #2131

Refine treatment of aa abstract

---

lib/LaTeXML/resources/XSLT/LaTeXML-block-xhtml.xsl

Add an empty <span class='ltx_tag ltx_tag_item'/> to itemization items w/o tag to get consistent placement
Fixes: #2158

Add at least an empty tag to itemization items

---

lib/LaTeXML/Package/TeX.pool.ltxml
t/encoding/ansinew.xml
t/encoding/applemac.xml
t/encoding/cp1250.xml
t/encoding/cp1252.xml
t/encoding/cp437.xml
t/encoding/cp437de.xml
t/encoding/cp850.xml
t/encoding/cp858.xml
t/encoding/cp865.xml
t/encoding/latin1.xml
t/encoding/latin5.xml
t/encoding/latin9.xml
t/fonts/abxtest.xml
t/parse/array_math.xml

make `\lnot` and `\neg` be OPERATOR rather than FUNCTION, which leads to better parsing & MathML.
Fixes #2163

Not a function

---

lib/LaTeXML/Package/aas_support.sty.ltxml

needed some `\expandafter` magic.
Fixes #2090

Fix \ion macro

---

lib/LaTeXML/Core/Document.pm
lib/LaTeXML/Package/comment.sty.ltxml

This PR fixes how comments are inserted into the XML, and enhances `comment.sty` to preserve the comments in the output.
Fixes #2087

Fixes comments, and comment.sty

---

lib/LaTeXML/Package/LaTeX.pool.ltxml
lib/LaTeXML/resources/CSS/LaTeXML-marginpar.css
lib/LaTeXML/resources/CSS/LaTeXML.css
lib/LaTeXML/resources/XSLT/LaTeXML-webpage-xhtml.xsl

This allows marginpars to float (in the CSS sense), so that they display in order instead of overlapping, fixing #2041.  LaTeXML-marginpar.css doesn't appear to mesh well with LaTeXML-navbar-left.css (for example `.ltx_page_main { width }` is determined by which is loaded last), so I've not tried to resolve that.  On the other hand, if someone is loading both, then they will probably want their own css file anyway.
The tex code I was using to test this out:
```tex
\usepackage{latexml}
\begin{lxNavbar}
\lxContextTOC
\end{lxNavbar}
\section{Section Title}
A small amount of text.\marginpar{first}\marginpar{second second second second}
A large amount of text. A large amount of text. A large amount of text. A large amount of text. A large amount of …
```

floating marginpar

---

lib/LaTeXML/Package/listings.sty.ltxml
lib/LaTeXML/resources/CSS/LaTeXML.css
t/alignment/listing.xml
t/slides/beamer.xml

Fixes #2067 in so far as non-breaking spaces are concerned.

use normal spaces with CSS white-space:pre instead of non-breaking spaces in listings

---

lib/LaTeXML/Post.pm

Fixes #2093 by setting the URI of postprocessing documents to their destination. This guarantees that calling e.g. `document(@imagesrc)` resolves relative URLs correctly, i.e., relative to the destination directory.

set URI to destination for postprocessed documents

---

lib/LaTeXML/Core/List.pm
lib/LaTeXML/Core/Whatsit.pm
lib/LaTeXML/Package/TeX.pool.ltxml

I was double-checking if our raw support for `tikz-qtree.sty` has improved (based on [a small example](https://github.com/brucemiller/LaTeXML/issues/341#issuecomment-821877053) from #341 ), and indeed it has!
The only catch was that due to the deeper interpretation, the conversion was running into `Fatal:perl:deep_recursion` fatal errors. I allowed more recursion in 3 locations, which then allowed the conversion to succeed.
Tested with a simple:
```
$ latexmlc test.tex --dest=test.html --includestyles
```
That minimal example tree now renders exactly as in the PDF - with the only exception of having the entire outer frame translated too far down. Tested with today's latexml master at 6143eb15bbbb435bcb0cf67544acac1c55e6b3e2
TeX example:
<details>
```tex …
```

allow deeper recursion for tikz diagrams

---

lib/LaTeXML/Core/Gullet.pm
lib/LaTeXML/Core/Token.pm

This PR skips spaces before reading the value of (pseudo) registers that take a token as value, such as `\textfont`.
Fixes #2097
Also removes an unneeded circular dependency which broke perl-critic.

Fix token register

---

lib/LaTeXML/Package/TeX.pool.ltxml

Fixes #2159 
Tested with
```tex
\usepackage{graphicx}
\graphicspath{  {subdir1/}, test/,  {subdir2/}  {subdir3/}
{subdirn/}  }
\end{document}
```
Result:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<?latexml searchpaths="/home/deyan/git/my-LaTeXML,/tmp"?>
<?latexml class="article"?>
<?latexml package="graphicx"?>
<?latexml graphicspath="/tmp/subdir1"?>
<?latexml graphicspath="/tmp/test"?>
<?latexml graphicspath="/tmp/subdir2"?>
<?latexml graphicspath="/tmp/subdir3"?>
<?latexml graphicspath="/tmp/subdirn"?>
<?latexml RelaxNGSchema="LaTeXML"?>
<document xmlns="http://dlmf.nist.gov/LaTeXML">
<resource src="LaTeXML.css" type="text/css"/>
<resource src="ltx-article.css" type="text/css"/>
</document>
```

refine regex for \graphicspath argument

---

lib/LaTeXML/Package/hyperref.sty.ltxml

Fixes #2125 
We had provisions to recognize `\usepackage[colorlinks]{hyperref}`, but no provision to recognize the option when passed in through `\hypersetup`.

respect colorlinks in \hypersetup

---

lib/LaTeXML/resources/XSLT/LaTeXML-inline-xhtml.xsl

When an `ltx:text` is given a `width` attribute (eg from `\makebox`), when it is converted to html's `span`, the width gets ignored since CSS doesn't allow width on inline elements. 
It would be tempting to have such constructors to create an `ltx:inline-block` instead of an `ltx:text`, but that also has a different content model and so introduces seemingly extraneous `ltx:p` elements, which seem unnatural.
This PR shifts the burden to the XSLT, since it is really CSS that has the "problem": When converting such an `ltx:text` to a `span`, if it has a `@width`, also add the class `ltx_inline-block`.   This seems to solve the immediate problem.
It also reveals a different one: that LaTeXML's sizes, which appear to be accurate within TeX's context, when re-expressed in HTML pts, with …

Make ltx:text->span add class=ltx_inline-block if given a width

---

lib/LaTeXML/Package/LaTeX.pool.ltxml
t/fonts/textsymbols.xml

Fixes #2122 .
Unicode seems to have dedicated circled characters for numbers 0 through 20, and the lower and upper English letters. This PR now uses them with `\textcircled`. For other cases, we continue to rely on the `U+20DD` combining character.
I am attaching a sample tex source and a screenshot of the HTML from a default Firefox view.
Still renders a bit odd, but maybe better in the long run?
I also tried to add some baseline math attributes, ensuring that circled numbers reach MathML as `<mn>` rather than `<mi>` elements. Feedback is most welcome.
<details>
```tex
\textcircled{0} \textcircled{1} \textcircled{2} \textcircled{3} \textcircled{4} \textcircled{5}
\textcircled{6} \textcircled{7} \textcircled{8} \textcircled{9} \textcircled{10} …
```

use Enclosed Alphanumerics for common \textcircled cases

---

lib/LaTeXML/Package/LaTeX.pool.ltxml
lib/LaTeXML/Package/TeX.pool.ltxml
t/ams/amsdisplay.xml

This PR fixes a couple of numbering issues with nested alignments and subequations.
Fixes #2055
Fixes #2105 
Fixes #2042
Fixes #2142 
(Actually, I'm not sure if it fixed #2142, or if it was already fixed; in any case it seems correct now)

Aligned numbers

---

t/003_unit_imagemagick.t

Quick follow-up to #2195, meant to pass on *any* working version of ImageMagick (by making weaker numeric assumptions)

weaken numeric test to pass with more ImageMagick versions

---

lib/LaTeXML/Package/LaTeX.pool.ltxml
lib/LaTeXML/Package/amsmath.sty.ltxml

This fixes #2083.  As noted there, several of the spacing commands have moved from AMSmath into LaTeX.

move spacing from AMSmath to LaTeX

---

lib/LaTeXML/resources/CSS/ltx-book.css

Some numbers crept into the ltx-book.css file that shouldn't be there and make validation to fail.

spurious characters in css file removed

---

lib/LaTeXML/Package/listings.sty.ltxml
t/alignment/listing.xml

This PR cherry-picks the best bits of @dginev and @xworld21 patches.  Apologies for all the round-about, but thanks for the patience & ideas.
This PR also adds full numbering tags to the lines in a listing, and gives them a type-name ("line"), so that they can be reasonably referenced (also by index), so hopefully provides the  tools to answer #2007.
Closes #2179, closes #2189, closes #2196, closes #2200.
Fixes #2178
Fixes #2007

Listings fix

---

lib/LaTeXML/Package/subcaption.sty.ltxml

This issue intersects an ar5iv report and my current deeper dive into figures/subfigures/minipages.
A minimal example was available at [ar5iv#31](https://github.com/dginev/ar5iv/issues/31#issuecomment-1700154030), excerpted here:
```tex
\usepackage{graphicx}
\usepackage{subcaption}
\begin{figure}
\centering
\begin{subfigure}[t]{0.49\textwidth}
\centering
\includegraphics[width=0.74\textwidth]{example-image-a}
\subcaption{} \label{fig:a}
\end{subfigure}
\caption{Test}
\end{figure}
\end{document}
```
It appears that our latexml use of `beforeFloat('subfigure',...` combined with the unconditional `\subcaption` code of `\edef\@captype{sub\@captype}` leads to setting an incorrect captype of `subsubfigure`, which leads to errors.
Reading the comments of …

attempt to guard the \@captype for \subcaption

---

lib/LaTeXML/Core/Array.pm
lib/LaTeXML/Package/graphics.sty.ltxml
lib/LaTeXML/Package/graphicx.sty.ltxml
lib/LaTeXML/Util/Image.pm

This PR fixes a couple of glitches processing `graphicx` images: the incorrect (but accepted) use of commas to separate viewport values; inconsistent up/downscaling of vector graphics images.
Fixes #2114

Image glitches

---

lib/LaTeXML/resources/XSLT/LaTeXML-bib-xhtml.xsl
lib/LaTeXML/resources/XSLT/LaTeXML-block-xhtml.xsl
lib/LaTeXML/resources/XSLT/LaTeXML-common.xsl
lib/LaTeXML/resources/XSLT/LaTeXML-epub3.xsl
lib/LaTeXML/resources/XSLT/LaTeXML-inline-xhtml.xsl
lib/LaTeXML/resources/XSLT/LaTeXML-meta-xhtml.xsl
lib/LaTeXML/resources/XSLT/LaTeXML-misc-xhtml.xsl
lib/LaTeXML/resources/XSLT/LaTeXML-para-xhtml.xsl
lib/LaTeXML/resources/XSLT/LaTeXML-structure-xhtml.xsl
lib/LaTeXML/resources/XSLT/LaTeXML-tabular-xhtml.xsl
lib/LaTeXML/resources/XSLT/LaTeXML-webpage-xhtml.xsl

This PR only contains a cleanup renaming (hopefully).
Motivated by the `context` and `mode` keywords in our XSLT files being too similarly vague to encounter in the same template, and trying to pin down more accurate names.
In the process I also moved `innercontext` to `inline`, since it was always set to the constant value of `'inline'`. I am even wondering if that needed a dedicated variable or a simple string would do?
Certainly more tweaking is possible here (e.g. now that we are claiming the param is a simple boolean toggle, it can be changed to using a boolean true/false). But it's a start resolve some of the naming difficulties I had.

Rename xsl context param to more targeted spansoup

---

lib/LaTeXML/Core/Mouth.pm

Fixes #2175
The regression is really subtle, so this PR definitely deserves a careful look-over. As Tim helpfully diagnosed in the issue, the underlying cause were the improvements from commit https://github.com/brucemiller/LaTeXML/commit/acaa51d9bdf4ae582c57f527fe34580290efac34 .
The remaining subtlety seemed to be revealed when babel.sty loads its english `.ini` file on a recent texlive (`babel-en.ini`). Every time that file read encounters a completely empty line, it seems to terminate the read early. Explaining *how* that happens is not something I can do with sufficient clarity at the moment, but it has to do with the interplay of `Gullet::readUntil`, `Mouth::readToken` and `Mouth::getNextChar`, where the `undef` from the empty line needs to be handled at just the right context point …

extra guards for empty lines for Mouth::readToken

---

lib/LaTeXML/Package/amsthm.sty.ltxml

Fix #2225. I'll update it if tests fail (tests are too slow on my machine!).

amsthm.sty.ltxml: ignore \thmnote, \thmnumber, \thmnote if arguments are empty

---

lib/LaTeXML/Package/framed.sty.ltxml
t/graphics/framed.xml
t/theorem/ntheorem.xml

Fix #2224, mostly. Remaining discrepancies:
- vertical spacing is different, but this seems unavoidable: as far as I can tell, CSS padding behaves differently than `\fboxsep`;
- LaTeXML does not indent the content, unless the box is at the start of an `<ltx:para>`; I presume this requires starting a new `<ltx:para>` for each box, but I promised a CSS only PR, and I am afraid of breaking something else.

replicate framed padding and border width

---

MANIFEST
lib/LaTeXML/Package.pm
lib/LaTeXML/Package/t5enc.def.ltxml

This seems to supply at least nominal support for Vietnamese characters and accents.
Fixes #2052

Initial support for Vietnamese

---

lib/LaTeXML/Package/TeX.pool.ltxml

Background: I was down a couple of different rabbit holes in debugging two almost-working Tikz diagrams, when I finally unwrapped the expansion onion to a discrepancy that had to do with a space given to an argument of `\let`, as in the minimal:
```tex
\def\set#1{\let#1=\foo}
\set{ \j} % this sets \j to the meaning of \foo, despite the space
```
And then I expanded it into my working test for pdftex:
```tex
\def\foo{foo}
\def\setA#1{\let#1=\foo}
\def\setB#1{\let #1=\foo}
\def\setC#1{\let  #1 =\foo}
\def\setD#1{\let    #1   = \foo}
\setA\a
\setB\b
\setC\c
\setD\d
test behind def: \a, \b, \c, \d
\let\e=\foo
\let \f=\foo
\let  \g =\foo
\let    \h   = \foo
test in plain sight: \e, \f, \g, \h
\bye
```
Every single one of these 8 macros expands to `foo` in the PDF. But variants `\c` and `\d` …

\let skips more spaces than documented

---

lib/LaTeXML/Package/babel_support.sty.ltxml

Fixes #2175
To quote Bruce from our discussion today: "this should buy us another couple of releases".
We may approach the question differently in a hypothetical world where latexml loads `latex.ltx` in its entirety.
For now, this PR extends the custom guards we have for `\bbl@switch`, which are hosted at `babel_support.sty.ltxml`, to also track the low-level behavior of updating `\cf@encoding` with concrete tokens, as needed by a babel language switch.
Hopefully CI passes on all older texlives, I have confirmed texlive 2022 and 2023 succeed.

emulate \cf@encoding transitions in \bbl@switch

---

lib/LaTeXML/Util/Test.pm
t/50_structure.t
t/80_complex.t
t/83_expl3.t

This PR is essentially a repeat on my first attempt in #2045, and is one way to interpret the sentiment I recently expressed in #2175 and #2204.
Namely, I suggest we temporarily only run expl3-related tests in continuous integration, allowing systems where latexml's expl3 emulation is broken to still have a clean/successful installation. Those are currently two tests - glossary and si. Also, this is specifically targeted to the `0.8.8` release of latexml.
For the next, `0.8.9` release, I think Bruce has shown some convincing prototypes where both the performance in loading expl3 can be improved, as well as the robustness in interpretation, but that will require some sweeping changes to the pool-related internals of Core processing.
P.S. Attached with taking this route would be a …

only run expl3-dependent tests in continuous integration

---

lib/LaTeXML/Common/Font.pm
lib/LaTeXML/Package.pm
lib/LaTeXML/Package/LaTeX.pool.ltxml
lib/LaTeXML/Package/TeX.pool.ltxml
lib/LaTeXML/Package/diagbox.sty.ltxml
lib/LaTeXML/Package/makecell.sty.ltxml
lib/LaTeXML/Package/pgfsys-latexml.def.ltxml
lib/LaTeXML/Package/wasysym.sty.ltxml
t/alignment/cells.xml
t/alignment/diagboxtest.xml
t/ams/mathtools.xml
t/fonts/cancels.xml
t/fonts/wasysym.xml
t/graphics/colors.xml
t/graphics/graphrot.xml
t/graphics/picture.xml
t/graphics/xcolors.xml
t/structure/enum.xml

The actual issue fix was a simple one liner in the pgf driver, but it turned up some inconsistency in color defaulting. The most interesting bit is the test for black in `TeX.pool` which affects how color adapts to a box being moved, copied, etc.  The rest is just consistency that `black` becomes `Black()`, and thus `#000000`.
Fixes #1945

Color tweaks

---

lib/LaTeXML/Core/Alignment.pm
t/ams/mathtools.xml
t/encoding/ly1.xml

Alignment cells should have *both* zero width and height to be considered empty (except for rule lines).
Fixes #1861

Empty cells

---

lib/LaTeXML/Package/LaTeX.pool.ltxml
lib/LaTeXML/Package/elsarticle.cls.ltxml

Hello! Well I sure found an interesting example of what happens when argument lists get shuffled unintentionally.
Apparently `\PassOptionsToPackage` and `\PassOptionsToClass` have never really worked, as their arguments had been swapped.
I landed on this discovery when diagnozing why [ar5iv:2310.13021](https://ar5iv.labs.arxiv.org/html/2310.13021) used AuthorYear citation styles rather than the Number style used in the PDF. The source revealed the lines:
```tex
% if you need to pass options to natbib, use, e.g.:
%     \PassOptionsToPackage{numbers, compress}{natbib}
% before loading neurips_2023
\PassOptionsToPackage{numbers, compress}{natbib}
% ready for submission
% \usepackage{neurips_2023}
\usepackage[preprint]{neurips_2023}
```
which appears to have been supplied by the neurips …

pass package options in the right order

---

lib/LaTeXML/Package/mn2e_support.sty.ltxml

I got pinged that this was missing and it seemed faster to make the PR than an issue.
mnras.cls has a recent addition of `\ion`, which I transferred as-is to the binding.
Will fix arXiv:2311.17062

add \ion for mnras.cls and friends

---

lib/LaTeXML/Package/xfrac.sty.ltxml

This was a very easy fix for arXiv:2301.13344 [log here](https://ar5iv.labs.arxiv.org/log/2301.13344), which wasn't finding `\graphicspath` during conversion.
As it turns out, xfrac.sty on texlive 2022 has the following line:
```tex
\RequirePackage{amstext,graphicx,l3keys2e,textcomp,xparse,xtemplate}
\ProvidesExplPackage{xfrac}{2022-06-22}{}
```
I think adding the latex 3 pieces is too much for now, but adding the more common LaTeX 2 entries should be smooth sailing.
The PR upgrades the arXiv article from Error to Warning severity (some unparsed math).

[minor] add required packages for xfrac

---

lib/LaTeXML/Package/LaTeX.pool.ltxml
lib/LaTeXML/Package/hyperref.sty.ltxml
lib/LaTeXML/Package/thmtools.sty.ltxml

By the time I had checked the latest reported problem in [ar5iv#412](https://github.com/dginev/ar5iv/issues/412) I had it fixed, so filing the two extra `Digest` calls in this PR.
Separately, I am also filing a small softening of the `\hypertarget` error of inserting an `ltx:anchor` to a Warning, since it turns out when it occurs it can be really frequent (100+ times). We stumbled onto that when converting the [Linear Algebra textbook by Hefferon](https://hefferon.net/linearalgebra/) this week. I will probably file an issue to bookkeep some of the more subtle problems there, but this one seems clearcut.

Digest some keys in thmtools; avoid error cascades in \hypertarget 

---

lib/LaTeXML/Package/LaTeX.pool.ltxml
t/alignment/colortbls.xml
t/babel/page545.xml
t/complex/si.xml
t/graphics/picture.xml

This PR fixes the effects of `\centering` (and related) leaking outside their groups.
Fixes #1712

Fix centering

---

lib/LaTeXML/Core/Tokens.pm
lib/LaTeXML/Package/LaTeX.pool.ltxml
lib/LaTeXML/Package/listings.sty.ltxml

Fixes [ar5iv#393](https://github.com/dginev/ar5iv/issues/393), 
Minimal motivating example:
<details>
```tex
\usepackage{makeidx}
\makeindex
\def\w{w}
\begin{itemize}
\item A\index{Choice Principle!({{\sf AC$^\{<\w}_\w$}})}
\item B\index{Choice Principle!({{\sf BC$^{<\w}_\w$}})}
\end{itemize}
\printindex
\end{document}
```
</details>
---
In a way this is an edge case problem in LaTeX documents which have an actual error in the argument of the `\index` command. The arXiv example is a particularly egregious case, where a big portion of a 70 page manuscript goes haywire due to a single malformed index argument.
pdflatex is largely immune to such problems, as the argument to `\index` is neutralized via `\@sanitize` and written in the auxiliary `.idx` …

respect \@sanitize guard for \index 

---

lib/LaTeXML/MathParser.pm
lib/LaTeXML/Package.pm
lib/LaTeXML/Package/LaTeX.pool.ltxml
lib/LaTeXML/Package/TeX.pool.ltxml
lib/LaTeXML/Post/MathML.pm
lib/LaTeXML/resources/CSS/LaTeXML.css
t/alignment/listing.xml
t/alignment/plainmath.xml
t/babel/numprints.xml
t/complex/si.xml
t/daemon/formats/lexmath.xml
t/fonts/mathcolor.xml
t/math/ambiguous_relations.xml
t/math/compact_dual.xml
t/math/declare.xml
t/theorem/amstheorem.xml
t/theorem/latextheorem.xml

First step, clean up erroneous, missing and/or redundant font declarations which lead to erroneous or redundant mathvariant declarations in the MathML. Typically happens when the appropriate font is not propagated while synthesizing symbols.
Then add classes, like `ltx_mathvariant_italic`, for cases where the mathvariant cannot be handled by remapping the Unicode.
Fixes #2021 
Fixes #2051

Mathvariant fixes

---

lib/LaTeXML/Package/algorithm2e.sty.ltxml

Fixes https://github.com/dginev/ar5iv/issues/423
Since algorithm2e.sty is emulated in Perl, with some very special considerations for the ends of lines, I think this is the best way to also support the `\DontPrintSemicolon` without losing the line endings.
There is probably a possible refactor that relies on the native interpretation more, but that could be deferred...
Running example:
```tex
\usepackage{algorithm2e}
\begin{algorithm}
\DontPrintSemicolon
line 1
line 2\;
line 3\;
\For{$t = 1, 2, \ldots, T$} {
line 1\;
line 2\;
line 3\;
}
\end{algorithm}
\end{document}
```

emulate \DontPrintSemicolon in algorithm2e.sty

---

Makefile.PL
lib/LaTeXML/Package.pm
lib/LaTeXML/Util/Pathname.pm

Better fix for #2293: after adding some Windows-specific escaping, kpsewhich can be called with arbitrary file names, even with special characters, and so `pathname_is_nasty` can be removed altogether. This supersedes #2295, #2294.
The `if (open(my $resfh, '-|', ...))` block can definitely be useful elsewhere. In Util::Pathname, there are two backticks left, and there are a few other not-quite-safe system calls in other modules. However, @brucemiller @dginev you should decide if and how to make that happen, e.g. a new Util module maybe?

use Win32::ShellQuote for kpsewhich

---

lib/LaTeXML/Core/Parameter.pm
lib/LaTeXML/Package/pdfTeX.pool.ltxml

Minimal fix for https://github.com/arXiv/html_feedback/issues/258
The main issue was a need for adding the `SkipSpaces` parameter between two `OptionalMatch:` parameters in `\pdfliteral`, so that the arguments get read in appropriately, and then ignored (for now).
The minimal test snippet is:
```tex
\pdfliteral direct {2 Tr 0.5 w}%
test%
\pdfliteral direct {0 Tr 0 w}%
\end{document}
```
This kind of pattern would benefit from a test, but I think that can wait until we actually try to emulate some of the directives (e.g. turning `test` bold here).

SkipSpaces between two OptionalMatch arguments in \pdfliteral

---

README.pod

The badges in the README had URLs that no longer function, minor fixes:
- our CI workflow is no longer named CI, so we need 2 badges - one for Linux, one for Windows
- the CC0 license badge can simply point to the official URL, the old one has a "bad signature" today

fix URLs for badges in the README

---

lib/LaTeXML/Package/pgfmath.code.tex.ltxml

Added in the hope of fixing https://github.com/dginev/ar5iv/issues/431 , but it only resolved the first error in that issue.
Minimal example enabled by the PR:
```tex
\usepackage{pgf}
\pgfmathparse{height("Some Lovely Text")} \pgfmathresult
\pgfmathsetmacro\MathAxis{height("$\vcenter{}$")}
\MathAxis
\end{document}
```

pgfmath parse for width,depth,height

---

bin/latexmlpost
lib/LaTeXML.pm
lib/LaTeXML/Common/Config.pm
lib/LaTeXML/Post/MathML.pm

Fixes #1941 . At least it allows it to be fixed, via a new option.
Here is a draft following some offline discussions on allowing a customization switch for preferring zero-width space (U+200B) over invisible times (U+2062) in implied `<mo>` elements.
The PR minimally touches up the character in post-processing, via the `MathML::stylizeContent` sub.
An easy test is:
```
$ latexmlc 'literal:2x' --whatsin=math --dest=test.html \
--noinvisibletimes
```
I have exposed the option in latexmlpost and latexmlc. But not yet in latexmlmath (maybe later).

--noinvisibletimes: choose zero-width space over invisible times

---

lib/LaTeXML/Core/Alignment.pm
lib/LaTeXML/Core/Definition/Constructor.pm
lib/LaTeXML/Core/Parameter.pm
lib/LaTeXML/Core/Parameters.pm
lib/LaTeXML/MathParser.pm
lib/LaTeXML/Package/LaTeX.pool.ltxml
lib/LaTeXML/Package/TeX.pool.ltxml
lib/LaTeXML/Package/import.sty.ltxml
lib/LaTeXML/Package/lipsum.sty.ltxml
lib/LaTeXML/Package/listings.sty.ltxml
lib/LaTeXML/Package/multirow.sty.ltxml
lib/LaTeXML/Package/ulem.sty.ltxml
lib/LaTeXML/Package/xy.tex.ltxml

This PR lifts a first small selection of the unfortunate Fatal regressions in the arXiv sandboxes with the latest master:
1. Add a guard for `\xyoption` to avoid loading the same option twice (as inspired by the original sty, which also does so)
2. allow more recursion in deeply nested argument reads, even if a true infinite loop lurks behind that - the final Fatal printed gets a more informative trace in the genuine loop cases.
3. add a guard in `revertScript` to only call `->defined_as` on Token objects (and not Tokens).
4. recognize and guard the advanced use of `\multirow` where the height param can be a negative or fractional number. Not implemented yet, but won't Fatal anymore.
5. Fix a surprisingly common regression with xparse and lipsum conflicting (really my hacky expl3 "pool" …

Sandbox run 01.2024, fixes for Fatal cases (10)

---

lib/LaTeXML/Post/MathML.pm

A bit of an unfortunate follow-up to #2303 , based on observing that we get the default `0.27...em` spacing for any zero-width Unicode chars not yet in the MathML operator dictionary.
See the [discussion in mathml-core](https://github.com/w3c/mathml-core/issues/209#issuecomment-1924012036) for more details, as well as [an example codepen](https://codepen.io/dginev/pen/zYbjGNj).
Setting the lspace/rspace attributes explicitly feels like we are reverse-patching the defaults, but without the rendering looking normal, it seems that it causes more harm than good to switch away from invisible times.

Set lspace and rspace for zero-wdith space mo 

---

lib/LaTeXML/Common/Font.pm
lib/LaTeXML/Common/Object.pm
lib/LaTeXML/Core/List.pm
lib/LaTeXML/Core/Parameter.pm
lib/LaTeXML/Core/Tokens.pm
lib/LaTeXML/Core/Whatsit.pm
lib/LaTeXML/Package/IEEEtran.cls.ltxml
lib/LaTeXML/Package/LaTeX.pool.ltxml
lib/LaTeXML/Package/TeX.pool.ltxml
lib/LaTeXML/Package/listings.sty.ltxml
lib/LaTeXML/Package/natbib.sty.ltxml
lib/LaTeXML/Package/pgfmath.code.tex.ltxml
lib/LaTeXML/Package/xcolor.sty.ltxml
lib/LaTeXML/Post/MathML.pm

This PR is a (final) follow-up to the just merged #2309 .
I address another handful of Fatal issues, and one minor binding issue:
- allow deeper recursion in digesting reads of parameters
- allow deeper recursion in stringify
- Guard against infinite loops in complex listings
- The examples were in cases that deal with `QUOTED_RE`, but I think there are more general possible pitfalls related to `colnum` not getting incremented and sanity-checked in every possible arm of the loop conditional.
- Finding all of the tricky corner cases is a little hard without a deep dive, so I added a distinctive Error message. We can collect all papers exhibiting the issue after a rerun and build a tougher test suite.
- IEEEtran.cls.ltxml needs to support an optional arguments for its list envs, and also …

Sandbox Fatal fixes 01.2024, round 2

---

lib/LaTeXML/Package/hyperxmp.sty.ltxml
lib/LaTeXML/Package/nicefrac.sty.ltxml
lib/LaTeXML/Package/ntheorem.sty.ltxml
lib/LaTeXML/Package/pdfpages.sty.ltxml
lib/LaTeXML/Package/rotating.sty.ltxml
lib/LaTeXML/Package/sidecap.sty.ltxml
lib/LaTeXML/Package/srcltx.sty.ltxml

I was burning the midnight oil listening to interesting talks...
And happened to walk through the [error:undefined:\ifthenelse](https://corpora.mathweb.org/corpus/arxmliv/tex_to_html/error/undefined/%5Cifthenelse) CorTeX reports. Then I noticed that a number of the articles should have already had the macro supported.
It turns out that some of our bindings should have required `ifthen.sty`, as their raw `.sty` counterparts do - but didn't, since the Perl side never needed the dependency. However, in arXiv, some authors rely on these transitive dependencies being in place and don't load `ifthen` directly. So for their sake, here is a simple PR adding them in.

consistent ifthen.sty dependence in bindings

---

lib/LaTeXML/Package/subfiles.sty.ltxml

Fixes #2323
Our subfiles.sty binding is a little brave/simple and it only goes so far. To fix the reported issue, I think the key bit was processing the main/outer `{document}` as usual, while only redefining the environment on secondary uses (in the dependent files).
So I deferred the redefinition, allowing the reported example to work as expected. An even nicer test is to move the algorithm to a standalone file and use a main.tex:
```tex
\usepackage{subfiles}
\usepackage[ruled]{algorithm2e}
\subfile{alg}
\subfile{alg}
\subfile{alg}
\end{document}
```
which is a little closer to the package intention.

subfiles.sty redefines only secondary {document} uses

---

lib/LaTeXML/Package/epsf.sty.ltxml
lib/LaTeXML/Util/Image.pm

Fixes an unfortunate Fatal in arXiv:0710.5511
It is also curious to note that some diagnostic "die" messages from perl in post-processing go unnoticed in the arXiv build logs, as they do not use the latexml error-reporting API. So this paper was in the "no_messages" category. As in:
```
Illegal division by zero at /home/deyan/perl5/lib/perl5/LaTeXML/Util/Image.pm line 225.
Status:conversion:3
```
I also tracked down the underlying reason for the bug, which was a malformed `viewport` option - there was a missing `ToString` for serializing the optional argument of `\epsfbox` from `epsf.sty.ltxml`. I also noticed this macro is used in `epsfig.sty.ltxml`, but decided not to touch that in this PR.

avoid unexpected division by zero in image transform

---

bin/latexmlc

While checking #2338 I noticed that the `status_code` field was not being set for latexmlc calls that used a daemonized server.
It helps to have that set, so that latexmlc can choose a correct exit status.

add status_code field for latexmls-based calls

---

lib/LaTeXML/Post/MathML.pm

Use em rather than percent for MathML mo minsize, maxsize to avoid interpretation issues.
Also, tweak operator dictionary assumptions about what browsers will assume is stretchy.

Use em rather than percent for MathML mo minsize, maxsize

---

lib/LaTeXML/Engine/TeX_Macro.pool.ltxml
lib/LaTeXML/Engine/TeX_Math.pool.ltxml

Spotted while porting. There appear to be two \expandafter definitions following each other. 
As the first one wasn't getting used (immediately overwritten by the second), this PR removes it for clarity.

remove redundant \expandafter definition

---

lib/LaTeXML/Common/Font.pm
lib/LaTeXML/Common/Font/Metric.pm
lib/LaTeXML/Core/Definition/CharDef.pm
lib/LaTeXML/Core/State.pm
lib/LaTeXML/Engine/LaTeX.pool.ltxml
lib/LaTeXML/Engine/TeX_Character.pool.ltxml
lib/LaTeXML/Engine/TeX_Fonts.pool.ltxml
lib/LaTeXML/Engine/TeX_Math.pool.ltxml
lib/LaTeXML/Engine/TeX_Paragraph.pool.ltxml
lib/LaTeXML/Engine/plain.pool.ltxml

This PR continues the previous TeX-pool reorg PR in preparation for more extensive refactoring.
* move several helper functions and ligature patterns to more appropriate "Engine" modules
* recognizes more font names
* more accurate initialization of various `\mathcode`, `\sfcode`
* simulate TeX-plain's register allocation better.

Rearrangements

---

lib/LaTeXML/resources/XSLT/LaTeXML-structure-xhtml.xsl

A bit of a minor tweak that makes the moderncv.cls output capable of handling a simple plain-text position (originating in the `\title` macro). The previous version was expecting a multiline construct in a `\vbox`, which is a bit too specific.
Funny story how I stumbled on it...

update xsl rule for moderncv personal position/title

---

lib/LaTeXML/Package/amsmath.sty.ltxml

Fixes #2383 . Quite subtle, but I think I got it - I can make the minimal example from the issue into a test if preferred.
Details: The key problem was that when the `->unread` of a `{` happened, the *actual* aligned state got modified, rather than the "safely neutralized" local state, which appears to be the primary purpose of this parameter type.

Extra safety when unreading alignment-related characters for \aligned

---

lib/LaTeXML/Common/Color.pm

Fixes #2407 
The problem was that when a base model is grayscale, a `mix` operation with `rgb` would remain in the base model - i.e. remain in grayscale. So when `mix` or `add` executes, the "richer" color model ought to be used.
Suggestions welcome if my code should be structured better, I almost made a new `sub` to hold the model-switching logic. Are there more places that could benefit from this treatment?

avoid using grayscale base when mixing richer colors

---

lib/LaTeXML/Core/KeyVals.pm

There are more subtle refactors and updates possible in KeyVals, but here is a PR that cleans up a couple of the more obvious pieces which are now outdated.
[Found while porting]

cleaning up a few outdated KeyVals corners

---

lib/LaTeXML/Package/mathtools.sty.ltxml

Fix incorrect conversion of mathtools symbols like \coloneq and \Coloneq

---

lib/LaTeXML/Engine/LaTeX.pool.ltxml
lib/LaTeXML/Package.pm

Fixes #2403 
With Bruce's help, I zeroed in on the cause of the issue, namely `\par@in@bibliography`. That code, which defensively auto-opens a `\bibitem`, recognizes too few of the legitimate cases with macro use (as described in the issue).
Since it is rather high difficulty to both handle "sloppy" uses of `{thebibliography}` as well as the advanced macro uses before a real `\bibitem`, this PR resigns to undoing the error after it is caused.
Namely, this first stab suggests to check in the `afterDigest` hook of `\lx@bibitem` whether the previous recorded box was an _empty_ use of `\bibitem`. In the case it was, the assembled previous box is pruned from the digested list, and its `RefStepID` is reused.
Seems to work well on the few cases I tried, open to adjustments.

prune an empty \bibitem when auto-opened without need

---

lib/LaTeXML/Engine/TeX_Glue.pool.ltxml
lib/LaTeXML/Engine/TeX_Kern.pool.ltxml

Simplify `\lastskip` (and also simlar `\lastkern`); as mentioned in last comment in #2423. The code was correct but hadn't been cleaned up after development.

Simplify \lastskip,\lastkern (suggested by D.Ginev)

---

t/80_complex.t

Fixes #2427 
This may be a change in the packaging of texlive, I am unsure. I would have assumed our texlive 2021 CI would also fail due to the various `.sty` dependencies not being present, but it succeeds?
To reproduce the reported error on Ubuntu (with texlive 2023), it takes:
```bash
$ sudo apt remove texlive-science
```
With this PR the test is gracefully skipped:
```
$ make test TEST_FILES=t/80_complex.t 
PERL_DL_NONLAZY=1 "/usr/bin/perl" "-MExtUtils::Command::MM" "-MTest::Harness" "-e" "undef *Test::Harness::Switches; test_harness(0, 'blib/lib', 'blib/arch')" t/80_complex.t
t/80_complex.t .. 5/15 # Skip: Missing requirement algorithm.sty for t/complex/figure_mixed_content
t/80_complex.t .. 11/15 # Skip: Missing requirement siunitx.sty for t/complex/si
t/80_complex.t .. ok     
All …
```

Explicit test requirements of figure_mixed_content 

---

lib/LaTeXML/Package/latexml.sty.ltxml

Encountered during the mega discussion in #2392 .
Sad, unfortunate, etc.

typo that disabled magnify option of latexml.sty

---

lib/LaTeXML/Core/Document.pm
lib/LaTeXML/Core/List.pm
lib/LaTeXML/Core/Whatsit.pm
lib/LaTeXML/Engine/LaTeX.pool.ltxml
lib/LaTeXML/Engine/TeX_Glue.pool.ltxml
lib/LaTeXML/Package.pm

This PR provides an option `toAttribute` to `DefConstructor,DefEnvironment` (and `Whatsit`s generally) to customize the conversion of a whatsit to an attribute value; its sytax is analogous to that of the `reversion` option, being a sub or string, possibly containing `#1..`. 
This is useful for objects which need the flexibility of a `Whatsit` (as opposed to simple `Box`) but which are sometimes placed in an attribute value that ends up in the text (or html) of the conversion; In those cases, the value should contain neither XML, nor the TeX reversion (as `toString` typically does). The motivating example is `\hskip`.
The `setAttribute` method of `Document`, when given an object reference as value, will use `toAttribute` to turn it into a string, but we need to be careful *not* to use …

To attribute

---

lib/LaTeXML/Package/natbib.sty.ltxml

Very minimal, fixes  https://github.com/arXiv/html_feedback/issues/2651
The scarier question is "how do we catch all of these DefRegister subtleties in general, in all bindings?"
Minimal snippet:
```tex
\usepackage{natbib}
\bibsep.9ex plus.1ex minus.05ex
\end{document}
```

minor: \bibsep is a glue register

---

lib/LaTeXML/Engine/LaTeX.pool.ltxml

Fixes #2221 .
The unfortunate aspect is that the example reported in the issue identifies only a surface symptom problem, where `\typeout` was being too eager with expanding its argument before printing. But isn't otherwise related to the deeper issues related to changes.sty loads.
Although I suspect the main work of improving core interpretation will improve that front.

More precise expansion for \typeout

---

lib/LaTeXML/Engine/LaTeX.pool.ltxml

I trusted the diagnostic in #2453 and changed the respective parameter type to one emulating `\edef` expansion.
Quick and simple PR.

Fixes #2453

---

lib/LaTeXML/Package/pgf.sty.ltxml
lib/LaTeXML/Package/pgfsys-latexml.def.ltxml

The change guarantees that `\XC@mcolor` is updated after color/xcolor are loaded, but also before finishing loading PGF, as opposed to at the end of the preamble. This also improves the usage of `\XC@mcolor`: in principle, other packages may be adding stuff to it, so it should be extended rather than redefined.
This fixes #2398, and hopefully does not break anything.

update \XC@mcolor in pgf.sty rather than pgfsys-latexml.def

---

lib/LaTeXML/Package/pgfsys-latexml.def.ltxml

Fix #2476. It doesn't fix `--pictureimages` in general: it only makes it compile *something* successfully. Unfortunately, the output is cropped the wrong way, but that's a different issue altogether.

omit \lxSVG@closescope in reversion

---

lib/LaTeXML/Util/Pathname.pm

Small optimization to `build_kpse_cache`; seemingly worthwhile since it's invoked on every run.

Fold 2 calls to kpsewhich; avoid regexp in tightest loop

---

lib/LaTeXML/Core/State.pm

Patch following discussion in #2527.  If we assign "inplace", with an actual value (as opposed to clearing), and there is no previous assignment, we'll assign globally. A reasonable default, if we end up ever needing the feature.

If assigning 'inplace', and there's a value, assign globally

---

lib/LaTeXML/Package/pgf.sty.ltxml

Part two of #2401 (to fully fix #2399): the quick commands *by definition* must not alter the bounding box. They do this by altering `relevantforpicturesize`, so this depends on the other PR to actually have an effect. This changes how some of Silviu's test are rendered (for the better) although plenty of stuff is still broken.
As far as I can tell, the initial implementation of PGF was extremely conservative about stuff being drawn outside of the SVG bounding box, hence the disabling of `relevantforpicturesize` and the redefinition of the quick commands. I don't think this is necessary anymore.

restore native PGF quick commands

---

lib/LaTeXML/Package/pgfsys-latexml.def.ltxml

Fix #2376 for PGF/TikZ.
The [commit that removed `@viewBox`](https://github.com/brucemiller/LaTeXML/commit/b1d4af1958c1e1e0f222b3e3deb933e04a6e3b92 ) said 'AVOID scaling, in particular viewBox so that text size matches containing document'. I can't quite tell what issue was being addressed: if `@viewBox` and `@width`, `@height` agree, no scaling happens. Rather, having the correct `@viewBox` *enables* CSS to change width and height, and that can only happen intentionally. So I am guessing this PR is fine.

restore viewBox in pgf pictures

---

lib/LaTeXML/Core/Alignment.pm

Following up on https://github.com/brucemiller/LaTeXML/pull/2488#discussion_r2001739762, simply record `@rowdepths` among the data collected by Alignment.

add @rowdepths to Alignment

---

lib/LaTeXML/Package/pgfsys-latexml.def.ltxml

This PR implements the `baseline` keyword option of pgf. It is basically #2477, but directly implements the baseline adjustment using CSS `vertical-align`, rather than usurping the `imagedepth` attribute. All the debugging was done by @xworld21 *Thanks!!!*
Closes #2477

Implement pgf baseline

---

lib/LaTeXML/Package/pgfsys-latexml.def.ltxml

A slight correction now, so we're all on the same page. When the `baseline` pgf keyword is used,  it provides an *alternative* baseline to `\pgf@picminy', rather than adding to it; `\pgf@shift@baseline` defaults to `\pgf@pixminy`. Thus, when we set the `vertical-align`, we use the difference `miny-shift`, rather than the `shift`. (The shifted circle was deceptive, due to symmetry).
This is a correction to #2535
Oh! And I semi-accidentally snuck in @xworld21's baseline adjustment to the pgf alignments. Thanks!
Attn: @xworld21

Fix use of \pgf@shift@baseline

---

lib/LaTeXML/Engine/BibTeX.pool.ltxml
lib/LaTeXML/Engine/LaTeX.pool.ltxml
lib/LaTeXML/Package/amsrefs.sty.ltxml
lib/LaTeXML/Package/cases.sty.ltxml
lib/LaTeXML/Package/dcolumn.sty.ltxml
lib/LaTeXML/Package/listings.sty.ltxml
lib/LaTeXML/Package/mathtools.sty.ltxml

This PR adjusts calls to `UnTeX` to  inhibit-linebreaks when used to create Tokens for further TeX processing; particularly when used in a context where `%` might not even trigger a comment, like `listings`. (A perhaps unfortunate API design, requires an extra flag in such cases).
Fixes #2553

Be careful to inhibit-linebreaks in UnTeX 

---

lib/LaTeXML/Post/MathML/OperatorDictionary.pm
t/post/simplemath-post.xml
t/post/simplemath.xml

I noticed some typos in the MathML operator dictionary code and fixed them.
To be sure, I added a couple of artificial tests in t/post/simplemath.xml to verify that the code is working as intended (e.g. now `&&` is correctly recognised as binary operator, so it does not get lspace/rspace attributes).

some MathML operator dictionary fixes and tests

---

lib/LaTeXML/Package/import.sty.ltxml

Fixes [arXiv:2103.14899](https://ar5iv.labs.arxiv.org/html/2103.14899), reported in [ar5iv:535](https://github.com/dginev/ar5iv/issues/535).
The concrete use example was:
```tex
\subimport{./}{Main/Tex/01_introduction}
\subimport{./}{Main/Tex/02_related_works}
\subimport{./}{Main/Tex/03_proposed}
```
The issue was particularly visible when using the `.zip` input to latexml (appending the raw `.` char was invalidating the unpacked sandbox path, hence all relative imports were failing).
A bit of care to always use a path separator improves the arXiv article to Warning status.

robust path join in import.sty.ltxml

---

doc/site/index.tex

Motivating discussion from the .deb maintainers here:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1106715
This would also need a live site rebuild (by @brucemiller )

[site] switch to transitive dependency on libxml2 and libxslt1.1 for Debian

---

lib/LaTeXML/Engine/Base_Utility.pool.ltxml
lib/LaTeXML/Engine/LaTeX.pool.ltxml

Fixes #1929, as well as [ar5iv#174](https://github.com/dginev/ar5iv/issues/174)
A simple add-on for binding `\AND` also adresses the ~30 reports in arXiv resembling [html_feedback#1284](https://github.com/arXiv/html_feedback/issues/1284)
The PR is a spiritual successor to Tom's #1937. In this attempt, I tried to achieve the minimal goals of:
- defer frontmatter digestion to `\maketitle` (accumulating the tokens until then)
- mark certain frontmatter as replacable instead of extensible (to avoid duplicated entries, e.g. `\title`).
- bind `\And`, `\AND` in the common LaTeX kernel to compensate for the limited `\@maketitle` emulation. I also realized emulating fully isn't actually a nice solution here, as they often get bound to `\end{table} ... \hfill ... \begin{table}` which isn't really …

Defer digesting frontmatter to \maketitle

---

lib/LaTeXML/Package/tikz.sty.ltxml

This is an oddball PR in need of extra eyes+feedback. It is motivated by [arXiv/html_feedback#3723](https://github.com/arXiv/html_feedback/issues/3723), which discusses arXiv:2203.00837v4.
The exact technical issue reduces to:
```tex
\usepackage{tikz}
\begin{tikzpicture}[align=center]
\node (1) {example};
\end{tikzpicture}
\end{document}
```
which throws an error in latexml (and is fine in pdflatex):
```
latexml (LaTeXML version 0.8.8; revision a23fe9af) processing test.tex
Error:undefined:\pgfmathresult The token T_CS[\pgfmathresult] is not defined. at test.tex; line 5 col 0
Warning:expected:<number> Missing number (Dimension), treated as zero. at test.tex; line 5 col 0
```
The code that deals with this curious macro is in …

Lift \tikz@align@temp and define \pgfmathresult as 0.0

---

lib/LaTeXML/Util/Pathname.pm

While I was looking at Windows things, I remember that LaTeXML is currently broken on Cygwin. This PR unbreaks it, although it comes with a big caveat: it assumes that kpsewhich is also a Cygwin binary.
Also, I was wrong to use Win32::ShellQuote on NetWare. Not that anybody was complaining.

treat Cygwin as Unix, do not use ShellQuote on NetWare

---

MANIFEST
lib/LaTeXML/Package/pgfkeys.sty.ltxml
lib/LaTeXML/Package/pgfmath.sty.ltxml
lib/LaTeXML/Package/pgfrcs.sty.ltxml

These are simple top-level bindings for the already supported pgf internals in question.
Recently spotted this in the [arXiv:2508.00812 log](https://arxiv.org/html/2508.00812/__stdout.txt).
A simple test snippet is:
```tex
\usepackage{pgfmath}
\pgfmathapproxequalto{0.15}{0.1499999999}\pgfmathresult
\pgfmathapproxequalto{0.15}{0.144}\pgfmathresult
\end{document}
```

bindings for pgfkeys, pgfmath, pgfrcs

---

lib/LaTeXML/Common/Config.pm

This was an oversight for a rare kind of input organization such as:
```
mydocument/00README.json
mydocument/main/main.tex
mydocument/sections/section-1.tex
mydocument/sections/section-2.tex
mydocument/figures/figure-1.png
...
```
With the invocation
```
latexmlc --whatsin=directory mydocument/
```
The `00README.json` will specify the path to the `main.tex` as the top-level file, and while the `sourcedirectory` was being correctly updated to `mydocument/` that wasn't actually added to the search paths. So when a conversion starts at `mydocument/main/main.tex`, an `\input{sections/section-1}` will no longer have visibility at the level above.
Simple fix, just add a directory input to the search paths -- in a way it is obviously correct.

Add directory on whatsin to the search paths
