brucemiller/LaTeXML

bin/latexmlfind, doc/manual/manual.tex, lib/LaTeXML/Core/Definition/Constructor.pm, lib/LaTeXML/Core/Document.pm, lib/LaTeXML/MathParser.pm, lib/LaTeXML/Package.pm, lib/LaTeXML/Post/MathML.pm, lib/LaTeXML/Util/Pathname.pm, lib/LaTeXML/resources/XSLT/LaTeXML-webpage-xhtml.xsl, tools/latexmllint
Here's those spelling errors, Bruce.  (not that they bother me, but I wanted to practice doing something... =)
=> pedantic spelling fixes (lintian complained)

lib/LaTeXML/Core/State.pm, lib/LaTeXML/Package/eTeX.pool.ltxml
Improve the way frame depth detection is currently handled.
=> Feature enhanced framedepth

lib/LaTeXML/Package/LaTeX.pool.ltxml
Allow LaTeXML to handle bbl if not all needed bib files are available.
=> Feature enhanced bibliography

lib/LaTeXML/Package/LaTeX.pool.ltxml
I added the definition for \loop and for all the \newcounts, \newdims, \newifs etc. I found in latex.ltx. 
I also added some very short macros that seemed like aliases suchs \dischyph=\- .
=> Upgrades to LaTex.pool.ltxml

lib/LaTeXML/Common/Error.pm, lib/LaTeXML/Core/State.pm, lib/LaTeXML/MathParser.pm
Apply colors to STDERR-logging in order to improve clarity.
=> Feature colored logging

lib/LaTeXML.pm
As said, removing some unneeded code from the high-level driver, as it arguably has no effect at all by now.
Also removed some trailing whitespaces, my editor does that automatically now.
=> Sanitize is essentially cruft by now

lib/LaTeXML/Util/Pack.pm
The scenario here (and I will add a second pull request for a different bug in this example) is in the archive input mode:
```bash
latexmlc bundle.zip --dest=test.html
```
```tex
% main.tex
\input{preamble}
Some content
\end{document}
```
and 
```tex
% preamble.tex
```
The current Util::Pack behavior will give the highest likelihood to be a main file to the source containing the ```\documentclass``` macro. This pull request monitors the ```\input``` and ```\include``` macros found in the sources and maintains a list of vetoed files that were found as arguments. It's still imperfect, but made a real-world example (from an Authorea user) work successfully.
I'm attaching the [bundle.zip](https://github.com/brucemiller/LaTeXML/files/241735/bundle.zip) …
=> Whatsin archive: able to veto TeX sources used as inputs

lib/LaTeXML/Post/OpenMath.pm
=> om:FOREIGN does not exist; should be om:OMFOREIGN

lib/LaTeXML/Common/Error.pm
=> Use lean generation of Fatal messages for timeouts

lib/LaTeXML/Package/TeX.pool.ltxml
This was a rather common Fatal I was noticing, and it has an obvious patch. Any side-effects I am not noticing?
=> Defend against undef tokens in DefToken

README.pod
I am now a badge addict. 
You can check how this looks on GitHub by visiting the README on the pushed branch here:
https://github.com/dginev/LaTeXML/blob/modern-badge-showoff/README.pod
You'll make me extremely happy if you decide to merge here, irrational as it is.
=> Hype-compliant readme badges

lib/LaTeXML/Common/Config.pm
* Minor cleanup of some option defaults
* Restructured the POD to follow the new structure of the latexmlpost POD
* Copied over all option docs I could find from latexmlpost and latexml
* Proofread
Probably not perfect, but hopefully exhaustive.
=> Fixes #612 ; Full update to Common::Config doc

lib/LaTeXML/Util/Test.pm, t/daemon/formats/citation.spec, t/daemon/formats/citationraw.spec
Thanks to Bruce for catching this! Should be a nice boost in robustness + speed of the test suite.
=> Don't load external DTD in testing, better failure messages

lib/LaTeXML/Post/Manifest/Epub.pm, lib/LaTeXML/Util/Pack.pm
Hi,
I stumbled on this problem while trying to create an ePub for my new blog posts (soon to be online) and realized that the Manifest couldn't pick up any resources in the subdirectories under OPS.
In my concrete example I needed to generate a manifest ```OPS/content.opf``` file that contained an item for a nested image file:
```xml
<item id="app-assets-images-pointers.png" href="app/assets/images/pointers.png" 
media-type="image/png"/>
```
I used the core File::Find module for traversing the subdirectories, and sanitized the produced item IDs to be NCNames. 
I also removed some code duplication in the Pack post-processor and made sure LaTeXML.cache is never added to the archive. 
If you are happy with using File::Find, this is ready to merge. I haven't added a test for it yet though, …
=> Patch ePub image packing for files in subdirectories

README.pod
Amazingly, I am still feeling picky about the README file.
Here is a suggestion for a few improvements, and I even did them in POD!
=> Tidying up README.pod

Changes
=> Fixed a typo in my name

doc/manual/manual.tex
Hope I did everything right and edited the correct file! :wink:
=> Fixed a typo in manual.tex following issue #797

doc/site/index.tex
Also clarify that the flags should be passed to the latexmlpost command (I hope I got the markup right)
=> Fix typo in command line call

lib/LaTeXML/Package/TeX.pool.ltxml
=> Fix typo in enspace

lib/LaTeXML/Core/Document.pm
Different take on the now closed #952
=> Infinite building loop

lib/LaTeXML/Package/LaTeX.pool.ltxml
This PR upgrades the mentioned arXiv doc from a Fatal status to an Error status with a rather decent looking HTML output.
=> Teasing away Perl-level die for error arxiv doc 1802.05385

README.pod
Randomly clicked and noticed Bruce's homepage link has changed
=> update homepage link

lib/LaTeXML/Common/Locator.pm
Hi @brucemiller 
Please review the PR.
Many Thanks.
Best Regards,
Mohammad S Anwar
=> Fixed pod error as reported by CPANTS.

bin/latexml, bin/latexmlc, lib/LaTeXML/Util/Test.pm, t/96_fatal.t, t/daemon/broken.tex
=> non-zero exit code on fatal conversions for latexml+latexmlc

lib/LaTeXML/Package/LaTeX.pool.ltxml, t/complex/si.xml
=> lx@stackrel needs a reversion for mathimages

lib/LaTeXML/Package.pm, lib/LaTeXML/Package/LaTeX.pool.ltxml, lib/LaTeXML/Package/TeX.pool.ltxml
Random robustness fixes; added some new definitions in LaTeX; more forgiving about registers.
=> Random robustness fixes

README.pod
=> Point readme to travis-ci.com

lib/LaTeXML/Package.pm, lib/LaTeXML/Util/Pathname.pm
Fixes #1357, as prescribed by the issue reporter.
=> Allow double-loading .ldf files for babel

lib/LaTeXML/resources/CSS/ltx-article.css, lib/LaTeXML/resources/CSS/ltx-book.css, lib/LaTeXML/resources/CSS/ltx-report.css, lib/LaTeXML/resources/XSLT/LaTeXML-structure-xhtml.xsl
This should handle the scenario in aastex.
=> Better formatting of multiple dates

lib/LaTeXML/Package/LaTeX.pool.ltxml, t/fonts/textsymbols.xml, t/structure/filelist.xml
=> Always require textcomp in LaTeX.pool

lib/LaTeXML/Package.pm, lib/LaTeXML/Package/OmniBus.cls.ltxml, lib/LaTeXML/Package/booktabs.sty.ltxml
A few more random recursion fixes (and some along the way)
=> More recursions

lib/LaTeXML.pm
I'm briefly helping the MathIR folks from [ARQmath](https://www.cs.rit.edu/~dprl/ARQMath/), and preparing a turnkey solution for daemonized processing of tens of millions of formulas with latexml, notably from StackExchange.
On big part of that is stripping down all overhead one can find in the hand-over from the conversion harness to the LaTeXML.pm `->convert` call. Luckily, that is already mostly taken care of quite nicely in LaTeXML.pm, and some of the trickier bits I can ship separately as `latexmls` enhancements. The one bit that I would like to fine-tune here is allowing for reusing the same `cache_key` without specifying any other option. In latexmlc that would look as, for example:
Initial call with a range of options:
```
latexmlc --cache_key=example --expire=60 --whatsout=math …
```
=> Stricter get_converter which never overrides a set cache_key

MANIFEST, lib/LaTeXML/Package/SIunits.sty.ltxml, lib/LaTeXML/Package/hepunits.sty.ltxml, lib/LaTeXML/Package/revtex4_support.sty.ltxml
As it says. And it eases my conscience w.r.t. #1396
=> Binding for hepunits, SIunits; little patch for revtex4

lib/LaTeXML/resources/XSLT/LaTeXML-block-xhtml.xsl
Add download attribute to listings as per #1450
=> add download attribute to listings data

lib/LaTeXML/Package/pgfsys-latexml.def.ltxml
Recorded stops must be cleared globally; deconvolute the code while we're at it
Fixes #1479
=> fix pgf shading

lib/LaTeXML/Post/MakeBibliography.pm
=> Remove month from date before generating suffixes

lib/LaTeXML/resources/XSLT/LaTeXML-jats.xsl
Here's a PR, as discussed in #1500 
Should i try to add something in the spec LaTeX files?
Fixes #1500
=> Set href attribute in jats xslt

lib/LaTeXML/resources/XSLT/LaTeXML-jats.xsl, t/daemon/formats/jats.xml
Include ltx:title/ltx:tag when converting to JATS; update test case
fixes #1503
=> For JATS, include ltx:title/ltx:tag

bin/latexml, bin/latexmlc, bin/latexmlpost
Making sure we get slightly cleaner stderr cleanup on exit and status_code check for latexmlc, especially for Fatals (split from #1525 )
=> Touchup latexml/latexmlc exit

lib/LaTeXML/Common/Color/hsb.pm, lib/LaTeXML/Core/Document.pm, lib/LaTeXML/Core/Parameter.pm, lib/LaTeXML/MathParser.pm, lib/LaTeXML/Package/IEEEtran.cls.ltxml, lib/LaTeXML/Package/LaTeX.pool.ltxml, lib/LaTeXML/Package/TeX.pool.ltxml, lib/LaTeXML/Package/hyperref.sty.ltxml, lib/LaTeXML/Package/url.sty.ltxml, lib/LaTeXML/Package/xcolor.sty.ltxml, lib/LaTeXML/Post/SVG.pm
There are relatively minor long-tail bits, transferred from #1525 . I transferred them over by hand to a new branch, hopefully no typos got in.
=> Misc patches from arXiv Fatal errors

lib/LaTeXML/Common/Error.pm
~~Tiny~~ small fix to #1572 for Windows.
~~Running `system('')` enables the escape sequences, and disables them on exit, which is the desired behaviour with virtually no work. Also it is completely harmless even if it runs in the wrong terminal.~~ Now based on `Win32::Console`.
I think I did this in the right spot, fenced behind the availability of `Win32::Console` ~~(copied from the similar test from `Util::Pathname`)~~.
It works in both cmd.exe and PowerShell, at least for the versions I have at hand.
=> Enable VT100 emulation on Windows

lib/LaTeXML/Package/LaTeX.pool.ltxml, lib/LaTeXML/Package/OmniBus.cls.ltxml, lib/LaTeXML/Package/TeX.pool.ltxml, lib/LaTeXML/Package/aa_support.sty.ltxml, lib/LaTeXML/Package/amsppt.sty.ltxml, lib/LaTeXML/Package/colordvi.sty.ltxml, lib/LaTeXML/Package/diagbox.sty.ltxml, lib/LaTeXML/Package/enumitem.sty.ltxml, lib/LaTeXML/Package/float.sty.ltxml, lib/LaTeXML/Package/graphicx.sty.ltxml, lib/LaTeXML/Package/llncs.cls.ltxml, lib/LaTeXML/Package/newfloat.sty.ltxml, lib/LaTeXML/Package/physics.sty.ltxml, lib/LaTeXML/Package/pstricks.sty.ltxml, lib/LaTeXML/Package/subfig.sty.ltxml, lib/LaTeXML/Package/sv_support.sty.ltxml, t/alignment/diagboxtest.xml
As it says; I just couldn't help myself: a few random Error and Warning cleanups.
=> More arxiv patches

lib/LaTeXML/Package/pstricks.sty.ltxml
two steps forward, one back.
[wip, till sandbox run finished]
=> fix malicious typo

lib/LaTeXML/Core/State.pm
This fixes the regression piece in #771 , but only that much (e.g. the `/pgf/blue` key is still unrecognized and the color feature is not supported).
The regression was actually an opportunity to add a missing piece from the TeX interpretation side of things -- the internals of `pgfplots.code.tex` rely on `\globaldefs` to make certain assignments globally, which latexml hadn't yet emulated.
I tried my best to "hot code" the upgrade, as it will be checked extremely often in `assign_internal` (thanks to Bruce for pointing me to the right place in State!). 
While doing that I fell into a bunch of common traps, chiefly not realizing that getting the integer value of a Number register requires `->valueOf()->valueOf()` and perl will happily not tell you that you're not looking at an integer if …
=> Respect \globaldefs in assignments

lib/LaTeXML/resources/XSLT/LaTeXML-tei.xsl, t/daemon/formats/tei.xml
Updated and simplfied TEI stylesheet,  and validated the test case.
Comments and suggestsions from any and all TEI users, or potential ones, welcomed!
(@Thanathan-k ?)
=> Updates and simplify TEI stylesheet, and test case; validate

lib/LaTeXML/resources/XSLT/LaTeXML-jats.xsl, t/daemon/formats/jats.xml
Updated and simplified JATS stylesheet.
Attempted to validate.
Comments & suggestions requested from any and all JATS users, or potential ones.
(@rgieseke @xworld21  ??)
=> Update JATS stylesheet and sample, and validate

t/50_structure.t
Fixes #1474
It feels good to make a PR that changes a single character
=> Glossary test only runs on texlive 2016 or newer

bin/latexml
Signed-off-by: W. Michael Petullo <mike@flyn.org>
=> Add --log option to manual page

lib/LaTeXML/Post/MakeBibliography.pm
Fixes #1605
Previously, when the argument to `\bibliography` ended in `.bib` MakeBibliography would fail to find the requested bibliography file.
This was cause by it adding an extra '.bib' extension, even though there already was one.
This commit updates the behavior to only add a '.bib' extension if not already present.
=> Fix #1605: Allow \bibliography to include '.bib'

bin/latexml, bin/latexmlpost, lib/LaTeXML.pm, lib/LaTeXML/Common/Error.pm, lib/LaTeXML/Package/LaTeX.pool.ltxml
as it says....
Fixes #1560  (hopefully)
=> Make Debug print all lines to STDERR, and use it for reports of Fatal

lib/LaTeXML/Post/LaTeXImages.pm
dvisvgm 1.6 was released in 2014, is it time to drop the code around detecting the number of digits in the file names? The current code breaks on >99 images.
Alternatively I can add a few lines to detect say up to <10,000 images.
=> drop dvisvgm pre-1.6 compatibility

.gitignore, bin/latexml, bin/latexmlmath, bin/latexmlpost, doc/MakeTools.pm, doc/latexmldoc.css, doc/makemanual, doc/makesite, doc/manual/genpods, doc/manual/manual.tex, doc/site/index.tex, doc/sty/latexmlman.sty, lib/LaTeXML/Common/Config.pm, lib/LaTeXML/Common/Model/RelaxNG.pm, lib/LaTeXML/Common/XML.pm, lib/LaTeXML/Package.pm, lib/LaTeXML/Post/Split.pm, lib/LaTeXML/Post/XSLT.pm, lib/LaTeXML/Util/Radix.pm
An update to the Manual ( and site).
First patches, just for smooth building and stability.
fixes #1073
fixes #1402
fixes #1416
=> Manual update

lib/LaTeXML/Core/Definition/Expandable.pm, lib/LaTeXML/Core/Definition/Register.pm
A bit of tracing that helped me debug the infinite loops from #1685 as a standalone PR.
=> Small tracing upgrade to Registers

lib/LaTeXML/Package/babel_support.sty.ltxml, t/babel/german.xml
As it says; Yep, that looks better. Thanks molke!
fixes #1673
=> Correct right german quote marks 

lib/LaTeXML/Core/Document.pm, lib/LaTeXML/Package/TeX.pool.ltxml, lib/LaTeXML/Package/algorithmic.sty.ltxml, lib/LaTeXML/Package/algorithmicx.sty.ltxml
=> Arxiv malformed

lib/LaTeXML/Package/subcaption.sty.ltxml
Nice and simple PR, back to keeping things small.
=> a quick solution for \subfloat in subcaption.sty

lib/LaTeXML/Package/footmisc.sty.ltxml
As stated. Noticed we were getting errors on these in the Nov 2021 arXiv sandbox.
=> Additional macros from footmisc.sty

lib/LaTeXML/Common/Dimension.pm, lib/LaTeXML/Common/Font.pm, lib/LaTeXML/Core/Document.pm, lib/LaTeXML/Package/LaTeX.pool.ltxml, lib/LaTeXML/Package/TeX.pool.ltxml, lib/LaTeXML/Package/graphics.sty.ltxml, lib/LaTeXML/Post/CrossRef.pm
Some random fatal/error fixes. I doubt any of these are regressions from the most recent run, but a bit older.
=> Arxiv regressions

lib/LaTeXML/Package/array.sty.ltxml
=> Correctly define \arraybackslash

lib/LaTeXML/Package/acmart.cls.ltxml, lib/LaTeXML/Package/llncs.cls.ltxml, lib/LaTeXML/Package/pdfTeX.pool.ltxml, lib/LaTeXML/resources/RelaxNG/LaTeXML-structure.rnc, lib/LaTeXML/resources/RelaxNG/LaTeXML-structure.rng, lib/LaTeXML/resources/XSLT/LaTeXML-jats.xsl, lib/LaTeXML/resources/XSLT/LaTeXML-structure-xhtml.xsl, lib/LaTeXML/resources/XSLT/LaTeXML-tei.xsl
As stated.
Also neutralized two minor pdf-related macros.
=> macro \orcidID addition to llncs.sty

lib/LaTeXML/Package/pstricks.sty.ltxml
as it sez; @dginev merge if you're happy
=> fix optional coordinates in pstricks

lib/LaTeXML/Common/Glue.pm, lib/LaTeXML/Package.pm, lib/LaTeXML/Package/TeX.pool.ltxml, lib/LaTeXML/Package/amsmath.sty.ltxml, lib/LaTeXML/Package/overpic.sty.ltxml, lib/LaTeXML/Package/relsize.sty.ltxml, lib/LaTeXML/Package/xylatexml.tex.ltxml, lib/LaTeXML/Post/UnicodeMath.pm
As it says, various little bits of cleanup revealed by the arXiv sandbox run.
Ready to merge & re-run the sandbox if you like it.
=> Post xy cleanup

lib/LaTeXML/Package/amsmath.sty.ltxml
=> Add support for MaxMatrixCols

lib/LaTeXML/Package/LaTeX.pool.ltxml
=> set more reasonable default page sizes

lib/LaTeXML/Package/algorithm2e.sty.ltxml
=> Respect package options algochapter, etc; Thanks giovanni111

lib/LaTeXML/Package/enumitem.sty.ltxml
=> Put missing argument to setEnumerationStyle

lib/LaTeXML/Core/Gullet.pm
This may be a better alternative?
fixes #1938 
closes #1939
=> Be more careful looking for CC_ALIGN when scanning alignments

lib/LaTeXML/Post/MathML/Linebreaker.pm
=> Linebreaker needs to know about U+2212 as minus

lib/LaTeXML/Package/thmtools.sty.ltxml
=> Fixup \listoftheorems, partial options

lib/LaTeXML/resources/CSS/LaTeXML.css, lib/LaTeXML/resources/CSS/ltx-amsart.css, lib/LaTeXML/resources/CSS/ltx-apj.css, lib/LaTeXML/resources/CSS/ltx-article.css, lib/LaTeXML/resources/CSS/ltx-report.css
=>  Responsive margins

lib/LaTeXML/Post/MathML.pm
=> Deal with stray/unexpected XHMints in MathML

lib/LaTeXML/Core/Definition/Expandable.pm
As it says;  We had been deferring tokenization of macro bodies when given (in perl) as strings. That gives a small performance gain for multiple small conversions, but the extra checks are a penalty for conversions involving heavy expansion.
=> Dont defer tokenization of macro body

doc/latexmldoc.css, lib/LaTeXML/resources/CSS/LaTeXML-navbar-left.css, lib/LaTeXML/resources/CSS/LaTeXML-navbar-right.css
Simple css styling fix; Thanks @goska.
Fixes #2103
=> Style ol as well as ul in navbar

lib/LaTeXML/Package/listings.sty.ltxml
=> use value of name in \lstinputlisting

lib/LaTeXML/resources/XSLT/LaTeXML-structure-xhtml.xsl
=> Adjust html header levels in appendix corner cases

lib/LaTeXML/Package/lineno.sty.ltxml
=> Add linenomath environment

lib/LaTeXML/Package.pm, lib/LaTeXML/Package/LaTeX.pool.ltxml, lib/LaTeXML/Package/enumitem.sty.ltxml, lib/LaTeXML/resources/CSS/LaTeXML.css, t/keyval/keyvalstyle.xml
This PR fixes several itemization issues
Fixes #1645
Fixes #1927
Fixes #1961
Fixes #2155
=> Itemize fixes

lib/LaTeXML/Package/amsmath.sty.ltxml
=> Handle some amsmath options (reqno,leqno,fleqn)

lib/LaTeXML/Package/enumitem.sty.ltxml
=> Adds obsolete \setitemize, \setenumerate, \setdescription

lib/LaTeXML/Common/XML/Parser.pm, lib/LaTeXML/Core/Document.pm, lib/LaTeXML/MathParser.pm, lib/LaTeXML/Post.pm, lib/LaTeXML/Post/MathML.pm
Allows fully converting [arXiv:1004.2156](https://arxiv.org/pdf/1004.2156.pdf), especially the final polynomial on pages 84,85,86. Motivating screenshot from the PDF, and TeX source:
<details> 
```tex
\subsection*{Generic Offset Polynomial for Example \ref{exam:ch4:WhitneyUmbrella} (page \pageref{exam:ch4:WhitneyUmbrella})}\label{Ap3-ComplementsToSomeProofs-Whitney}
\nin {$ g(d,x_1,x_2,x_3)=-16{\,}x_1^2{\,}x_2^{10}{\,}x_3^2+16{\,}x_1^2{\,}x_2^{10}{\,}d^2-48{\,}x_1^2{\,}x_2^8{\,}x_3^4+128{\,}x_1^2{\,}x_2^8{\,}x_3^2{\,}d^2-80{\,}x_1^2{\,}x_2^8{\,}d^4-48{\,}x_1^2{\,}x_2^6{\,}x_3^6+240{\,}x_1^2{\,}x_2^6{\,}x_3^4{\,}d^2-352{\,}x_1^2{\,}x_2^6{\,}x_3^2{\,}d^4+160{\,}x_1^2{\,}x_2^6{\,}d^6-16{\,}x_1^2{\,}x_2^4{\,}x_3^8+160{\,}x_1^2{\,}x_2^4{\,}x_3^6{\,}d^2-432{\,}x_1^2{\,}x_2^4{\,}x_3^4{\,}d^4+448{ …
```
=> Avoid Fatal recursion on multi-page formulas

lib/LaTeXML/Package/braket.sty.ltxml
Fixes #2334 . Just a small set of reversion tweaks.
=> adjust reversions of \braket to use | separators

lib/LaTeXML/Package/pgfmath.code.tex.ltxml
One character fix for the very first item of #2478.
=> fix \pgfmathrand range

lib/LaTeXML/Package/iftex.sty.ltxml
As prompted by the recent iftex.sty github discussion, updating with the latest no-op macros from that package.
=> [minor] update to iftex 2022/02/03

.github/workflows/windows.yml
hoping that just updating the version is all that is needed.
=> Update actions/cache to v4

lib/LaTeXML/Util/Pack.pm
This small PR prepares latexml for the new `00README.json` metadata convention that succeeds the `00README.XXX` in arXiv's Submission v1.5 system.
This is not a core TeX enhancement, but follows the healthy practice of testing LaTeXML against the arXiv corpus for its annual releases. Pack.pm has existing support for `00README.XXX` when processing ZIP inputs, which this PR extends to `00README.json`.
I am marking this PR as a draft, until the new file format is officially documented at the [arXiv 00README documentation page](https://info.arxiv.org/help/00README.html). Tested on a couple of valid+invalid JSON files, the key target being entries of the form:
```json
{
"sources" : [
{
"usage" : "toplevel",
"filename" : "main.tex"
}
]
}
```
=> prepare for 00README.json new metadata directives from arXiv

lib/LaTeXML/Engine/latex_constructs.pool.ltxml, lib/LaTeXML/Package/amsmath.sty.ltxml, lib/LaTeXML/Package/amsrefs.sty.ltxml, lib/LaTeXML/Package/revtex3_support.sty.ltxml
Another small batch of patches, mostly about Fatals & Errors.
=> Ar xiv sandbox 3
